### ISSUE TITLE
国内ip列表里发现一条错误的

### ISSUE THREAD

**Issue by Mr-Fook** [ACL4SSR/ACL4SSR#10]
在103.86.70.0/23中，103.86.71.0/24并非国内ip，而是洛杉矶Zenlayer数据中心。

详见：http://bgp.he.net/net/103.86.71.0/24

**Comment by leosam1995** [comment]
这个国内IP段是用的ipip.NET 发行的。
其实我能理解为啥这样。因为牺牲一些小的ip段 来换来更快的速度。
ipip应该是用了网段插值优化
    此功能主要用于将多个不连续的小网段，通过插入一些网段将其合并成一个网段，以减少路由表中的项数，但插入网段后
    会使路由表变得粗糙，请根据需要选用。

**Comment by Mr-Fook** [comment]
然而我刚看了 17mon/china_ip_list , 他的最后一次更新已经修正了这个问题。
题外话，就算17mon没改， 在你们的ACL里也就103.86.70.0/23改成103.86.70.0/24这么一个步骤。
这个步骤和网段优化没有什么关系，是一个简单的修正....

**Comment by leosam1995** [comment]
那只能说没时间看ipip更没更新，我得写毕业论文，还有答辩。这些日子根本没时间。
如果你觉得对你很重要的话。你可以pull一下

**Comment by Mr-Fook** [comment]
。。偶然发现了就正常的发个Issues，改不改那是你们的事

**Comment by leosam1995** [comment]
改不改是我们的事，那你就不要说了

**Comment by BROBIRD** [comment]
你们下次可以直接甩锅给我……
