### ISSUE TITLE
关于google play无法下载

### ISSUE THREAD

**Issue by 741243716** [ACL4SSR/ACL4SSR#100]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
无论用哪个规则或者全局代理之后google play只能访问不能下载请问怎么解决?

**Comment by leosam1995** [comment]
那应该是你服务器问题。
可以尝试切换一下服务器 换条线路
或者分应用代理。
还不行的话 就升级一下play
再不行的话，就退出重新登陆下play

**Comment by 741243716** [comment]
服务器重装系统重装SSR重装锐速都不行，分代理也试过，退出重新登陆也试过都不行。跪求解决方案啊！

**Comment by BROBIRD** [comment]
国行手机基本都有这问题，和代理没啥关系……

**Comment by 741243716** [comment]
前几天还行从昨天开始就不行了
