### ISSUE TITLE
误杀云视听极光及银河奇异果扫码登录网址

### ISSUE THREAD

**Issue by Aidan-K** [ACL4SSR/ACL4SSR#101]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
使用上述勾选的ACL时无法扫码登录云视听极光及银河奇异果，显示网络错误，未使用时则可以
网址：
http://tv.aiseet.atianqi.com/i-tvbin/login/scanreport?p=b6CE4EF083D1F8BA82DAA2CB985E349F3
（正常打开后才会跳转到qq.com的网址）
http://tinyurl.ptqy.gitv.tv/6e6Nxex-1c56e1f6（跳转后的网址在两种情况下均可访问）

**Comment by BROBIRD** [comment]
是什么应用？麻烦您给一些截图，描述之类的

**Comment by Aidan-K** [comment]
是电视端播放视频的应用，可通过用手机扫描电视上显示的二维码登录
云视听极光：https://wapbaike.baidu.com/item/云视听极光/19874116?fr=aladdin
http://tv.qq.com
银河奇异果：http://baike.sogou.com/m/fullLemma?lid=158461168&fromTitle=银河奇异果
http://app.iqiyi.com/tv/player/index.html

**Comment by kljjh** [comment]
反正一次性的啦，关一下代理就好
