### ISSUE TITLE
ss能不能导入这个规则呢？

### ISSUE THREAD

**Issue by destincc** [ACL4SSR/ACL4SSR#102]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：ss-Android能调用这个规则吗？

**Comment by BROBIRD** [comment]
fullgfwlist.acl

**Comment by destincc** [comment]
我希望拥有banad呢？在ss的自定义规则里在线规则文件URL直接添加就可以了？ACL能得以应用？

**Comment by BROBIRD** [comment]
原版不支持
