### ISSUE TITLE
是否可以整合abp规则

### ISSUE THREAD

**Issue by chinuno-usami** [ACL4SSR/ACL4SSR#103]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
是否可以整合abp规则。比如
https://coding.net/u/HalfLife/p/list/git/raw/master/ad5.txt
这个列表，对国内的过滤比较全面，和acl的效果对比的确有不少网页广告用上面的规则可以过滤干净而acl去不掉的。
或者是否可以提供abp规则到acl的转换工具

**Comment by leosam1995** [comment]
abp中的规则能整合到acl里的 几乎都整合了。
acl去广告的原理是将一个网站用作广告投放的域名ban掉。
那么如果一个网站，他的一个域名，即用来放正常内容，又放广告。那样是不能将这个广告放倒acl列表中的。
abp和acl去广告的原理不一样。abp是网页元素和资源双重过滤。acl只能通过域名过滤
