### ISSUE TITLE
en.mi.com 和 en.miui.com 应走代理

### ISSUE THREAD

**Issue by xream** [ACL4SSR/ACL4SSR#107]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

`en.mi.com` 和 `en.miui.com` 应走代理, 目前会因为 `(^|\.)mi\.com$` 和 `(^|\.)miui\.com$` 全部直连了

**Comment by BROBIRD** [comment]
`en.mi.com`不存在A记录
`en.miui.com`直连访问没有问题

**Comment by xream** [comment]
抱歉 `en.mi.com` 应该是我记错了...
`en.miui.com` 直连太慢 既然有代理就优化下

**Comment by BROBIRD** [comment]
`en.miui.com`使用新加坡阿里云服务器，不存在访问障碍，请检查运营商是否存在劫持，本项目拒绝处理只有少量样本的问题。如有需要请自行修改。
