### ISSUE TITLE
优酷的视频前贴片广告没有拦截成功

### ISSUE THREAD

**Issue by sayyuan** [ACL4SSR/ACL4SSR#108]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
优酷的视频前贴片广告没有拦截成功

**Comment by leosam1995** [comment]
可以上zdfans网站上找专门去广告的软件装
http://www.zdfans.com/2059.html
surge能按网址后面的内容拦截 
这个没那功能，只能通过域名拦截。
