### ISSUE TITLE
Netflix TV版存在劫持不全的问题，希望添加解决方案

### ISSUE THREAD

**Issue by andrew-qiu** [ACL4SSR/ACL4SSR#11]
我用的Netflix Android TV版，目前遇到代理规则无法覆盖，造成Netflix无法打开的问题。根据如下讨论帖的信息：
https://www.v2ex.com/t/713564

发现可能问题有两个：
1、Netflix TV版存在IP直连问题，所以可能要添加各地区的IP直连地址
IP-CIDR,203.75.84.0/24,no-resolve
下面是原有的：
IP-CIDR,23.246.0.0/18,no-resolve
IP-CIDR,37.77.184.0/21,no-resolve
IP-CIDR,45.57.0.0/17,no-resolve
IP-CIDR,64.120.128.0/17,no-resolve
IP-CIDR,66.197.128.0/17,no-resolve
IP-CIDR,108.175.32.0/20,no-resolve
IP-CIDR,192.173.64.0/18,no-resolve
IP-CIDR,198.38.96.0/19,no-resolve
IP-CIDR,198.45.48.0/20,no-resolve

另外我还发现 Netflix 也用 AWS 的服务，所以我也一并把 DOMAIN-SUFFIX,[amazonaws.com](http://amazonaws.com/) 也添加到 Netflix 节点。还有一个是 DOMAIN-SUFFIX,[akamaiedge.net](http://akamaiedge.net/) 。这两个不一定需要添加，但我也懒得测试了，加了再说，反正最后没有问题了。

2、DNS劫持问题

希望作者大大可以帮忙添加下哦

**Comment by acl4ssr-sub** [comment]
IP-CIDR,203.75.84.0/24,no-resolve 

添加了，你检查一下？

**Comment by andrew-qiu** [comment]
> IP-CIDR,203.75.84.0/24,no-resolve
> 
> 添加了，你检查一下？

好嘞 感谢
