### ISSUE TITLE
影梭（ss）怎么使用acl文件呢？

### ISSUE THREAD

**Issue by ygfly** [ACL4SSR/ACL4SSR#110]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：影梭（ss）怎么使用acl文件呢？谁能给点提示？

**Comment by BROBIRD** [comment]
fullgfwlist.acl
