### ISSUE TITLE
请求将services.googleapis.cn域名添加到绕过大陆地址及大陆不可访问列表中。

### ISSUE THREAD

**Issue by ygfly** [ACL4SSR/ACL4SSR#111]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
请求将services.googleapis.cn域名添加到绕过大陆地址及大陆不可访问列表中。

**Comment by BROBIRD** [comment]
不明白您的意思

**Comment by ygfly** [comment]
更新安卓7.0后Play市场一直不能正常使用，除非全局代理，否则会提示"从服务器检索信息时出错 [DF-DFERH-01]”。原来是Google Play链接了services.googleapis.cn，这个地址，而这个地址返回的是空数据，，于是尝试把这个域名添加到代理链表，果然就能用了

**Comment by leosam1995** [comment]
googleapis.cn 都添加了
