### ISSUE TITLE
知乎视频被强制使用代理

### ISSUE THREAD

**Issue by ikelvingo** [ACL4SSR/ACL4SSR#112]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
知乎上的回答中嵌入的所有视频，播放时均被强制使用代理

**Comment by BROBIRD** [comment]
请抓包证明
