### ISSUE TITLE
影梭ss要怎样使用这些规则呢？

### ISSUE THREAD

**Issue by ygfly** [ACL4SSR/ACL4SSR#115]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
影梭ss 好像只有gfwlist-banAD.acl能运行，但去广告都无效。难道是我的姿势不对？ 我是在影梭的 自定义规则-手动设置-在线规则文件   里添加的。

**Comment by BROBIRD** [comment]
Duplicate of #110
请不要重复提交相同问题
