### ISSUE TITLE
Medium 不在gfwlist内

### ISSUE THREAD

**Issue by eliotce** [ACL4SSR/ACL4SSR#116]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

**Comment by BROBIRD** [comment]
请问这是什么？
https://github.com/ACL4SSR/ACL4SSR/blob/091ee42277966898c6d046493d6fc573b975afae/gfwlist-user.rule#L2859
https://github.com/ACL4SSR/ACL4SSR/blob/091ee42277966898c6d046493d6fc573b975afae/fullgfwlist.acl#L2925
https://github.com/ACL4SSR/ACL4SSR/blob/091ee42277966898c6d046493d6fc573b975afae/gfwlist-banAD.acl#L4121
