### ISSUE TITLE
广告屏蔽以及Windows电脑问题

### ISSUE THREAD

**Issue by 99junlin99** [ACL4SSR/ACL4SSR#118]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：无法屏蔽爱奇艺和优酷广告，在我把lines1的surge移植了大部分之后，突然可以，然后优酷广告还是不行。最后问下Windows版本的ssr如何编辑ip段，而且除了芒果tv，其余皆不行（移植后），这俩是不是软件的问题，有没有推荐的安卓或者Windows软件

**Comment by BROBIRD** [comment]
IP段？具体是哪个功能？
去广告推荐ADM（阿呆喵）
如果你认为你的移植经过测试不影响正常功能，可以提交Pull Request。

**Comment by 99junlin99** [comment]
我去试下阿呆猫把，安卓优酷广告不能屏蔽有点伤，有法子没

**Comment by BROBIRD** [comment]
目前没有好的办法……

另外提醒您 本项目使用 [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh)协议开源，您账号下的项目 https://github.com/99junlin99/ssracl 应当遵守此开源协议，协议中申明了以下条件：


>     署名 — 您必须给出适当的署名，提供指向本许可协议的链接，同时标明是否（对原始作品）作了修改。您可以用任何合理的方式来署名，但是不得以任何方式暗示许可人为您或您的使用背书。
> 
>     相同方式共享 — 如果您再混合、转换或者基于本作品进行创作，您必须基于与原先许可协议相同的许可协议 分发您贡献的作品。
> 
>     没有附加限制 — 您不得适用法律术语或者 技术措施 从而限制其他人做许可协议允许的事情。


虽然本项目维护者并没有意愿强制要求所有人遵守此协议，但是我们希望维护开源社区的行为准则。
另外我们发现，您在此项目的文件中删除了原维护者（本项目维护者）的相关信息，对此我们表示遗憾并提出异议。必要时我们将联系 Github 社区管理方进行处理。

我也在上方的回复中建议您给本项目提交 Pull Request 。或者在issue中说明您的修改，由项目维护者在项目中进行改动。

谢谢您的支持，也期待您的理解。
