### ISSUE TITLE
请讲把services.googleapi.cn加入代理列表

### ISSUE THREAD

**Issue by lzl119** [ACL4SSR/ACL4SSR#119]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：该域名会解析到国内网络导致gcm/fcm无法使用，香港ip无法连接Google play

**Comment by BROBIRD** [comment]
这是给Windows C#客户端用的，关Google Play什么事……

**Comment by lzl119** [comment]
什么意思？这个不能给安卓用吗？

**Comment by BROBIRD** [comment]
你们用一个项目的时候连最基本的README都不看的么……

**Comment by lzl119** [comment]
仅推荐未root的安卓手机使用
我这句话没理解错吧

**Comment by BROBIRD** [comment]
请问你所说的这个规则URL前面的文字是被你选择性无视了吗
