### ISSUE TITLE
华为音乐错误

### ISSUE THREAD

**Issue by LINRONGG** [ACL4SSR/ACL4SSR#121]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：华为手机自带音乐不能播放，浏览资源正常。

**Comment by LINRONGG** [comment]
华为自带音乐 开着SSR听不了在线音乐 显示连接超时 关掉就可以听 是不是去广告的原因？

**Comment by BROBIRD** [comment]
你觉得广告无法忍受吗？如果觉得可以忍受，可以用分应用代理模式。我有空看一下吧（

**Comment by LINRONGG** [comment]
再补上。。。广告应该把华为服务屏蔽了。。系统更新都屏蔽了，我开着SSR检测无更新。  关掉SSR之后检测我错过了两次更新

**Comment by BROBIRD** [comment]
……我都是直接用的分应用代理

**Comment by LINRONGG** [comment]
我试过分应用开白名单模式。。。微信QQ什么的。。息屏会断网。。

**Comment by BROBIRD** [comment]
息屏断网？具体是什么情况？我还真没留意这个……（我这里好像是正常的
