### ISSUE TITLE
可以的话建议单独区分微软服务和Copilot

### ISSUE THREAD

**Issue by XieLongWu** [ACL4SSR/ACL4SSR#121]
可以的话建议单独微软服务和Copilot规则分开
目前微软已经推送了23H2版本，可以开启Copilot

**Comment by XieLongWu** [comment]
> Copilot据我观察，就两个域名：
> 
> ```
> edgeservices.bing.com
> sydney.bing.com
> ```

感谢，实测自己手动添加这两个规则即可

**Comment by XieLongWu** [comment]
> > Copilot据我观察，就两个域名：
> > ```
> > edgeservices.bing.com
> > sydney.bing.com
> > ```
> 
> 感谢，实测自己手动添加这两个规则即可，我可以推送一个Pull吗

哦我好像没有权限在Github上克隆这个库，可惜了希望有能力的人可以推送一下

**Comment by fxzxmicah** [comment]
Copilot据我观察，就两个域名：
```
edgeservices.bing.com
sydney.bing.com
```

**Comment by XieLongWu** [comment]
https://github.com/ACL4SSR/ACL4SSR/pull/122

**Comment by fxzxmicah** [comment]
忘了说，还有一个小问题是，Bing AI（包括Copilot）图像生成用的都是`https://www.bing.com/images/create/`，所以对于域名规则来说，www.bing.com并不好分类，既属于Bing搜索引擎，又属于Copilot和Bing AI。

**Comment by XieLongWu** [comment]
> 忘了说，还有一个小问题是，Bing AI（包括Copilot）图像生成用的都是`https://www.bing.com/images/create/`，所以对于域名规则来说，www.bing.com并不好分类，既属于Bing搜索引擎，又属于Copilot和Bing AI。

有道理，毕竟上级域名都是属于bing.com。
不过个人测试下来单独把属于Copilot的子域名分类到Copilot能解决需要桌面Copilot但是又不想微软服务全走代理的问题。(目前这个规则www.bing.com还是会自动把我跳到cn.bing.com）
或者说可以把整个bing.com域名拿出来作为一整个规则供用户自己选择似乎也可以。毕竟bing.com还是分国际版和国内版，虽然我不太确定cn.bing.com中选择国际版和www.bing.com在实际上有没有区别，因为平时不太用bing搜索引擎。

**Comment by XieLongWu** [comment]
> > 忘了说，还有一个小问题是，Bing AI（包括Copilot）图像生成用的都是`https://www.bing.com/images/create/`，所以对于域名规则来说，www.bing.com并不好分类，既属于Bing搜索引擎，又属于Copilot和Bing AI。
> 
> 有道理，毕竟上级域名都是属于bing.com。 不过个人测试下来单独把属于Copilot的子域名分类到Copilot能解决需要桌面Copilot但是又不想微软服务全走代理的问题。(目前这个规则www.bing.com还是会自动把我跳到cn.bing.com） 或者说可以把整个bing.com域名拿出来作为一整个规则供用户自己选择似乎也可以。毕竟bing.com还是分国际版和国内版，虽然我不太确定cn.bing.com中选择国际版和www.bing.com在实际上有没有区别，因为平时不太用bing搜索引擎。

测试了一下，cn.bing.com的国际版也会强制限制安全搜索为严格，且语言强制显示为英文，所以直接将整个bing.com域名归到一个规则里进行单独代理更合适。实测代理到别的地区，且bing.com的地区设置为非中国大陆地区就可以解锁安全搜索，并且使用自己设置的语言。

**Comment by mujiannan** [comment]
Teams也应该单独拆出来，目前Teams是可以统一走直连的，视频会议更方便。

**Comment by XieLongWu** [comment]
> Teams也应该单独拆出来，目前Teams是可以统一走直连的，视频会议更方便。

个人感觉可能就微软Bing需要一直走代理，其他的服务好像都能直连。

**Comment by Mircc** [comment]
感谢,同有此需求,可惜大佬还没有合并,我看到你的已经自行添加了.我copy了下

**Comment by XieLongWu** [comment]
> 感谢,同有此需求,可惜大佬还没有合并,我看到你的已经自行添加了.我copy了下

这里一位大佬又提到了一个域名，你可以也添加一下试试。
https://github.com/ACL4SSR/ACL4SSR/pull/122#issuecomment-1818272021
