### ISSUE TITLE
你好，请问为啥电脑版的ssr的user.rule不更了？

### ISSUE THREAD

**Issue by dddog999** [ACL4SSR/ACL4SSR#123]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
你好，请问为啥电脑版的ssr的user.rule不更了？

**Comment by BROBIRD** [comment]
精力有限呀……抱歉啦，电脑上有更好的去广告方案，所以我们觉得意义不大

**Comment by dddog999** [comment]
谢谢回复
