### ISSUE TITLE
google翻译应走直连

### ISSUE THREAD

**Issue by alexlavigne** [ACL4SSR/ACL4SSR#125]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

https://translate.google.cn/ 这个地址应该走直联的，但是规则中没设置对，导致开代理时，andriod端的google翻译软件无法联网

**Comment by BROBIRD** [comment]
用分应用代理吧……

**Comment by BROBIRD** [comment]
而且就算走代理应该也是可以联网的
