### ISSUE TITLE
广告误杀反馈

### ISSUE THREAD

**Issue by bydx** [ACL4SSR/ACL4SSR#126]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
开启过滤后联通手机营业厅左上角签到入口消失，请求修复。

**Comment by BROBIRD** [comment]
用分应用代理

**Comment by bydx** [comment]
今天又发现飞猪流量中心的活动无法打开，虽然这两个完全是墙内应用，也希望能正视问题，难道发现一个误杀就屏蔽一个应用？

**Comment by BROBIRD** [comment]
如果您可以确定是什么域名下的广告，我们可以添加到规则里。我们维护精力有限，完全是用业余时间维护。开源项目依靠社区合作发展，希望您知晓。
