### ISSUE TITLE
请问banAD.acl能转换成dnsmasq规则么

### ISSUE THREAD

**Issue by 474364707** [ACL4SSR/ACL4SSR#127]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
banAD.acl能转换成dnsmasq规则么
server=/.0rz.tw/127.0.0.1#7913
ipset=/.0rz.tw/gfwlist
没有python环境
想替换梅林里的GFWList

**Comment by BROBIRD** [comment]
GFWlist不是比这个全很多么……
转换方法您可以自行摸索，我们暂时没有时间研究……
