### ISSUE TITLE
github官网被墙了，希望加入代理名单（MIUI浏览器内置黑名单，与墙无关）

### ISSUE THREAD

**Issue by Ouksnack** [ACL4SSR/ACL4SSR#128]
今天登录github官网提示根据国家法律禁止访问……希望代理规则加入代理名单，谢谢

**Comment by BROBIRD** [comment]
请给出证明

**Comment by Ouksnack** [comment]
访问https://github.com的时候自动转到了这个网址file:///android_asset/cac/warning.html，提示：根据国家法律法规，本页面禁止访问!

**Comment by BROBIRD** [comment]
此问题与本项目无关

**Comment by bydx** [comment]
能多用几个浏览器测试再下结论吗，建议远离MIUI浏览器

**Comment by Ouksnack** [comment]
是MIUI浏览器内部设置了黑名单

**Comment by Ouksnack** [comment]
卸载MIUI浏览器更新，使用系统自带浏览器就可以恢复使用了
