### ISSUE TITLE
请将GCM推送走直连，否则GCM每120s会重连一次

### ISSUE THREAD

**Issue by crazystone19840328** [ACL4SSR/ACL4SSR#131]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
请将GCM推送走直连，否则GCM每120s会重连一次，这个是ssr的bug，我关掉ssr，gcm是可以用的，但是开着ssr,就会120秒断开重新连接一次，我想让gcm走直连，是不是就可以解决这个问题呢，另外问一下，将一个域名加入[bypass_list]需要怎么写呢，例如“mtalk4.google.com“”，谢谢！！！

**Comment by leosam1995** [comment]
我手机 已经卸载了谷歌的全套
如果需要想加的话 需要把gcm的网址发给我

**Comment by BROBIRD** [comment]
120秒重连和ACL有什么关系……自己改服务端超时时间

**Comment by crazystone19840328** [comment]
你没有明白我的意思，120秒重连的确不是acl的问题，是ssr服务端的事情，超时时间已经设置为300，我说的是，将GCM走直连，不通过代理，这个ACL可以做到吧应该，如果不方便，可以我自己来修改，但是不知道是怎么写，例如mtalk4.google.com这个网址，要什么标记是走直连呢？

**Comment by BROBIRD** [comment]
bypass_list就是绕行

**Comment by crazystone19840328** [comment]
我知道，我说的是域名加到里面具体的格式，应该怎么来写

**Comment by BROBIRD** [comment]
参考正则表达式

**Comment by BROBIRD** [comment]
多一句嘴……改成直连我觉得大概率会连接不了 GCM

**Comment by crazystone19840328** [comment]
现在我用你的fullgfwlist，gcm在wifi和数据下心跳都正常了，我在河南，电信，即使我关掉ssr，GCM推送也是可以的，这个应该是分地区的
