### ISSUE TITLE
关于ACL全局代理时，指定域名直连，在WIFI下可以，数据网络下还是走代理的问题

### ISSUE THREAD

**Issue by crazystone19840328** [ACL4SSR/ACL4SSR#132]
# 全局代理时，指定域名直连，在WIFI下可以，数据网络下还是走代理
[proxy_all]
[bypass_list]
(^|\.)mtalk4\.google\.com$
(^|\.)mtalk\.google\.com$
(^|\.)alt1-mtalk\.google\.com$
(^|\.)alt2-mtalk\.google\.com$
(^|\.)alt3-mtalk\.google\.com$
(^|\.)alt4-mtalk\.google\.com$
(^|\.)alt5-mtalk\.google\.com$
(^|\.)alt6-mtalk\.google\.com$
(^|\.)alt7-mtalk\.google\.com$
(^|\.)alt8-mtalk\.google\.com$

哪位有空可以试一下
在wifi下，GCM是可以发送正常心跳的，数据网络下就不行了，120秒就会断开重新连接一次，很奇怪

如果我用[bypass_all]然后代理gfwlisi列表时，无论wifi还是数据，GCM心跳都是正常的

**Comment by crazystone19840328** [comment]
好的，我自己用的

**Comment by crazystone19840328** [comment]
点好转义也是不行，这个问题困扰了好久了，有一个办法可以解决我的问题(wifi和数据下均推送正常)，用[bypass_all]，gfwlist代理，但是这样有些没有收录的网站被墙

**Comment by BROBIRD** [comment]
这个就真的不知道了，同一个配置文件在不同网络下的表现应该是相同的
我这里测试似乎没有问题，网络环境是 CMCC 江苏

另外，无论是公开还是私人使用，只要使用了本项目原创的内容并且在公开渠道发布了，都请遵守[CC-BY-SA 4.0 协议](https://creativecommons.org/licenses/by-sa/4.0/deed.zh)，
包括但不限于保留原项目的信息，并注明您做的修改内容等。

> 共同维护开源社区秩序，人人有责。

**Comment by crazystone19840328** [comment]
好的，谢谢

**Comment by BROBIRD** [comment]
如果有发现随时保持沟通，我这里暂时复现不了，抱歉……

**Comment by BROBIRD** [comment]
@crazystone19840328 您这个Repository https://github.com/crazystone19840328/acl 没遵守 CC-BY-SA 4.0 协议啊
建议您至少把 fullgfwlist.acl 文件头的版权信息添加回去。
如果您实在不愿意改那我就要考虑提交DMCA Takedown Notice 了，抱歉。

**Comment by crazystone19840328** [comment]
好的，马上改

**Comment by BROBIRD** [comment]
感谢合作

**Comment by BROBIRD** [comment]
先行关闭了，如果仍然有问题可以继续评论或新开 Issue

**Comment by crazystone19840328** [comment]
好的，已经加上备注
