### ISSUE TITLE
饿了么 nr-op.elemecdn.com

### ISSUE THREAD

**Issue by fxzxmicah** [ACL4SSR/ACL4SSR#133]
[TCP] 172.19.0.1:42548 --> nr-op.elemecdn.com:443 match GeoIP(CN) using 🎯 全球直连[DIRECT]

elemecdn.com

**Comment by acl4ssr-sub** [comment]
这种的已经命中GeoIP(CN)  就不需要再加列表了

**Comment by fxzxmicah** [comment]
但是饿了么别的域名都加了，这个不加不合适吧？

**Comment by fxzxmicah** [comment]
真不加？别的饿了么规则也都能命中CN，那别的规则也都不需要，可以删了。
