### ISSUE TITLE
gfw white相关事宜

### ISSUE THREAD

**Issue by 99junlin99** [ACL4SSR/ACL4SSR#135]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：gfw white这项的直连都没用把，我测试了下这些网址，基本都是404.另外基于你的修改版我传到了我的github上，然后我的GitHub被封了，，，我现在已经删除了那个项目，接下来该怎么做？

**Comment by BROBIRD** [comment]
这规则是正则表达式，不是单一URL规则，浏览器访问为404不能说明任何问题。
如果要修改本项目的资源，请使用“Fork”功能，然后在自己的账号下遵守[CC BY-SA 4.0协议](https://creativecommons.org/licenses/by-sa/4.0/deed.zh)进行修改。
