### ISSUE TITLE
请问SSR#C的规则还能否更新

### ISSUE THREAD

**Issue by skyhutianwen** [ACL4SSR/ACL4SSR#137]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

**Comment by leosam1995** [comment]
电脑段还是直接用SwitchyOmega谷歌浏览器插件吧，这个的gfwList是实时更新的
扩展和基础的备份bak文件，在项目中刚刚上传了
教程可以参考https://doub.io/dbrj-13/
