### ISSUE TITLE
LAN 直连规则 enable

### ISSUE THREAD

**Issue by wu-cl** [ACL4SSR/ACL4SSR#138]
```
...
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
```
配置文件中，`GEOIP,LAN` 被注释掉了，会导致用 url 解析的 lan 地址走到最后的 final 匹配。
请问是个注释的原因是什么，有什么场景不能 cover 吗？

**Comment by acl4ssr-sub** [comment]
原因是有些geoip里面精简过度，没有加LAN区域，添加了会报错
如果你的地址判断里有的话，可以自己加上

**Comment by wu-cl** [comment]
抱歉这里表述不够准确，有些机场的自己规则会加上一条
`RULE-SET, LAN, DIRECT`
不是 geoip 增加 lan，是单独一条补上 lan 放行
