### ISSUE TITLE
请求添加一个劫持到的广告域名

### ISSUE THREAD

**Issue by lzz691997865** [ACL4SSR/ACL4SSR#138]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：有时浏览csdn(其他网站偶尔有)时会跳转到dnns.yongyuelm.com下的一个链接https://dnns.yongyuelm.com/S_2qc9gA/MDAwMDAwMDAwMJZ8i2TGqqetsmykbLF5ZNyoo00of5fZyL1oo00onoPPhquo000oZZ5hgaGHqsW5cbHAkJOsvaCF17KMrNmzuXuYhLWNr7F3rmSNZYKssOB5sLVoo00omq6xoHXZsqKo27PPd5iQz46lxnq2YIOIhq2wrHCwsqOnq7F5ZNuyfMqXstJ3qZjYdXIO0O0O_MDAwMDAwMDAwMJZ8i2TGroVtsrKbsLGKm9eo000oapiay85mnJmTaKvJn56qmXtoo00oZKoo00oUeqbJfZumvnpg2rKixt6zz4ashrV9rq6gq6SYeK1nvb2CnceQs2o000oxinmVsrKslbPfnKqEyHVy   有时候是弹出提示框说手机中毒了需要下载他的浏览器，然后就一直震动。有时是跳转到游戏广告

**Comment by BROBIRD** [comment]
？？？？？？？

**Comment by BROBIRD** [comment]
请按照 issue 模版填写

**Comment by lzz691997865** [comment]
十分抱歉，本来是写好的，传上来之后丢了

**Comment by BROBIRD** [comment]
下次更新应该会加上 感谢！

**Comment by lzz691997865** [comment]
好的，谢谢

**Comment by leosam1995** [comment]
已加入
