### ISSUE TITLE
请求添加一个广告域名

### ISSUE THREAD

**Issue by lzz691997865** [ACL4SSR/ACL4SSR#139]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：https://interaction.bayimob.com/static/baoxiang/index.html?hdgghtmlid=19&appkey=42049853088fb44e415e7a265f6a38df&adSpaceKey=221b420acf98702f77b78086d2edc319&t=1528067351976  这个会跳转到一个广告页面，有时浏览百度的时候会出现

**Comment by BROBIRD** [comment]
下次更新加入，感谢！

**Comment by leosam1995** [comment]
已加入
