### ISSUE TITLE
itunes.apple.com 希望能走代理

### ISSUE THREAD

**Issue by maxadjsky** [ACL4SSR/ACL4SSR#144]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [x] banAD.acl

* 您提交此issue的目的是：

- [x] 提交代理/直连域名

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
希望苹果的网站https://itunes.apple.com/能走代理，因为苹果屏蔽了中国的 IP

**Comment by leosam1995** [comment]
安卓的 需要加苹果的吗？ 有需求的话 可以给你加上

**Comment by maxadjsky** [comment]
@leosam1995 有需求的，谢谢

**Comment by leosam1995** [comment]
已添加
