### ISSUE TITLE
gfwlist-banADhk有问题？？

### ISSUE THREAD

**Issue by colorsakura** [ACL4SSR/ACL4SSR#145]
每次有这个ACL，SSR就closed by peer，其他的没有问题

**Comment by jsyzdej** [comment]
我也是，使用今天更新的gfwlist-banAD.acl时出现connection closed by peer导致无法科学上网
手机型号MI 6
Android版本8.0.0

**Comment by leosam1995** [comment]
只是今天的版本吗？

**Comment by leosam1995** [comment]
我修了一下 你试试 应该好了

**Comment by colorsakura** [comment]
没有问题了
