### ISSUE TITLE
尝试加入quora的域名, 但是无效, 到底怎么加呢?

### ISSUE THREAD

**Issue by YagamiLelouch** [ACL4SSR/ACL4SSR#148]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：尝试加入quora的域名, 但是无效, 到底怎么加呢?

**Comment by BROBIRD** [comment]
首先，这句话你看看见没有？
https://github.com/YagamiLelouch/Proxy/blob/8e8f9cf0e109490bc17a502da13f050027968f87/SSRGFWRoute.acl#L4
其次，你也没有说明你要加哪些域名？想要什么样的效果？
