### ISSUE TITLE
google play上DQ4,DQ5等游戏的云同步验证失败

### ISSUE THREAD

**Issue by asdfsega** [ACL4SSR/ACL4SSR#15]
使用SSR的自定义ACL无法正常验证，使用“绕过局域网和大陆地址”可以正常验证并下载云存档。

**Comment by BROBIRD** [comment]
请您尝试使用play store里的“Packet Capture”应用 抓包确认一下具体域名反馈给我们，谢谢您！

**Comment by asdfsega** [comment]
使用Packet Capture抓不到DQ系列......不知道是不是我用的不对，tailsman倒是抓得到。

**Comment by BROBIRD** [comment]
我们似乎也没有什么其他办法……
