### ISSUE TITLE
有没有 兴趣 支持 一下 v2rayNG？

### ISSUE THREAD

**Issue by Forty-nine** [ACL4SSR/ACL4SSR#150]
有没有 兴趣 支持 一下 v2rayNG？

**Comment by BROBIRD** [comment]
emmmm感觉格式有点复杂 可能近期没有计划支持

**Comment by LittleGrocery** [comment]
v2ray github有别的人有规则，我也把这份项目的规则手导了进去，两份都说能去广告和代理，至于哪份比较好真是不好说
但是如果能ssr我感觉还是用ssr比较好，因为资源占用比v2ray少很多啊

**Comment by leosam1024** [comment]
换clash吧 项目支持clash。
clash支持vmess协议。也可以去广告

**Comment by wuliao1223** [comment]
> 有没有 兴趣 支持 一下 v2rayNG？

v2ray用233脚本可以去广告

**Comment by alenelric** [comment]
> 换clash吧 项目支持clash。
> clash支持vmess协议。也可以去广告

v2rayNG支持tasker,能配置断开家里路由自动连接，到家连接WIFI之后自动关闭……这个有点香，以前用SSR就这样很舒服，基本上不需要手动操作

**Comment by txyyh** [comment]
> > 换clash吧 项目支持clash。
> > clash支持vmess协议。也可以去广告
> 
> v2rayNG支持tasker,能配置断开家里路由自动连接，到家连接WIFI之后自动关闭……这个有点香，以前用SSR就这样很舒服，基本上不需要手动操作

额，tasker 是可以对未支持tasker的应用操作的

**Comment by alenelric** [comment]
> > > 换clash吧 项目支持clash。
> > > clash支持vmess协议。也可以去广告
> > 
> > 
> > v2rayNG支持tasker,能配置断开家里路由自动连接，到家连接WIFI之后自动关闭……这个有点香，以前用SSR就这样很舒服，基本上不需要手动操作
> 
> 额，tasker 是可以对未支持tasker的应用操作的

也需要应用满足条件才行吧，你说的应该是类似下面这样吧
am start -n com.eg.android.AlipayGphone/com.alipay.mobile.scan.as.main.MainCaptureActivity
