### ISSUE TITLE
请求更新对 reddit 的支持

### ISSUE THREAD

**Issue by JackRBlack** [ACL4SSR/ACL4SSR#151]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
[已修改] 目前 reddit 无法直连访问。我已尝试在 proxy_list 中添加 
```
(^|\.)reddit\.com$
```
但是没有效果（我并不清楚 ACL 文件的编写格式，但简单的模仿似乎不 work）。

**Comment by BROBIRD** [comment]
你确定你读了README？

**Comment by BROBIRD** [comment]
我在之前的issue中也说过了，SSR默认的超时时间是600s，请自己检查服务端的配置。

**Comment by JackRBlack** [comment]
有趣的是我一旦使用 gfwlist-banAD.acl 后就没这个问题了。。。 gcm 非常稳定。

**Comment by BROBIRD** [comment]
reddit我们评估（参考GFWList）之后会决定是否加入，GCM的问题我们需要更多更详细的测试样本。

**Comment by JackRBlack** [comment]
十分感谢，辛苦开发者了 👍

**Comment by leosam1995** [comment]
已经添加
