### ISSUE TITLE
ShadowsocksX-NG可否订阅此名单？

### ISSUE THREAD

**Issue by fuzheng1998** [ACL4SSR/ACL4SSR#153]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

**Comment by BROBIRD** [comment]
之前是可以的，现在不清楚，你可以试一下

**Comment by fuzheng1998** [comment]
亲测有效，用udacity，白名单会自动变成英文的总站
