### ISSUE TITLE
提交广告域名，同时提供一个 广告list

### ISSUE THREAD

**Issue by sullevy** [ACL4SSR/ACL4SSR#154]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

yunpifu.cn
广告域名

建议，合并这个 repo 中的 adlist.conf  [LINK](https://github.com/h2y/Shadowrocket-ADBlock-Rules/blob/master/sr_cnip_ad.conf)

**Comment by leosam1995** [comment]
收到 已经合并
