### ISSUE TITLE
.rule一直就没更新了么……

### ISSUE THREAD

**Issue by hengyuanma** [ACL4SSR/ACL4SSR#155]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

.acl一直在更新，但给PC用的.rule一直就没更新了……请问有什么方法可以把acl转换成rule规则吗？
对比了一下文本，感觉不是换指令就能解决的，似乎复杂一些……

**Comment by BROBIRD** [comment]
PC没必要用rule吧……Windows端的去广告软件很多，功能也比SSR强大。目前没有更新的计划……
