### ISSUE TITLE
有关优酷爱奇艺广告的反馈

### ISSUE THREAD

**Issue by LittleGrocery** [ACL4SSR/ACL4SSR#157]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
1.爱奇艺不能播放广告就直接无法播放视频了
2.优酷已无法阻止视频开头的广告

**Comment by leosam1995** [comment]
优酷的拦不了。ssr软件不支持url拦截
iqiyi的 你下一个谷歌商店的iqiyi吧。天生没广告。只要用ssr ，不管什么规则。好像iqiyi网页版的就打不开

**Comment by CallMeNullPointException** [comment]
> 优酷的拦不了。ssr软件不支持url拦截
> iqiyi的 你下一个谷歌商店的iqiyi吧。天生没广告。只要用ssr ，不管什么规则。好像iqiyi网页版的就打不开

好的谢谢你
