### ISSUE TITLE
请问您这个路由中的去广告规则能够使用唉openwrt的路由器中么？

### ISSUE THREAD

**Issue by ssswww0004** [ACL4SSR/ACL4SSR#163]
* 您要反馈的问题：
请问您这个路由中的去广告规则能够使用唉openwrt的路由器中么？如果能够使用，请问怎么使用，如何让openwrt能够识别您的去广告规则？谢谢

**Comment by LittleGrocery** [comment]
这种有教程的吧？

**Comment by BROBIRD** [comment]
那就要问固件作者/openwrt-ss的作者有没有编译支持ACL并且支持本项目中的语法了

**Comment by ssswww0004** [comment]
你好，我之前在路由器上成功使用过vokins大神的主机去广告规则，请问您这个是否也可以和vokins大神的主机规则一样？如果一样的话那我就试试。谢谢

**Comment by BROBIRD** [comment]
@ssswww0004 请不要在本项目中提及这个人，谢谢。本项目拒绝与这个人产生任何形式的联系。

**Comment by ssswww0004** [comment]
好的，我知道了！不好意思！那我问下您这个和host去广告有很大的区别吗？能通过ABP的规则来修改么？

**Comment by BROBIRD** [comment]
语法只支持SS/SSR，你可以根据列表中的域名自行修改语法，修改时请保留版权及遵守开源协议。总体效果弱于ABP，与hosts相当。
