### ISSUE TITLE
SSR客户端显示SSL handshake overtime

### ISSUE THREAD

**Issue by frankpen** [ACL4SSR/ACL4SSR#169]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
  在安卓ssr客户端中,路由使用自定义规则,链接后总是显示ssl 握手超时,导致不能上网

**Comment by BROBIRD** [comment]
和本项目无关

**Comment by slaier** [comment]
url填错，填写<https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/gfwlist-banAD.acl>

**Comment by frankpen** [comment]
你怎么猜到的？！ 确实是没有使用raw地址导致的错误！谢谢！佩服
