### ISSUE TITLE
请将t.cn加入白名单吧

### ISSUE THREAD

**Issue by GreatFinger** [ACL4SSR/ACL4SSR#17]
t.cn短链打不开，关掉ssr代理便能打开了。

**Comment by BROBIRD** [comment]
请问您具体使用的是哪一个规则？

**Comment by GreatFinger** [comment]
我用的是（banAD.acl （默认代理）去广告+局域网直连+国内IP段直连+国内常用域名直连+国外代理）

**Comment by BROBIRD** [comment]
实测该规则并没有问题，请您检查其他有可能的原因。

**Comment by vsxen** [comment]
t.cn最近抽风了吧 经常遇到
