### ISSUE TITLE
建议移除steamcdn-a.akamaihd.net 域名

### ISSUE THREAD

**Issue by graytoowolf** [ACL4SSR/ACL4SSR#17]
steamcdn-a.akamaihd.net是一个由Steam（一个数字发行平台）使用的内容分发网络（CDN）域名。它用于分发Steam客户端和游戏的更新、下载和其他相关文件，以提高下载速度和可靠性。该域名由Akamai Technologies公司提供支持，该公司是一家全球领先的云服务提供商之一。

**Comment by yxymeng** [comment]
请问一下，此域名直连就行吗？只影响下载而不影响其他的吗？因为现在虽然还没移除此域名，但是下载也是走直连的路线。

**Comment by caliban511** [comment]
确实，这个系列域名应该直连的，steam下载游戏时如果走了这个的话，还是很坑的，几十G流量很快就能跑出去，，我上个月有200G流量莫名其妙跑没了，怀疑就是走了这个，，我后来在openclash的高优先自定义规则里自己加了几条直连规则，，现在没有遇到类似问题了，，，

**Comment by pkoukk** [comment]
#36 
目前已经删除了
