### ISSUE TITLE
(analytics|locdrop|onepush)\.query\.yahoo\.com$导致tumblr app不能翻页

### ISSUE THREAD

**Issue by qgtxqj** [ACL4SSR/ACL4SSR#173]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
(analytics|locdrop|onepush)\.query\.yahoo\.com$
这条规则屏蔽analytics.query.yahoo.com，会导致tumblr app浏览不能翻页。

**Comment by BROBIRD** [comment]
经测试，可以正常翻页……

**Comment by qgtxqj** [comment]
这个域名不是每次翻页都去访问，我是用bifrostv查看流量记录才发现这个问题的。
