### ISSUE TITLE
提交广告域名

### ISSUE THREAD

**Issue by Awu1d** [ACL4SSR/ACL4SSR#177]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
你好，最近几天受困于斐讯路由器的广告骚扰，实在受不了了，自行进行了网络抓包，发现广告域名为ck.kejet.net，查询大佬编写的规则，发现ACL文件内已包含了关键字“kejet”的拦截项，但实际上未对其进行屏蔽拦截，恳请大佬在下次更新时处理一下，辛苦大佬了

**Comment by leosam1995** [comment]
我看kejet.com 和kejet.net 都加入了 还有问题吗

**Comment by Awu1d** [comment]
现在解决了，我直接把路由器刷机就好了
