### ISSUE TITLE
在Linux桌面下如何使用此规则

### ISSUE THREAD

**Issue by Howard-00** [ACL4SSR/ACL4SSR#179]
* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
在Linux桌面下如何使用此规则

**Comment by BROBIRD** [comment]
自己找能用的客户端呗
