### ISSUE TITLE
多久会和GFWlist同步一次？

### ISSUE THREAD

**Issue by DearTanker** [ACL4SSR/ACL4SSR#181]
貌似 behance.net 还没同步过来？

**Comment by NateScarlet** [comment]
试试 https://raw.githubusercontent.com/NateScarlet/gfwlist.acl/master/gfwlist.acl 每天自动更新

**Comment by DearTanker** [comment]
很棒。谢谢。

**Comment by NateScarlet** [comment]
不懂java打包 打包脚本加行curl能实现不

**Comment by DearTanker** [comment]
> 不懂java打包 打包脚本加行curl能实现不

理论上，最好是在有更新的时候自动给 Shadowsocks Android 项目 pull request 一下。这样那边的项目作者就可以 Merge 进代码了。

**Comment by BROBIRD** [comment]
是纯手动同步的，自动同步已经在计划中了，但是目前还没有空闲的时间做

**Comment by leosam1995** [comment]
已经同步
