### ISSUE TITLE
TalkingData 官网疑似被广告策略 BanAD.list 误伤

### ISSUE THREAD

**Issue by JosephusZhou** [ACL4SSR/ACL4SSR#181]
在 /Clash/BanAD.list 文件中，talkingdata.com 被加入到其中遭到广告规则的拦截处理。
我作为一个开发者，使用到了talkingdata 提供的数据统计服务，在电脑使用 clash + acl4ssr 去广告规则时发现无法访问 talkingdata 官网（talkingdata.com）去登录管理项目。
请问是否应该将其更加细化处理，处理对应的有广告问题的二级域名（比如xxx.talkingdata.com），而不是将整个一级域名一杆子打死？

**Comment by fxzxmicah** [comment]
特殊需求建议自行维护一个规则仓库。另外如果非要用这里的规则，建议直接给出子域列表。

**Comment by JosephusZhou** [comment]
> 特殊需求建议自行维护一个规则仓库。另外如果非要用这里的规则，建议直接给出子域列表。

目前我也不确定 talkingdata.com 涉及广告的子域名，看来只能自己 fork 维护规则了。
