### ISSUE TITLE
ip更新请求

### ISSUE THREAD

**Issue by Upapanow** [ACL4SSR/ACL4SSR#182]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ x] backcn-banAD.acl
- [ x] banAD.acl
- [x ] fullgfwlist.acl
- [x ] gfwlist-banAD.acl
- [x ] gfwlist-user.rule
- [x ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
telegram和one drive下载文档和视频速速极慢，请求作者能够跟新IP段

**Comment by BROBIRD** [comment]
Telegram没有新的IP啊？Onedrive也不是靠IP连接的。你的问题应该和本项目无关。

**Comment by Upapanow** [comment]
好的，谢谢了
