### ISSUE TITLE
为什么proxy_all之后还需要proxy_list?

### ISSUE THREAD

**Issue by wilsli** [ACL4SSR/ACL4SSR#183]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

本人用mac版的ShadowsocksX-NG-R客户端，已经搞明白了它的“ACL Auto“模式实际上是在~/.ShadowsocksX-NG/gfwlist.acl文件后面加上了user-rule.txt里的域名，而它的“Whitelist Mode“则是用了~/.ShadowsocksX-NG/chn.acl文件，考虑到我打算默认翻墙仅直连国内网站，我以为只需要在chn.acl里保留[proxy_all]和[bypass_list]就可以了，于是把[proxy_list]全部删除，然而删除后可以访问谷歌脸书推特等网页，但是有部分网站访问不了（我的case是xmind.net无法访问，而把这个域名添加到PAC列表里切换到PAC模式或者ACL Auto模式都没有问题）。
在别的地方看到有人说ACL文件用了[proxy_all]之后还是需要用[proxy_list]列出一些所谓“conner case“[（帖子链接在这里）](https://github.com/shadowsocks/shadowsocks-android/issues/1895)，这是什么意思呢？难道没有办法一劳永逸地绕开国内域名和IP默认走代理吗？

**Comment by BROBIRD** [comment]
@leosam1995 建议的，防止漏网之鱼

**Comment by wilsli** [comment]
> @leosam1995 建议的，防止漏网之鱼

不是proxy_all了吗？还有漏网之鱼吗？

**Comment by wilsli** [comment]
我用了原作者qinyuhang的chn.acl（里面就是没有[proxy_list]部分的），White List Mode就正常了，奇怪！

**Comment by BROBIRD** [comment]
> 
> 
> 我用了原作者qinyuhang的chn.acl（里面就是没有[proxy_list]部分的），White List Mode就正常了，奇怪！

这个你需要问作者……每个客户端使用ACL的具体逻辑我不是很清楚

**Comment by wilsli** [comment]
> > 我用了原作者qinyuhang的chn.acl（里面就是没有[proxy_list]部分的），White List Mode就正常了，奇怪！
> 
> 这个你需要问作者……每个客户端使用ACL的具体逻辑我不是很清楚

非常感谢你的回答。

**Comment by Loyalsoldier** [comment]
可以用这个项目里的 `nobanAD.acl` 规则文件 URL([https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/nobanAD.acl](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/nobanAD.acl)) 替换掉 `Shadowsocks-X-NG-R` 的`高级设置`选项里的 `ACL GFW List 列表 URL`地址，然后使用 `ACL 自动 - ACL 自动`模式运行软件。`nobanAD.acl` 默认规则就是**国内直连、国外全走代理**。

![演示截图](https://user-images.githubusercontent.com/10487845/56871185-bba93c80-6a4c-11e9-985d-d6024b3cedc3.jpg)
