### ISSUE TITLE
运营商劫持之后跳转的广告域名

### ISSUE THREAD

**Issue by lzz691997865** [ACL4SSR/ACL4SSR#187]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
跳转到的广告链接:https://m.wep016.top/2018qdlg_3/p7031z.html?20190325090701&t=1971861995&f=1&i=1

**Comment by leosam1995** [comment]
已添加
