### ISSUE TITLE
局域网问题

### ISSUE THREAD

**Issue by marxvr** [ACL4SSR/ACL4SSR#189]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
你好，想请教一下，如果要访问ssr服务端的局域网，需要加什么规则，例如192.168.1.x的需要在Proxylist中添加什么？

**Comment by BROBIRD** [comment]
抱歉，这个问题我确实不知道
