### ISSUE TITLE
航旅纵横app无法访问，提示网络错误。

### ISSUE THREAD

**Issue by qwerpoiugb** [ACL4SSR/ACL4SSR#190]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
航旅纵横app打开后不显示内容，提示网络错误。

**Comment by BROBIRD** [comment]
使用分应用代理
