### ISSUE TITLE
mac SSR 如何使用acl？

### ISSUE THREAD

**Issue by amomonkey** [ACL4SSR/ACL4SSR#193]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题
* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
更新白名单，并把模式设置成ACL自动后如何使用？好像并不是白名单模式。
请问具体的操作方式是怎么样？

<img width="687" alt="屏幕快照 2019-04-28 上午9 53 46" src="https://user-images.githubusercontent.com/30174930/56857085-94defd80-699b-11e9-842a-67949f28789c.png">

**Comment by BROBIRD** [comment]
请咨询相关软件作者
