### ISSUE TITLE
没有behance

### ISSUE THREAD

**Issue by 5iux** [ACL4SSR/ACL4SSR#196]
* 有关此issue的规则名称：

- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl

* 您提交此issue的目的是：

- [x] 提交代理/直连域名

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
没有behance的域名
behance.net
be.net

**Comment by BROBIRD** [comment]
请贴出广告出现的具体位置、广告资源的域名信息截图等

**Comment by 5iux** [comment]
> 请贴出广告出现的具体位置，广告资源的域名信息截图等

behance被墙了

**Comment by BROBIRD** [comment]
你自己看看你填的是啥……

请等待下次与GFWList的同步

**Comment by 5iux** [comment]
大佬我错了😂
