### ISSUE TITLE
Ruleset syntax error

### ISSUE THREAD

**Issue by s1ro6** [ACL4SSR/ACL4SSR#2]
Error syntax:
`ejghgjhhgadcdchjaada.ru.` -> `ejghgjhhgadcdchjaada.ru`

Rule File:
1. `https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/BanEasyList.yaml`
2. `https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/BanEasyList.list`

**Comment by acl4ssr-sub** [comment]
FIX
