### ISSUE TITLE
请添加域名koolshare.cn走代理谢谢

### ISSUE THREAD

**Issue by MichaelHu55** [ACL4SSR/ACL4SSR#20]
开启ssr后，koolshare.cn分配给联通网络cdn ip，打不开。关闭ssr,正常。开全局也正常。
已测试只在联通网络下有这个问题。

**Comment by BROBIRD** [comment]
请补充说明一下你的网络环境和使用规则名称，谢谢

**Comment by MichaelHu55** [comment]
网络环境，深圳联通和联通lte网络
规则，nobanAD.acl

**Comment by BROBIRD** [comment]
有没有检查一下是否是本地DNS的问题？使用17ce的深圳联通节点测试并没有问题。

**Comment by MichaelHu55** [comment]
单纯测试是没有问题的，只是开了ssr后就打不开了。我已测试电信移动没问题。估计是联通的问题。我将nobanAD.acl的MyList里添加一条koolshare.cn，就可以打开。

**Comment by MichaelHu55** [comment]
测试的话，拿个联通的手机，用lte上网，开ssr,路由设为自定义acl,或绕过国内ip。访问koolshare.cn就可发现这个问题 .

**Comment by BROBIRD** [comment]
可以上传一下错误页面的截图吗

**Comment by MichaelHu55** [comment]
该网页无法正常运作

koolshare.cn 未发送任何数据。

ERR_EMPTY_RESPONSE

我电脑不在身边，图片上就是显示这些

**Comment by MichaelHu55** [comment]
https://photos.app.goo.gl/PlewJC1giJilZUcp2

**Comment by BROBIRD** [comment]
这个有点像是被拦截了，但是这个规则本身没有去广告的条目啊？能否请您尝试一下banAD.acl，另外尝试修改一下ChinaDNS，看看能不能访问。我们这里没有发现规则上的问题。谢谢！

**Comment by MichaelHu55** [comment]
试了banad.acl,问题依旧。chinadns改为119.29.29.29,也是一样。

**Comment by BROBIRD** [comment]
检查一下“转发UDP”是否是关闭的，然后更新一下ACL文件试试。

**Comment by MichaelHu55** [comment]
更新了ACL，udp转发是打开的。问题还是依旧。

**Comment by BROBIRD** [comment]
UDP转发保持关闭……

**Comment by MichaelHu55** [comment]
我用的节点，必须开启，udp转发。不然连不上节点。。。

**Comment by MichaelHu55** [comment]
我的手机换上移动卡4g,就没有这个问题。应该这个锅就是联通背吧。或者就是这个网站对联通做的cdn节点问题。

**Comment by BROBIRD** [comment]
这种个例情况我们不会修改规则的，你可以在遵守协议的前提下自行fork修改适合自己使用的规则文件。同时根据你的描述，你可以尝试向您的ss服务提供商或联通公司反馈。

**Comment by MichaelHu55** [comment]
嗯，好的。谢谢了

**Comment by BROBIRD** [comment]
不客气，欢迎并感谢你关注我们的项目。

**Comment by MichaelHu55** [comment]
我已经通过修改hosts文件,重定向域名到香港ip,这样就解决了。不需要自已手动改acl文件了。谢谢了
