### ISSUE TITLE
B站客户端 加载不出图片

### ISSUE THREAD

**Issue by lbwstco** [ACL4SSR/ACL4SSR#201]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

用了此规则B站图片都无法访问了

**Comment by BROBIRD** [comment]
善用分应用代理

**Comment by BROBIRD** [comment]
另外记得把UDP转发关掉

**Comment by a8778700** [comment]
开了分代理就不能用规则了

**Comment by BROBIRD** [comment]
无法复现
