### ISSUE TITLE
开启banAD或gfwlist-banAD后，微信朋友圈，微博（国际版）等日常app的图像、视频载入十分缓慢。

### ISSUE THREAD

**Issue by ck629** [ACL4SSR/ACL4SSR#202]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
开启banAD或gfwlist-banAD后，微信朋友圈，微博（国际版）等日常app的图像、视频载入十分缓慢。

**Comment by BROBIRD** [comment]
#201

**Comment by ck629** [comment]
> #201

可是仍有去广告需求啊，尤其是微博

**Comment by BROBIRD** [comment]
实测并没有什么明显的速度差异

**Comment by ck629** [comment]
> 实测并没有什么明显的速度差异

刚弄了两个录屏，不知道怎么在这里传视频，传到GD了，可以去看看。
[https://drive.google.com/folderview?id=1Zf6hJVh1IvPSeUMAXkEnbWuD_lwoc1rU](url)

**Comment by BROBIRD** [comment]
顺便发一下你的设置（注意把隐私信息隐去）

**Comment by BROBIRD** [comment]
上面那个链接我没有访问权限……

**Comment by ck629** [comment]
> 上面那个链接我没有访问权限……

呃，是我没弄好，直接发你邮箱吧。

**Comment by BROBIRD** [comment]
……你开UDP转发肯定慢啊……像微博这种全球都有CDN的网站，解析到海外的IP再从境内连过去不慢就有鬼了……

**Comment by BROBIRD** [comment]
别忘了DNS是基于UDP协议的啊大兄弟😂

**Comment by ck629** [comment]
> ……你开UDP转发肯定慢啊……像微博这种全球都有CDN的网站，解析到海外的IP再从境内连过去不慢就有鬼了……

之前玩儿游戏开了然后忘了关，制杖了……sorry

**Comment by BROBIRD** [comment]
😂
