### ISSUE TITLE
无法正常使用googleplay

### ISSUE THREAD

**Issue by wzhb** [ACL4SSR/ACL4SSR#205]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
最近新买的手机全局或是使用你们的acl都无法使用googleplay
![image](https://user-images.githubusercontent.com/14255631/59014338-f3d34480-886e-11e9-944c-005c64af3b5d.png)

**Comment by BROBIRD** [comment]
> 全局或是使用你们的acl都无法使用googleplay
那就与本项目无关了

**Comment by wzhb** [comment]
用的是你们的acl呀，我勾选了

**Comment by BROBIRD** [comment]
你用全局都用不了，我也没办法啊

**Comment by wzhb** [comment]
奇怪的是我原先的手机googleplay完全可以使用，新的手机就不行

**Comment by BROBIRD** [comment]
所以说和这个项目没关系啊……我也爱莫能助

**Comment by wzhb** [comment]
嗯，好，谢谢

**Comment by BROBIRD** [comment]
我之前遇到这个问题的时候是和DNS有关，你可以排查一下

**Comment by wzhb** [comment]
明白，我去试试，谢谢。

**Comment by BROBIRD** [comment]
先 Close 了，发现与项目有关的问题可以再来提（
