### ISSUE TITLE
gfwlist微信朋友圈加载慢

### ISSUE THREAD

**Issue by ChenXingbo** [ACL4SSR/ACL4SSR#206]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
之前通过gfwlist使用微信一切正常，更新后发现微信朋友圈图片加载速度特别慢，请问该如何解决？

**Comment by y1zhou** [comment]
`banad.acl`有同样的问题

**Comment by BROBIRD** [comment]
duplicate of #199

**Comment by ChenXingbo** [comment]
谢谢大佬~
