### ISSUE TITLE
Google应用商店DF-DFERH-01问题

### ISSUE THREAD

**Issue by GoingTime** [ACL4SSR/ACL4SSR#209]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

目前部分国产手机预置Google服务，但是配置文件使用的是services.googleapis.cn。而国际版本则是用的services.googleapis.com。

由于在GFW的原因，大多数梯子默认分流的时候都会因为services.googleapis.cn后置的cn，而将这个域名解析到北京的某个服务器。所以解决这个问题的原理，就是将services.googleapis.cn解析到Google加州的服务器上。由于许多梯子只允许管理员更改分流规则，普通用户联系管理员修改很不方便，希望在ACL文件层面实现修改。

具体可见帖子：http://www.miui.com/thread-15970656-1-1.html

**Comment by BROBIRD** [comment]
Duplicate of #203
