### ISSUE TITLE
Add docker domains

### ISSUE THREAD

**Issue by cyqsimon** [ACL4SSR/ACL4SSR#209]
Docker was blocked en masse this month. Rules should be added for docker.com and docker.io.

**Comment by fuwuqi298** [comment]
+1

现在暂时在 clash 的 parsers 中加 
https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Docker/Docker.yaml
走的自动选择

**Comment by acl4ssr-sub** [comment]
已更新，感谢提供域名
