### ISSUE TITLE
开发者您好，我列出了一些域名清单，可以请您审核后添加进去嘛！

### ISSUE THREAD

**Issue by shwhy1998** [ACL4SSR/ACL4SSR#21]
开发者您好，经过对比我发现您的列表里少了以下这些，恳请您有时间更新下，非常感谢！！

PT域名-直连
- DOMAIN-SUFFIX,audiences.me
- DOMAIN-SUFFIX,nicept.net
- DOMAIN-SUFFIX,pttime.org
- DOMAIN-SUFFIX,hdfans.org
- DOMAIN-SUFFIX,btschool.club
- DOMAIN-SUFFIX,gainbound.net
- DOMAIN-SUFFIX,hddolby.com
- DOMAIN-SUFFIX,sharkpt.net
- DOMAIN-SUFFIX,hhanclub.top

基于OPPO一个收集个人隐私的域名-拦截
- DOMAIN,api.open.oppomobile.com

PLex域名-直连
- DOMAIN-KEYWORD,plex.tv

Playstation4/5下载域名-直连
- DOMAIN,gs2.ww.prod.dl.playstation.net.com
- DOMAIN,gst.prod.dl.playstation.net

Playstation4/5截图上传-代理
- DOMAIN,ps5.np.playstation.net

Playstation4/5首页商店相关域名-直连
- DOMAIN,image.api.playstation.com
- DOMAIN,library.rnps.dl.playstation.net
- DOMAIN,home.rnps.dl.playstation.net

**Comment by acl4ssr-sub** [comment]
PT域名-直连 我新增了。
其他的暂时不添加了，如果有需要推荐您自制一下
