### ISSUE TITLE
使用https://ip.skk.moe/查询ip地址的问题

### ISSUE THREAD

**Issue by GokouRuriia** [ACL4SSR/ACL4SSR#211]
您好，我的设备是Nokia X6，Android 9，在Shadowsocksr客户端上使用 [ACL4SSR白名单规则](https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/banAD.acl) ，在使用 [skk ip地址查询服务](https://ip.skk.moe/)  时，提示如图 ![Screenshot_2019-07-17-11-45-22.png](https://i.loli.net/2019/07/17/5d2e9db1b747d14466.png) ![Screenshot_2019-07-17-11-45-32_Mosaic_11_45_42.png](https://i.loli.net/2019/07/17/5d2e9db1c38d330930.png)
在关闭使用的自定义ACL后恢复正常，希望可以修复，谢谢

**Comment by colorsakura** [comment]
请使用不去广告的规则

**Comment by 5iux** [comment]
我改了个试试[https://5iux.github.io/ip/](https://5iux.github.io/ip/)
