### ISSUE TITLE
ACl规则里可以匹配hosts吗

### ISSUE THREAD

**Issue by lw960105** [ACL4SSR/ACL4SSR#212]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ *] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

Acl规则可以加入hosts吗

baidu.com  127.0.0.1  

比如这样的  Acl支持这种写法吗？还是其他格式？

**Comment by BROBIRD** [comment]
不能
