### ISSUE TITLE
CN 直连域名正则匹配勘误

### ISSUE THREAD

**Issue by Loyalsoldier** [ACL4SSR/ACL4SSR#213]
* 有关此issue的规则名称：
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

```
# CN域名直连
# ^.*\.cn$
(^|\.)edu\.cn$
(^|\.)gov\.cn$
(^|\.)net\.cn$
(^|\.)org\.cn$
(^|\.)中国$
(^|\.)公司$
(^|\.)网络$
```

1. 上面这段正则无法覆盖 `.cn` 的直连域名，应该加一条`\.cn$`;
2. `(^|\.)edu\.cn$` 应该写成 `\.edu\.cn$`，其余类似。

其实只要有了 `\.cn$`，`.edu.cn` `.gov.cn` `.net.cn` `.org.cn` 也就没什么必要。

**Comment by Loyalsoldier** [comment]
```
# CN域名直连
\.cn$
\.中国$
\.公司$
\.网络$
```

**Comment by leosam1995** [comment]
因为直接cn域名 错误拦截太多了

**Comment by Loyalsoldier** [comment]
在客户端开启 UDP 转发的话，会使得大部分 .cn 域名解析都会转发到远程服务器，导致本来大陆的直连域名解析出境外 IP 地址

**Comment by leosam1995** [comment]
那有时间还原回来吧

**Comment by BROBIRD** [comment]
> 
> 
> 在客户端开启 UDP 转发的话，会使得大部分 .cn 域名解析都会转发到远程服务器，导致本来大陆的直连域名解析出境外 IP 地址

开UDP转发的时候所有DNS请求都会被转发……DNS默认是基于UDP的……
