### ISSUE TITLE
user.rule过于老旧

### ISSUE THREAD

**Issue by kouhe3** [ACL4SSR/ACL4SSR#214]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
user.rule太久没更新啦，都不准啦，就不能跟随ACL文件更新吗

**Comment by okaygh** [comment]
同求,SSR PC端是被抛弃了码?

**Comment by leosam1024** [comment]
用clash吧 找个支持ssr的核心就行
