### ISSUE TITLE
pixiv.net中的reCAPTCHA验证误杀

### ISSUE THREAD

**Issue by QingKongBaiYu** [ACL4SSR/ACL4SSR#215]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
pixiv.net中使用reCAPTCHA人机验证时（修改邮箱）无法显示验证框，取消使用acl后正常显示，判断为误杀，暂时未判明其他应用或网页中是否会出现此情况。
pixiv应用中大图加载缓慢，停用后正常。

**Comment by BROBIRD** [comment]
reCaptcha根本没在阻断列表里……
