### ISSUE TITLE
请求添加FCM直连

### ISSUE THREAD

**Issue by Upapanow** [ACL4SSR/ACL4SSR#216]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
        在ssr协议下安卓的FCM推送会有一个120秒的反复中断问题，希望添加mtalk.google.com域名及其附属ip为直连模式。或者让ipv6直连，我发现这个域名有对应的v6地址有一定概率可以连上。

**Comment by BROBIRD** [comment]
客户端默认超时时间是600秒，请检查自己的服务器端配置

**Comment by Upapanow** [comment]
所有ssr机场都存在这个问题，不知道他们用的什么服务端配置，这个域名可以直连没必要走代理。
