### ISSUE TITLE
`OpenAi` 规则集里面包含 `gemini.google.com` 域名

### ISSUE THREAD

**Issue by DustinWin** [ACL4SSR/ACL4SSR#218]
**规则集所在地址：**  
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/OpenAi.list 
 
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/Ruleset/OpenAi.yaml

**预期结果：**  
不包含 `gemini.google.com` 域名

**实际结果：**  
包含 `gemini.google.com` 域名

**Comment by LD-Bao** [comment]
手机用gemini好像不行啊

**Comment by DustinWin** [comment]
> 手机用gemini好像不行啊

有单独的 [Gemini](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Gemini) 规则集

**Comment by LD-Bao** [comment]
> > 手机用gemini好像不行啊
> 
> 有单独的 [Gemini](https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/Gemini) 规则集

感谢感谢！！

**Comment by acl4ssr-sub** [comment]
fixed
