### ISSUE TITLE
使用banAD.acl后，QQ飞车手游的自定义音乐无法选定播放。

### ISSUE THREAD

**Issue by ywj601** [ACL4SSR/ACL4SSR#218]
在ShadowsocksR安卓端里使用banAD.acl文件后，
QQ飞车手游里的的自定义音乐列表无法选定播放，音乐名呈现灰色名称状态，可以说这播放器好像走了代理路线，因为国内播放器在外国没法使用。
并不是直连线，把ssr关闭后重启游戏，自定义音乐才能正常播放。
希望能有人找到把这播放器走的线加入白名单不让其走代理路线吧。
![Screenshot_2019-08-22-19-33-36-602_com tencent tm](https://user-images.githubusercontent.com/44678185/63511528-05de8e00-c514-11e9-8e12-71037dee8ff1.png)

**Comment by MephistoLynn** [comment]
你有没有发现，在微信里打开图片都会受影响。根本就转不出来

**Comment by ywj601** [comment]
> 你有没有发现，在微信里打开图片都会受影响。根本就转不出来

这个我不清楚，我想图片加载也走代理路线啰？

**Comment by MephistoLynn** [comment]
我现在发现许多腾讯系的产品，在他的资源请求中常常会和SS链接下的网络发生冲突。同时使用的SS和腾讯系产品很多资源就是没法加载，或者加载很慢，我合理的怀疑下腾讯系产品会自动检测SS链接，并进行处理，即便你选择的是绕过国内IP。一个还算有效的方案是在ACL代理模式下，同时开启分应用代理。

**Comment by ywj601** [comment]
> 我现在发现许多腾讯系的产品，在他的资源请求中常常会和SS链接下的网络发生冲突。同时使用的SS和腾讯系产品很多资源就是没法加载，或者加载很慢，我合理的怀疑下腾讯系产品会自动检测SS链接，并进行处理，即便你选择的是绕过国内IP。一个还算有效的方案是在ACL代理模式下，同时开启分应用代理。

至于检测ss，腾讯的TP系统是有这个检测的，因为有用ss的外挂。不过TP系统大多用于游戏，应用软件我就不清楚了。
我试了下“分应用代理”，开“分应用代理”+绕行模式，然后把QQ飞车选中了，开游戏是没有走代理了。还真的感谢你的建议（笑）。

**Comment by LouisKooAndroid** [comment]
我也发现了，不管用什么ACL文件还是绕过大陆和局域网模式，微信朋友圈图片都刷不了，都在转圈。

**Comment by leosam1995** [comment]
核心原因是SSR的选择的dns解析问题，然后另外微信是全球都有服务器，所以服务器的dns把他解析到国外去了。所以图片加载缓慢。
尽量分应用代理吧。
打开分应用代理，默认关闭绕行模式，然后选择你需要走代理的那些APP即可。按此方法设置后，微信票圈图片秒加载。亲测有效。

**Comment by BenzLeung** [comment]
淘宝和闲鱼也是这样，图片加载会变慢。但是给它们开了分应用代理就不能用acl屏蔽广告了。真希望能有两全其美的方案……
话说没有匹配到代理规则的url也是走“DNS”而没有走“China DNS”的吗？
