### ISSUE TITLE
10.x.x.x是局域网域名，不应该走代理

### ISSUE THREAD

**Issue by reoLantern** [ACL4SSR/ACL4SSR#219]
如题，我发现规则中应该是让10.x.x.x的地址走了代理（导致局域网连不上）

**Comment by fxzxmicah** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/e5cd7cafa388915a2fae5c033c3e33714749a217/Clash/LocalAreaNetwork.list#L14
已有规则。

**Comment by reoLantern** [comment]
我看log发现，按照[ACL4SSR_Online_Full_MultiMode.ini](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini)，访问10.21.x.x时，匹配了“漏网之鱼”，这个是不是不正确

**Comment by reoLantern** [comment]
似乎明白了，我在访问局域网内的特定域名 xxx.com，它在我本地被解析成 10.x.x.x，但是走代理是按照 xxx.com 匹配到了漏网之鱼......请问这个有什么解决办法吗

**Comment by fxzxmicah** [comment]
fork仓库，把你用的域名添加到直连。
如果其它人也可能会用到这个域名，那可以提交PR。

**Comment by reoLantern** [comment]
感谢😊
