### ISSUE TITLE
大佬，无法屏蔽YouTube广告

### ISSUE THREAD

**Issue by vcan** [ACL4SSR/ACL4SSR#220]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)

- [ * ] gfwlist-banAD.acl

* 您提交此issue的目的是：
- [*  ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
MIUI 10可以过滤头条等开屏广告、爱奇艺等视频内广告，无法过滤YouTube广告，希望增加相关的规则。

**Comment by leosam1995** [comment]
屏蔽了的话，误杀太严重
