### ISSUE TITLE
使用ACL后Proxifier失效了

### ISSUE THREAD

**Issue by xieqing0428** [ACL4SSR/ACL4SSR#221]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
mac客户端使用ACL模式后Proxifier定向转发就失效了, 谷歌搜索好像没有相关回答, 想接个地方问问有没有相同情况的, 打扰了

**Comment by BROBIRD** [comment]
无关问题，出门左转MAC客户端repo下提问
