### ISSUE TITLE
Proxy Back to China列表问题反馈

### ISSUE THREAD

**Issue by wuwentao** [ACL4SSR/ACL4SSR#222]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [x] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
1. 使用的是Mac版ShadowsocksX-NG Version 1.4.4-R8 (1)
2. 使用的的Proxy Back to China 模式，IP是海外的，需要访问国内网站走proxy，速度会快点
3. Server端是SSR
4. 发现ACL里面有很多网站好像不生效

问题1： 访问携程www.ctrip.com，好像域名解析为海外IP了，应该不在list里面，但是qunar.com好像在里面
问题2: 大众点评dianping.com在列表中，但是美团好像不在：meituan.com
问题3： 类似的应该还有不少，这样的域名如何手工自己添加？或更新到ACl list里
问题4： 例如访问www.ip.cn 按道理这个应该是走proxy_list的cn域名，但是好像DNS解析的是非国内IP，就跳过了，这个是属于SSR的问题？还是proxy_list规则的问题？

非ACL list项目相关的问题：
在ShadowsocksX-NG软件里，Proxy Back to China模式下，如何手工设置一个网站走proxy，一个不走proxy？

**Comment by wuwentao** [comment]
附：另外一个github上有人手工处理的办法，这样可以解决问题：
https://github.com/yzyjim/Shadowsocks-Back-China-PAC

**Comment by leosam1024** [comment]
2者解析规则不一样。国内软件 还是尽可能的分应用代理跳过吧
