### ISSUE TITLE
网易域名在 ACL 中正则匹配书写错误

### ISSUE THREAD

**Issue by Loyalsoldier** [ACL4SSR/ACL4SSR#224]
* 有关此issue的规则名称：
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

网易域名正则匹配错误 `(^|\.)net$ease\.com$`

**Comment by leosam1995** [comment]
已经修复

**Comment by Loyalsoldier** [comment]
其实是重复了两个网易域名，第一个写错了，第二个写对了。现在修复后，有两个对的

**Comment by leosam1995** [comment]
好了
