### ISSUE TITLE
user rule中没有google.com和其它google系域名

### ISSUE THREAD

**Issue by MichaelHu55** [ACL4SSR/ACL4SSR#23]
google.com
google.com.hk
google其它国家的国家的域名都没有。

只有一些google的ad在reject里，这样google搜索都打不开啊

**Comment by BROBIRD** [comment]
用https://www.google.com/ncr 其实就行了，之后会加上的

**Comment by BROBIRD** [comment]
C#客户端推荐使用PAC

**Comment by BROBIRD** [comment]
卧槽……我现在才发现我当时做的时候忘了把单独处理的Google放进去了……

**Comment by MichaelHu55** [comment]
是的，都没放，所有google单独站点。还有，为会c#客户端推荐用pac咯，我感觉user rule体验很好啊

**Comment by BROBIRD** [comment]
Fixed.

**Comment by snailwind** [comment]
请问 这个user rule是怎样用的？没看明白是如何用 复制粘贴到PAC里？

**Comment by BROBIRD** [comment]
@snailwind 
1、无关问题请另开issue
2、善用搜索引擎 https://github.com/ssrbackup/shadowsocks-rss/wiki/C%23-Proxy-Rule
