### ISSUE TITLE
Facebook Messenger 部分功能无法正常使用

### ISSUE THREAD

**Issue by SteveHawk** [ACL4SSR/ACL4SSR#230]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

在使用 `banAD.acl` 的时候，[Facebook Messenger](https://messenger.com) 的语音以及某些动图无法正常加载。使用全局代理或者使用 `gfwlist-banAD.acl` 的时候则能够正常加载。查看流量记录以后基本确定问题出在 `cdn.fbsbx.com` 这个域名上。

有几个地方我觉得很奇怪：

1. Messenger app 中无法加载的语音/动图，在网页中能够正常加载。网页和 app 访问的都是 `cdn.fbsbx.com` 这个接口，网页能正常走代理，app 就嗝屁，不知道为什么。

2. `gfwlist-banAD.acl` 中有对 `*.fbsbx.com` 这个域名的代理记录，然后就可以正常代理；`banAD.acl` 中并没有这个域名，但是默认应该走代理却没有正常被代理，非常奇怪。

希望能帮忙解答/解决下这个问题，十分感谢。

**Comment by leosam1995** [comment]
已添加
