### ISSUE TITLE
请问有否计划屏蔽 EasyList 和 EasyListChina 里的广告域名？

### ISSUE THREAD

**Issue by Loyalsoldier** [ACL4SSR/ACL4SSR#231]
* 有关此issue的规则名称：
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

---
* 您要反馈的问题：

请问有计划将 [EasyList](https://easylist.to/easylist/easylist.txt) 和 [EasyListChina](https://easylist-downloads.adblockplus.org/easylistchina.txt) 里的广告域名加入到与广告相关的 ACL 文件中吗？

**Comment by leosam1995** [comment]
我代码遍历了一波 ，都是菠菜 色情啥的 不好加 
我只加广告联盟的或者大厂广告的 
这种小网站，太多了 换域名也频繁，不好维护

**Comment by leosam1024** [comment]
添加了
