### ISSUE TITLE
banAD.acl对QQ/微信电话的影响

### ISSUE THREAD

**Issue by ausers** [ACL4SSR/ACL4SSR#232]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
以前此规则可以让QQ/微信电话不受代理影响，后来再次出现连接中无法接通的情况，希望能修复

**Comment by leosam1024** [comment]
路由选全局，打开分应用代理，默认关闭绕行模式，然后选择你需要走代理的那些APP即可。按此方法设置后，微信票圈图片秒加载。亲测有效。
这个是SSR的网络模式导致的，非ACL的问题。
微信所有的域名都已经是直连的。我今天抓了一下包，应该是这个问题
