### ISSUE TITLE
被墙域名申请：app.cloudcone.com

### ISSUE THREAD

**Issue by szkzn** [ACL4SSR/ACL4SSR#233]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)

备注：该域名已提交给GFWlist，暂时未得到回复
同时建议直接把主域名及其所有子域名添加至GFW列表，因为该IDC的IP段已被玩坏，成段成片的被墙，现在他们家的官网登陆页面的这个子域名已经在2个星期前阵亡，只有代理才能访问

---
* 您要反馈的问题：
添加被墙域名申请
cloudcone.com主域名及其子域名（建议，未来扩展延伸，预防）
app.cloudcone.com （当前实际情况）

测试环境：移动/电信/联通 4G，电信/联通宽带，都无法访问，已持续2个星期+

**Comment by szkzn** [comment]
即如下：
||cloudcone.com^

**Comment by leosam1995** [comment]
ok 下次更新添加
