### ISSUE TITLE
白名单模式algocasts.io域名请求直连

### ISSUE THREAD

**Issue by xieqing0428** [ACL4SSR/ACL4SSR#234]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
algocasts.io是算法视频教学，也没有广告但是被有些规则拦截了，希望开个直连，谢谢

**Comment by leosam1995** [comment]
已添加
