### ISSUE TITLE
从直连列表删除动漫花园

### ISSUE THREAD

**Issue by 4512369781** [ACL4SSR/ACL4SSR#235]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 您要反馈的问题：
动漫花园不能直接访问，需要使用代理才行。
麻烦在上面这两个规则的直连列表里删除share.dmhy.org相关条目。

**Comment by leosam1995** [comment]
已经删除

**Comment by 4512369781** [comment]
> 已经删除

谢谢(^^)
