### ISSUE TITLE
google FCM 网址问题

### ISSUE THREAD

**Issue by Forty-nine** [ACL4SSR/ACL4SSR#237]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
mtalk.google.com 在大陆可以直接连接，请求把这个域名作为特例直连

**Comment by Forty-nine** [comment]
`tcping mtalk.google.com 5228
Probing 2404:6800:4008:c05::bc:5228/tcp - Port is open - time=449.320ms
Probing 2404:6800:4008:c05::bc:5228/tcp - Port is open - time=456.952ms
Probing 2404:6800:4008:c05::bc:5228/tcp - Port is open - time=445.543ms
Probing 2404:6800:4008:c05::bc:5228/tcp - Port is open - time=446.505ms

Ping statistics for 2404:6800:4008:c05::bc:5228
     4 probes sent.
     4 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 445.543ms, Maximum = 456.952ms, Average = 449.580ms`

**Comment by BROBIRD** [comment]
你用ipv4测试看下

**Comment by Forty-nine** [comment]
nslookup mtalk.google.com
服务器:  WR1200JS.lan
Address:  2408:8234:3911:648e:d65f:25ff:fefe:1a10
非权威应答:
名称:    mobile-gtalk.l.google.com
Addresses:  2404:6800:4008:c02::bc
          108.177.97.188
Aliases:  mtalk.google.com

tcping 108.177.97.188 5228
Probing 108.177.97.188:5228/tcp - Port is open - time=72.081ms
Probing 108.177.97.188:5228/tcp - Port is open - time=67.064ms
Probing 108.177.97.188:5228/tcp - Port is open - time=71.680ms
Probing 108.177.97.188:5228/tcp - Port is open - time=67.565ms

Ping statistics for 108.177.97.188:5228
     4 probes sent.
     4 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 67.064ms, Maximum = 72.081ms, Average = 69.598ms

**Comment by BROBIRD** [comment]
初步测试了一下，各地可用性不太一致，等周末我想想有没有比较合适的解决办法，你先提供一下网络环境吧（地区+运营商（最好附一下ASN））

**Comment by Forty-nine** [comment]
吉林联通，as4837？

**Comment by shikkoku** [comment]
广东电信 AS4134
`nslookup mtalk.google.com
Server:  console.gl-inet.com
Address:  192.168.8.1

Non-authoritative answer:
Name:    mobile-gtalk.l.google.com
Addresses:  2404:6800:4008:c07::bc
          64.233.188.188
Aliases:  mtalk.google.com`

`PsPing v2.10 - PsPing - ping, latency, bandwidth measurement utility
Copyright (C) 2012-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

TCP connect to 64.233.188.188:5228:
5 iterations (warmup 1) ping test:
Connecting to 64.233.188.188:5228 (warmup): from 192.168.8.230:64673: 338.69ms
Connecting to 64.233.188.188:5228: from 192.168.8.230:64674: 21.50ms
Connecting to 64.233.188.188:5228: from 192.168.8.230:64675: 20.88ms
Connecting to 64.233.188.188:5228: from 192.168.8.230:64676: 30.49ms
Connecting to 64.233.188.188:5228: from 192.168.8.230:64677: 29.69ms`

**Comment by BROBIRD** [comment]
Solved via f868914

**Comment by shikkoku** [comment]
> Solved via [f868914](https://github.com/ACL4SSR/ACL4SSR/commit/f868914facb109862882d0aac6cb46238c9012da)

在https://acl4ssr.netlify.com/转换成clash的规则后没有体现出这条更新的规则。

**Comment by shikkoku** [comment]
https://github.com/ACL4SSR/ACL4SSR/commit/9bb0d50f0f3c5a0330ce8329c8fbf43e34658bfd

(^|\.)alt[0-8]-mtalk\.google\.com$
(^|\.)mtalk\.google\.com$

虽然banAD.acl规则里有这两条，但是mtalk.google.com还是走代理了。会出现120秒断开。

**Comment by BROBIRD** [comment]
> 
> 
> [9bb0d50](https://github.com/ACL4SSR/ACL4SSR/commit/9bb0d50f0f3c5a0330ce8329c8fbf43e34658bfd)
> 
> (^|.)alt[0-8]-mtalk.google.com$
> (^|.)mtalk.google.com$
> 
> 虽然banAD.acl规则里有这两条，但是mtalk.google.com还是走代理了。fcm会出现连接后120秒断开。
> 
> 客户端是https://github.com/shadowsocksRb/shadowsocksRb-android

我这里使用正常，稳定连接18分钟以上

**Comment by shikkoku** [comment]
> > [9bb0d50](https://github.com/ACL4SSR/ACL4SSR/commit/9bb0d50f0f3c5a0330ce8329c8fbf43e34658bfd)
> > (^|.)alt[0-8]-mtalk.google.com$
> > (^|.)mtalk.google.com$
> > 虽然banAD.acl规则里有这两条，但是mtalk.google.com还是走代理了。fcm会出现连接后120秒断开。
> > 客户端是https://github.com/shadowsocksRb/shadowsocksRb-android
> 
> 我这里使用正常，稳定连接18分钟以上

请问使用的客户端是哪个，是否方便提供测试？

**Comment by BROBIRD** [comment]
我用的是gfwlist-banAD，你试试看这个？

**Comment by shikkoku** [comment]
> 我用的是gfwlist-banAD，你试试看这个？

![Screenshot_20200414_164433_com google android gms](https://user-images.githubusercontent.com/4697177/79204549-502fc900-7e6f-11ea-83d2-be1c24a37418.jpg)

gfwlist-banAD.acl 一样会这样。 刚刚点错Reference in new issue了……

**Comment by BROBIRD** [comment]
我用的是https://github.com/BROBIRD/shadowsocksr-android/releases/tag/v5.0.5R
自己在rb基础上修改的，可能存在问题，你可以试试

**Comment by shikkoku** [comment]
> 我用的是https://github.com/BROBIRD/shadowsocksr-android/releases/tag/v5.0.5R
> 自己在rb基础上修改的，可能存在问题，你可以试试

![Screenshot_20200414_170840_com google android gms](https://user-images.githubusercontent.com/4697177/79207198-f9c48980-7e72-11ea-9447-17a60010a374.jpg)

依然会121秒~119秒自动断开重连。。

![Screenshot_20200414_170948_io github shadowsocksrb mod](https://user-images.githubusercontent.com/4697177/79207253-0c3ec300-7e73-11ea-8e2d-86a187387570.jpg)

**Comment by BROBIRD** [comment]
这个感觉更像是你网络的问题

**Comment by shikkoku** [comment]
> 这个感觉更像是你网络的问题

![Screenshot_20200414_175616_com google android gms](https://user-images.githubusercontent.com/4697177/79211831-4f9c3000-7e79-11ea-9fab-a4cda02b47bf.jpg)

这是cfa同一节点的测试结果，两次都是我手动断开的。可以维持长连接。

**Comment by shikkoku** [comment]
另外问下，大佬你这个改版的规则是会在线更新还是内置固化的呢？

**Comment by shikkoku** [comment]
> 这个感觉更像是你网络的问题

尝试换了个节点，目前保持了20分钟连接了。可能真的是网络问题吧。

**Comment by BROBIRD** [comment]
@shikkoku 应该是每次启动更新一次，但是我也没确认:joy: 发现有问题的话给我反馈一下吧
