### ISSUE TITLE
没有屏蔽广告

### ISSUE THREAD

**Issue by JZZ99** [ACL4SSR/ACL4SSR#240]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
大佬 我想问一下为什么我使用了规则之后广告并没有被屏蔽呢？

**Comment by BROBIRD** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by JZZ99** [comment]
....就是刚开始几次打开应用可以屏蔽启动广告 然后过了一会儿重新打开应用之后就又出现启动广告了 而且软件内的广告也没有屏蔽（我用的知乎），分应用代理也没有打开

**Comment by BROBIRD** [comment]
本项目从来没有声称可以屏蔽知乎的启动广告和应用内广告

**Comment by JZZ99** [comment]
好吧 是我想当然了
