### ISSUE TITLE
微信朋友圈图片无法加载

### ISSUE THREAD

**Issue by LittleDragonSun** [ACL4SSR/ACL4SSR#241]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“”以勾选！！)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：打开SSR客户端代理后使用上述规则，微信朋友圈的的信息几乎加载不出来，观察到图片是加载不出来的只有占位符。希望把微信朋友圈相关域名设置为直连。谢谢。

**Comment by leosam1995** [comment]
路由选全局，打开分应用代理，默认关闭绕行模式，然后选择你需要走代理的那些APP即可。按此方法设置后，微信票圈图片秒加载。亲测有效。
这个是SSR的网络模式导致的，非ACL的问题。
微信所有的域名都已经是直连的。我今天抓了一下包，应该是这个问题

**Comment by LittleDragonSun** [comment]
感谢你的测试、解答及提供解决方法。
