### ISSUE TITLE
Clash规则碎片能否加入安卓应用广告？

### ISSUE THREAD

**Issue by YipSzeho** [ACL4SSR/ACL4SSR#242]
> * 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
> 
> * [ ]  backcn-banAD.acl
> * [ ]  banAD.acl
> * [ ]  fullgfwlist.acl
> * [ ]  gfwlist-banAD.acl
> * [ ]  gfwlist-user.rule
> * [ ]  nobanAD.acl
> * [ ]  onlybanAD.acl
> 
> * 您提交此issue的目的是：
> 
> * [ ]  报告错误
> * [ ]  提交广告域名
> * [ ]  提交代理/直连域名
> * [x]  其他问题
> 
> * 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
> 
> * 您要反馈的问题：
>   Clash规则碎片可以加上安卓应用广告列表吗

**Comment by leosam1024** [comment]
clash 一开始是给桌面系统做的
acl的那个安卓广告全部用的正则，好多条合并在一起的，
要想拆成clash的 很难拆。主要没那么多时间，
如果你有时间 可以拆一下 push上来就行

**Comment by leosam1024** [comment]
已经添加了
  添加常用网址的广告拦截,效果很牛逼，副作用也有
  rules/ACL4SSR/Clash/BanProgramAD.list
  也有轻度的，只拦截了广告联盟的，一定影响都没有
  rules/ACL4SSR/Clash/BanAD.list
