### ISSUE TITLE
能否加入Clash安卓广告规则

### ISSUE THREAD

**Issue by sceraser** [ACL4SSR/ACL4SSR#243]
Clash安卓版已经推出，能否将SSR规则的应用广告规则同步回来

**Comment by leosam1024** [comment]
已经加了啊。看telegram的公告啊

**Comment by pekinghot** [comment]
> 已经加了啊。看telegram的公告啊 添加常用网址的广告拦截,效果很牛逼，副作用也有 rules/ACL4SSR/Clash/BanProgramAD.list 也有轻度的，只拦截了广告联盟的，一定影响都没有 rules/ACL4SSR/Clash/BanAD.list

爹，全网都找不到安卓客户端怎么添加规则的教程，有没指引发一下看看，谢谢啦
