### ISSUE TITLE
不知能否屏蔽微信公众号文章里的广告？

### ISSUE THREAD

**Issue by jiahe224** [ACL4SSR/ACL4SSR#244]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
Quantumult支持脚本，可以去除公众号广告，但安卓上貌似没有支持脚本的代理App，不知用此规则配合 ss 能否达到去除公众号广告的效果？

**Comment by leosam1024** [comment]
公众号的文章不是单独的广告域名，屏蔽不了
