### ISSUE TITLE
Clash的ChinaIp.list问题

### ISSUE THREAD

**Issue by Forty-nine** [ACL4SSR/ACL4SSR#245]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
bilibili解析的ip是 120.92.78.97，然而 ChinaIp 里 没有 120.92.78.0,导致 匹配 错误

**Comment by Forty-nine** [comment]
理论上可以，但我 CFW 没匹配 啊

**Comment by leosam1024** [comment]
IP-CIDR,120.92.0.0/17,no-resolve 已经包含
120.92.0.0-120.92.127.255	网络地址：120.92.0.0	广播地址：120.92.127.255	可分配地址范围：120.92.0.1-120.92.127.254	可分配主机数：32766

所以没问题

**Comment by Forty-nine** [comment]
明明我写了 DIRECT，但是 他走 代理 了啊

**Comment by Forty-nine** [comment]
我是 傻子，end

**Comment by BROBIRD** [comment]
> 
> 
> 我是 傻子，end

有点好奇发生了什么……
