### ISSUE TITLE
BanAD规则错误屏蔽了imgur图库的域名i.imgur.com

### ISSUE THREAD

**Issue by Sherman-Liu** [ACL4SSR/ACL4SSR#247]
![](https://i.imgur.com/7KOiHIX.png)

**Comment by leosam1024** [comment]
没有啊 https://imgur.com 我没加入屏蔽里啊

**Comment by Sherman-Liu** [comment]
太奇怪了，只要使用BanAD规则，就无法访问i.imgur.com，而nobanAD就没事

**Comment by BROBIRD** [comment]
如果是规则阻断的话应该是`CONNECTION_RESET`

**Comment by naloder** [comment]
感觉是楼主网络问题。。以及用chrome试试?

**Comment by BROBIRD** [comment]
@naloder 我觉得可以建议他先用https访问试试
