### ISSUE TITLE
请求clash增加对部分微软服务的加速和代理

### ISSUE THREAD

**Issue by Marukon** [ACL4SSR/ACL4SSR#248]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

DOMAIN-SUFFIX,live.com
DOMAIN-SUFFIX,live.net
DOMAIN-SUFFIX,office.com
DOMAIN-SUFFIX,office.net
DOMAIN-SUFFIX,windows.com
DOMAIN-SUFFIX,windows.net
DOMAIN-SUFFIX,sharepoint.com
DOMAIN-SUFFIX,office365.com
DOMAIN-SUFFIX,officeppe.net
DOMAIN-SUFFIX,skype.com
DOMAIN-SUFFIX,onedrive.com
DOMAIN-SUFFIX,msocsp.com
DOMAIN-SUFFIX,msauthimages.net
DOMAIN-SUFFIX,msauth.net
DOMAIN-SUFFIX,microsoftonline.com
DOMAIN-SUFFIX,msn.com
DOMAIN-SUFFIX,onenote.com
DOMAIN-SUFFIX,onenote.net
DOMAIN-SUFFIX,1drv.com

尤其是加速Onedrive的速度，谢谢

**Comment by Marukon** [comment]
修正一下，去掉部分域名

DOMAIN-SUFFIX,live.com
DOMAIN-SUFFIX,live.net
DOMAIN-SUFFIX,office.com
DOMAIN-SUFFIX,office.net
DOMAIN-SUFFIX,sharepoint.com
DOMAIN-SUFFIX,office365.com
DOMAIN-SUFFIX,officeppe.net
DOMAIN-SUFFIX,skype.com
DOMAIN-SUFFIX,onedrive.com
DOMAIN-SUFFIX,msocsp.com
DOMAIN-SUFFIX,msauthimages.net
DOMAIN-SUFFIX,msauth.net
DOMAIN-SUFFIX,microsoftonline.com
DOMAIN-SUFFIX,msn.com
DOMAIN-SUFFIX,onenote.com
DOMAIN-SUFFIX,onenote.net
DOMAIN-SUFFIX,1drv.com

**Comment by leosam1024** [comment]
微软现在在中国已经有很多cdn了。请求地址一般都是国内ip。
但是如果加入代理的话，可能使本来直连很快的，变的很慢。
所以一般不会加入的。

微软的域名考虑的是bing加入了代理。
其余的暂时不会加入。这个影响过大不敢弄。抱歉了

我刚刚也观察了一些其他大佬的规则，也没添加代理啊。

**Comment by Marukon** [comment]
好的，谢谢您的回复。我这主要是直连onedrive的速度太慢了才考虑加速的。

**Comment by leosam1024** [comment]
嗯 这个主要是考虑大多数用户吧 。我晚上考虑一下是否把onedirve的域名去掉，让你软件自行选择代理方式吧

**Comment by Marukon** [comment]
> 嗯 这个主要是考虑大多数用户吧 。我晚上考虑一下是否把onedirve的域名去掉，让你软件自行选择代理方式吧

谢谢大佬对此事的关注。大佬我上面提供的一些域名基本都是没有国内CDN的，基本不包括windows uodate之类的服务，主要针对微软云之类的服务，所以是加速微软部分域名，不是加速微软全部域名。很抱歉我的这个issue的标题有误，请大佬重新考虑，谢谢。

**Comment by Marukon** [comment]
感谢大佬的投票和更新，而且提供了如此之全面的微软服务域名。

**Comment by Marukon** [comment]
感谢大佬的投票和更新，而且提供了如此之全面的微软服务域名。

**Comment by oozj** [comment]
微软登录 要加
