### ISSUE TITLE
请求clash绕过部分文献下载网站

### ISSUE THREAD

**Issue by Marukon** [ACL4SSR/ACL4SSR#249]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

请求绕过这些网站，因为这些网站的服务必须使用国内IP才能使用。

- DOMAIN-SUFFIX,webofknowledge.com,DIRECT
- DOMAIN-SUFFIX,sciencedirect.com,DIRECT

**Comment by leosam1024** [comment]
可以先这样
cfw-bypass:
  - '*webofknowledge.com'
  - '*sciencedirect.com'

**Comment by Marukon** [comment]
> 可以先这样
> cfw-bypass:
> 
> * '*webofknowledge.com'
> * '*sciencedirect.com'

你好，我已经手动添加规则了，希望本项目下次更新时候能把这些网址囊括进去，谢谢。

**Comment by leosam1024** [comment]
这个你加到主clash的系统代理绕过列表中吧。这种域名一般不太会添加。
因为他不是常用大陆域名。个人用的话还是特殊处理一下吧

**Comment by Marukon** [comment]
> 这个你加到主clash的系统代理绕过列表中吧。这种域名一般不太会添加。
> 因为他不是常用大陆域名。个人用的话还是特殊处理一下吧

好的，谢谢。
