### ISSUE TITLE
请添加static.intentarget.com广告屏蔽

### ISSUE THREAD

**Issue by MichaelHu55** [ACL4SSR/ACL4SSR#25]
来源 http://m.news.sina.com.tw/article/20170801/23280392.html
中部广告

**Comment by BROBIRD** [comment]
您好，我这里并没有发现含有这一域名，中部也未发现广告能否提供截图和您获得的网页源码？谢谢！

**Comment by MichaelHu55** [comment]
图片https://goo.gl/photos/ewCdkCHFxWay5AbP7

**Comment by BROBIRD** [comment]
暂时没办法定位……我想想办法

**Comment by leosam1995** [comment]
popin.cc已经添加
