### ISSUE TITLE
请求加入直连名单

### ISSUE THREAD

**Issue by LeMiao** [ACL4SSR/ACL4SSR#250]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [x] 其他问题

* 您要反馈的问题：
1. 请求将 "sukiu.net" 主域及其子域加入直连名单。
2. 现在微信朋友圈图片下载会通过代理，QQ图片上传（疑似）通过代理，望检查。
- 关于第一点，我还有一个希望加入直连名单的域名，但不想让它过于公开，所以我把它发到了 BROBIRD 的 Gmail 邮箱，望见谅。

**Comment by leosam1024** [comment]
sukiu.net 指向的host 是 119.167.170.232 这个已经是大陆ip，没必要添加直连

微信代理的那个已经回答过了 [241](https://github.com/ACL4SSR/ACL4SSR/issues/241#issuecomment-568254237)，这个是SSR的一些问题，不是acl能搞定的。你可以用clash

**Comment by LeMiao** [comment]
> sukiu.net 指向的host 是 119.167.170.232 这个已经是大陆ip，没必要添加直连
> 
> 微信代理的那个已经回答过了 [241](https://github.com/ACL4SSR/ACL4SSR/issues/241#issuecomment-568254237)，这个是SSR的一些问题，不是acl能搞定的。你可以用clash

感谢回复。
sukiu.net 现在是处于被代理列表的。您提到的是一些二级域的国内CDN节点，但有一些子域不经过CDN，同时它们屏蔽境外IP访问。所以还是要麻烦您添加一下直连列表，以在使用代理软件的时候能正常访问它们。

**Comment by leosam1024** [comment]
我这边并没一点被代理的痕迹啊。不管是子域名还是主域名，都是直连的
很抱歉不能把你加进去，你自己操作的话 可以加入你自己的额外配置里。
不能加进去的原因有4点。
1. 你这个域名是阿里巴巴注册的，肯定是国内域名。
2. 我们这边看你的域名 不管是主域名还是子域名都是。
3. 我用ssr链接 也是直连的，不管是wifi还是4G
4. 你这个域名不是属于大陆常用域名，没必要加入，让dns自动选择吧
