### ISSUE TITLE
提交直连域名

### ISSUE THREAD

**Issue by ausers** [ACL4SSR/ACL4SSR#251]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

斐讯路由后台域名“p.to”需要直连

**Comment by leosam1024** [comment]
使用ip 192.。。。能访问吗？

**Comment by ausers** [comment]
> 使用ip 192.。。。能访问吗？

可以倒是可以，但p.to记熟了。。。而且输入更快点。。。

**Comment by leosam1024** [comment]
你先加个192的书签呗，到时候我看看能不能加上

**Comment by ausers** [comment]
> 你先加个192的书签呗，到时候我看看能不能加上

嗯，谢谢
（发现这域名还指向一个似乎是德国代购的。。。反正也是能直连的。。）

**Comment by leosam1024** [comment]
已经添加
