### ISSUE TITLE
以下育碧域名在Clash规则建议设为直连

### ISSUE THREAD

**Issue by JinjerTK** [ACL4SSR/ACL4SSR#253]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

public-ubiservices.ubi.com
dmx.upc.ubisoft.com
另外，包含DOMAIN-SUFFIX：ubi.com
DOMAIN-KEYWORD：ubisoft，ubiservice,ubistatic
本人小白，描述得可能很模糊，还见谅

**Comment by leosam1024** [comment]
这些都是美国服务器啊，直连不好吧，容易有些地区速度过慢 容易失败。

如果只是自用的话 可以在clash基础配置文件里添加这个
```
# 系统代理跳过列表 起作用的
cfw-bypass:
  # 育碧直连列表
  - "ubi.com"
  - "*.ubi.com"
  - "*ubisoft*"
  - "*ubiservice*"
  - "*ubistatic*"
```

**Comment by JinjerTK** [comment]
主要是经过来回测试了几次，发现用代理登录和不用代理登录uplay，每次切换都会要求重新输入账号密码，这点上比较麻烦，而且store.ubi.com这项域名如果被代理，那么uplay应用里的商城货币单位会变成代理地区货币如香港则是＄，且国内活动概率在uplay客户端中不显示，当然这些只是我个人的一些小小意见哈

**Comment by leosam1024** [comment]
我主要不玩，让他们自己选择吧 ，适合自己的就行

**Comment by JinjerTK** [comment]
好的，本来也只是个建议，另外请教下大佬到底哪个是基础配置文件，我用的是频道发布的v0.8.9，我修改了D:\...\Clash\resources\static\files里的config.yml，将上面代码直接复制粘贴在最后并保存了，也提示修改成功，但在connections看相关域名还是判为漏网之鱼走了代理

**Comment by leosam1024** [comment]
应该有重复项，你看看，是新增 不是替换
