### ISSUE TITLE
提交代理域名

### ISSUE THREAD

**Issue by JinjerTK** [ACL4SSR/ACL4SSR#255]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
建议将services.googleapis.cn加入代理，

国行手机预置框架的商店启动时会向services.googleapis.cn获取数据，而正常情况下(国际版)是向services.googleapis.com获取的，会导致Play商店出现"DF-DFERH-01"报错。

**Comment by BROBIRD** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/968c08a80a6dc27b57f514c9f7d93f9fa57f3e2b/banAD.acl#L8428
