### ISSUE TITLE
谷歌搜出来的 AMP 网站访问 404

### ISSUE THREAD

**Issue by lzfxxx** [ACL4SSR/ACL4SSR#256]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
谷歌搜出来的 AMP 网站访问 404
测试链接 https://amp-dev.cdn.ampproject.org/wp/s/amp.dev/about/websites/?usqp=mq331AQOKAGYAe69xdCymPSwiwE%3D
![Screenshot_20200216-134625](https://user-images.githubusercontent.com/12368329/74599786-c2c83680-50c2-11ea-9a38-8502e20c2747.jpg)

**Comment by leosam1024** [comment]
这个404，也不是acl的锅啊，纯属是那个网站404了 。。。。

**Comment by lzfxxx** [comment]
> 这个404，也不是acl的锅啊，纯属是那个网站404了 。。。。

不是的，所有的amp网站都404了
https://amp-reddit-com.cdn.ampproject.org/wp/s/amp.reddit.com/r/webdev/comments/ctu2gw/google_amp_how_is_this_okay_in_2019/?usqp=mq331AQOKAGYAe_V2JqKssLH6gE%3D

https://www-xda--developers-com.cdn.ampproject.org/wp/s/www.xda-developers.com/bypass-amp-links-deampify/amp/?usqp=mq331AQNKAGYAc2WmfbV_cu6Ng%3D%3D

https://www.google.com/amp/s/www.pinterest.cl/amp/pin/439452876114504685/

**Comment by leosam1024** [comment]
那也跟我这个acl没关系啊，acl只能关注域名，管不住url啊
acl只能决定这个网站是否能代理，决定不了这个网站是否有资源访问不了啊

**Comment by lzfxxx** [comment]
@leosam1024 
和域名还是有点关系的, 参考 https://www.v2ex.com/t/332817

**Comment by leosam1024** [comment]
我改改代理试试

**Comment by lzfxxx** [comment]
@leosam1024 谢谢帮忙, 我的安卓客户端没法添加自定义规则, 只能靠acl这边试试了

**Comment by leosam1024** [comment]
好了，给你加上了，自己过2分钟，更新一下acl，或者你用gwf那个更齐全的acl

**Comment by lzfxxx** [comment]
@leosam1024 可以了, 谢谢
