### ISSUE TITLE
clash规则BanProgramAD拦截墨迹天气

### ISSUE THREAD

**Issue by KhaosChow** [ACL4SSR/ACL4SSR#258]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
BanProgramAD.list中的规则DOMAIN-SUFFIX,cdn.moji.com将墨迹天气的正常页面拦截了。
![Screenshot_20200218-112030](https://user-images.githubusercontent.com/7082030/74701345-663f5580-5241-11ea-8650-4d3e762cd1a7.jpg)
![Screenshot_20200218-112104__01](https://user-images.githubusercontent.com/7082030/74701469-bfa78480-5241-11ea-8c24-6edd45b3c7cf.jpg)

**Comment by leosam1024** [comment]
删掉了 你试试
