### ISSUE TITLE
列表重复

### ISSUE THREAD

**Issue by Marukon** [ACL4SSR/ACL4SSR#259]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [x] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
Clash规则中，PROXYGFWlist.list文件里面

开头部分：
# 国外域名
DOMAIN-SUFFIX,hk
DOMAIN-SUFFIX,tw
DOMAIN-SUFFIX,sg
DOMAIN-SUFFIX,jp
DOMAIN-SUFFIX,kr
DOMAIN-SUFFIX,uk
DOMAIN-SUFFIX,us
DOMAIN-SUFFIX,tw

.tw重复

**Comment by leosam1024** [comment]
已经修改，谢谢提醒
