### ISSUE TITLE
用了转换clash订阅之后，play商店无法访问

### ISSUE THREAD

**Issue by LeslieLee0420** [ACL4SSR/ACL4SSR#260]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
用了转换订阅的这个链接之后https://acl4ssr.netlify.com，google play商店无法访问

**Comment by leosam1024** [comment]
我这边可以啊，你选定节点了？

**Comment by LeslieLee0420** [comment]
> 我这边可以啊，你选定节点了？
不好意思，我这边的问题，更新一下订阅就好了
