### ISSUE TITLE
master最新 banAD.acl SSR安卓使用后无法解析域名

### ISSUE THREAD

**Issue by yywudi** [ACL4SSR/ACL4SSR#261]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
最新更新的master/banAD.acl 文件, SSR android客户端连接后测试连接提示无法解析域名,
浏览器打开任何网页提示 ERR_NAME_NOT_RESOLVED, Telegram等直接连IP的可以正常连接.

回滚至 # 2020年2月17日 19:04:30 (commit 4d87b7a) 则正常使用.(https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/4d87b7a07e6dd3780d8629d84cf12ae29c5d7838/banAD.acl)

**Comment by leosam1024** [comment]
没问题啊 ，不知道是不是你更新问题
你试试镜像地址
https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/

看看里面的行不行

**Comment by yywudi** [comment]
一样的, 选择2/17的commit,然后ACL,连接测试正常,换成github或者你提供的镜像的master的, 更新完成之后, 连接测试直接报错 

客户端是 https://github.com/shadowsocksRb/shadowsocksRb-android/releases

我有录一段屏幕录制,可供参考, 步骤:
1, 正常连接的节点, 绕过局域网及中国大陆地址, 测试连接正常
2, 添加acl为2.17 commit 的acl,更新, 节点切换为自定义ACL文件, 测试连接正常,
3, 更换ACL为github或者镜像的master, 更新.  断开在连接,使用新ACL, 测试连接失败, 打开网站提示无法解析域名

**Comment by leosam1024** [comment]
我用你这个软件，没有绕过局域网和中国大陆地址啥啊，里面倒是有个acl订阅，填上不管用啊，还是全局
我下载的是v5.0.3R

可以用Maying

**Comment by yywudi** [comment]
我试了一下maying，用master的acl的确没有这个问题，奇怪，难道是最新的什么改动触发了这个app的某个bug？
这个客户端app是同步ss官方客户端为上游改核心为ssr，还不错的

**Comment by leosam1024** [comment]
你那个软件，是ss那些维护者自己实现的acl，有bug，实现不了分流的

**Comment by BROBIRD** [comment]
> 
> 
> 一样的, 选择2/17的commit,然后ACL,连接测试正常,换成github或者你提供的镜像的master的, 更新完成之后, 连接测试直接报错
> 
> 客户端是 https://github.com/shadowsocksRb/shadowsocksRb-android/releases
> 
> 我有录一段屏幕录制,可供参考, 步骤:
> 1, 正常连接的节点, 绕过局域网及中国大陆地址, 测试连接正常
> 2, 添加acl为2.17 commit 的acl,更新, 节点切换为自定义ACL文件, 测试连接正常,
> 3, 更换ACL为github或者镜像的master, 更新. 断开在连接,使用新ACL, 测试连接失败, 打开网站提示无法解析域名

Fixed via https://github.com/ACL4SSR/ACL4SSR/commit/ee99b6fd6443183ae39cc0e53d4c39ea3dc2e56f
