### ISSUE TITLE
www.google.com走了全球直连

### ISSUE THREAD

**Issue by LeslieLee0420** [ACL4SSR/ACL4SSR#263]
* 有关此issue的规则名称：(请将“[ ]”中的**一个**空格**替换**为小写英文字母“x”以勾选！！)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
今天更新规则订阅之后Clash里面www.google.com走了全球直连，但是play商店和youtube是代理的
![Screenshot_20200223-203528_Clash for Android](https://user-images.githubusercontent.com/46532123/75112317-a0fc2000-567d-11ea-8a47-a493d1e0bb4a.jpg)

**Comment by leosam1024** [comment]
谷歌搜索你肯定能上去，那个谷歌直连的是udp的，应该不要紧

**Comment by LeslieLee0420** [comment]
> 谷歌搜索你肯定能上去，那个谷歌直连的是udp的，应该不要紧

搜索连不上了····网页版和google app这俩都连不上了。我换stc的默认规则能连上

**Comment by leosam1024** [comment]
我用的很流畅啊，一点问题都没有。

**Comment by leosam1024** [comment]
你现在更新试试？

**Comment by LeslieLee0420** [comment]
没问题了，大佬。
