### ISSUE TITLE
clash规则问题

### ISSUE THREAD

**Issue by ccboxes** [ACL4SSR/ACL4SSR#267]
发现使用https://acl4ssr.netlify.com/
转换出的clash规则在clash for android上均无法访问Google。
查明原因在于
`- IP-CIDR,0.0.0.0/8,🎯 全球直连`
这一条，删除后可正常访问。
如不删除，则访问Google时log显示
dial 全球直连 error : dial tcp4 0.0.0.0:443: connect : connection refused

**Comment by leosam1024** [comment]
恩 删掉了
