### ISSUE TITLE
google规则不全

### ISSUE THREAD

**Issue by ccboxes** [ACL4SSR/ACL4SSR#268]
大陆手机中内置的Google服务默认使用中国cdn，域名是services.googleapis.cn
但该cdn没有play商店需要的api，会导致play商店无法使用，要解决这个问题要么把服务器重定向到services.googleapis.com，要么用规则强制该域名走代理。

**Comment by BROBIRD** [comment]
Duplicate of #203 and Not following template

**Comment by leosam1024** [comment]
这个不做更改
clash 规则 已经可以了 ，因为走的是关键字
ssr的，规则匹配逻辑我们控制不了，只做了最大化保证
