### ISSUE TITLE
已有的Clash订阅地址如何转换添加ACL4SSR规则？

### ISSUE THREAD

**Issue by sceraser** [ACL4SSR/ACL4SSR#269]
只能拆出其中每个节点的地址然后一个个在https://acl4ssr.netlify.com/转换吗？有没有更高效的方法

**Comment by leosam1024** [comment]
直接把你订阅地址输入在订阅栏就行，他会自动转换的，不懂的话可以tg问我

订阅 或者 单链接 都支持
