### ISSUE TITLE
请问ssr单纯使用去广告应该如何设置？

### ISSUE THREAD

**Issue by vokins** [ACL4SSR/ACL4SSR#27]
没有用戴笠服务，只是单纯使用ssr处理ad和智能转向应该如何设置？

**Comment by Love4Taylor** [comment]
不用代理的话..... 去广告软件不是多了去么.... 现有的 ACL 不管怎么总要涉及到部分流量走 SSR 服务器的....

**Comment by MichaelHu55** [comment]
现在去广告的列表比vokins的还是少太多了。很多都没有收录进来。

**Comment by vokins** [comment]
谢谢

**Comment by BROBIRD** [comment]
如果 @vokins 同意的话 大概下个月我会筛选yhosts里的域名添加到去广告列表
