### ISSUE TITLE
求解一个clash规则生成的问题

### ISSUE THREAD

**Issue by itcodes** [ACL4SSR/ACL4SSR#270]
我是自己搭的。但是发现模仿别人家的写了，压根就连不上。用咱们的这个生成也是无法连接。但是我用V2rayU是可以正常连接的。。。求一位大佬指挥一下。感谢。

我是用的下面的信息：
2. Clash规则
 LocalAreaNetwork.list：更新完善内网规则(只保留最主要的)
 ProxyLite.list：完善谷歌域名，将P站加入代理
 GeneralClashConfig.yml：更新CFW基础配置文件，整理直连域名

欢迎更新、测试规则，有问题可以直接tg联系或者提issue

ACL4SSR在线Clash等规则订阅转换：https://acl4ssr.netlify.com
项目镜像：https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@latest/
项目地址：https://github.com/ACL4SSR/ACL4SSR

**Comment by itcodes** [comment]
@leosam1024 大佬可否帮我看看。谢谢。

**Comment by leosam1024** [comment]
可以tg联系我

**Comment by itcodes** [comment]
> 可以tg联系我

需要添加你好友才可以发消息。我已经添加了。我叫BKBLL

**Comment by itcodes** [comment]
已经完美解决这个问题。非常感谢。
