### ISSUE TITLE
建议移除 .cn 域名走直连的规则

### ISSUE THREAD

**Issue by lgc2333** [ACL4SSR/ACL4SSR#275]
RT，被墙的例子如 chat.laplace.live （此网页会请求laplace.cn但是被墙导致无法正常使用）， 0d00.cn （我自己的域名，部署在cf pages上的静态页面，也被墙）等

**Comment by fxzxmicah** [comment]
删除一个.cn，会需要无数条.cn的细化规则。然而.cn可以直连的占多数，不可直连占少数，所以少数才是例外，需要额外的规则设置。

**Comment by lgc2333** [comment]
了解了，谢谢解释
