### ISSUE TITLE
请求在gitee上做个镜像仓库

### ISSUE THREAD

**Issue by fgprodigal** [ACL4SSR/ACL4SSR#276]
我这不连代理连github也被墙，所以在ssr客户端里没法使用github上的acl，能否考虑在码云(gitee)上建个镜像仓库，国内访问也更快，开发者本地就加个remote，也不会很麻烦

**Comment by fgprodigal** [comment]
像 https://github.com/privacy-protection-tools/anti-AD 这个项目就提供了gitee的链接

**Comment by leosam1024** [comment]
ACL4SSR在线Clash等规则订阅转换：https://acl4ssr.netlify.com
项目镜像：https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@latest/
项目地址：https://github.com/ACL4SSR/ACL4SSR


有镜像地址的

**Comment by fgprodigal** [comment]
感谢
