### ISSUE TITLE
关于国外域名关键词匹配范围过大的问题

### ISSUE THREAD

**Issue by ForestL18** [ACL4SSR/ACL4SSR#28]
# 国外域名
DOMAIN-SUFFIX,eu
DOMAIN-SUFFIX,hk
DOMAIN-SUFFIX,jp
DOMAIN-SUFFIX,kr
DOMAIN-SUFFIX,sg
DOMAIN-SUFFIX,tw
DOMAIN-SUFFIX,uk
DOMAIN-SUFFIX,us
DOMAIN-SUFFIX,ca

上述国外域名关键词范围匹配过大，容易将一些含有上述关键词的国内域名也给匹配上

建议在关键词前后加上.如`.eu` 或 `eu.`，以此匹配国外通用域名

**Comment by acl4ssr-sub** [comment]
DOMAIN-SUFFIX 本身就是以什么结尾的意思 不需要加点吧
