### ISSUE TITLE
打不开支持ipv6的教育网站

### ISSUE THREAD

**Issue by lidyu2019** [ACL4SSR/ACL4SSR#283]
转换ssr配置文件在clash上用打不开只支持ipv6的教育网站，用subconverter转换的ConnersHua文件夹你的规则是可以打开的，用ACL4SSR的打不开

**Comment by leosam1024** [comment]
我这没有教育网环境啊，你能知道那个规则拦截的吗？

**Comment by lidyu2019** [comment]
用subconverter里的全球连接可以在clash连接里显示https://dh.sau.edu.cn/ 走的全球连接，用ACLSSR后没有任何连接提示，直接打不开这个网站，我把拦截规则全部去掉都不行，这是电视直播页面，我也没有教育网环境。

**Comment by lidyu2019** [comment]
导致提取的直播源在电视盒子上也无法播放，不知到ACLSSR的转换程序是不是有问题，用subconverter_win64本地转换的没有问题，用subconverter_0.4.2_acl4ssr里的run.cmd这个转换的就不行

**Comment by leosam1024** [comment]
你ping一下 这个ip 看看地址是那个？

**Comment by lidyu2019** [comment]
把ACLSSR规则放在subconverter_0.4.2里替换全部用ACLSSR的规则转换来还是不能播放，看来还是规则有问题，我把这个网站域名直接放在ChinaDomain.list里都不行

**Comment by lidyu2019** [comment]
ping 出的是这个198.18.0.41 ping不通 站长工具查出来的202.199.27.11

**Comment by lidyu2019** [comment]
用subconverter_win64原版配置的可以看到全球直连显示的域名，ACLSSR的校园用的ipv6直播都不行

**Comment by leosam1024** [comment]
clash 开启debug 看日志

**Comment by lidyu2019** [comment]
用的openclash，没有debug选项，在连接日志里看不到https://dh.sau.edu.cn/这个记录，还有http://iptv.pdsu.edu.cn/这个网站也打不开

**Comment by leosam1024** [comment]
那就不清楚了，我这没ipv6 测试不了 

但是cn域名后缀的 都是放行的
