### ISSUE TITLE
youtube好像重复了。

### ISSUE THREAD

**Issue by KingPollux** [ACL4SSR/ACL4SSR#287]
youtube有两条路，一条走节点选择，一条走全球媒体。不知是不是有意的？应该是走全球媒体吧？

**Comment by KingPollux** [comment]
> 
> 
> youtube有两条路，一条走节点选择，一条走全球媒体。不知是不是有意的？应该是走全球媒体吧？

同样的，电报消息，奈非视频，都有这类重复。软件应该会优先选择走“节点选择”。

**Comment by qhfls** [comment]
应该是按rulesets的顺序来选择适用那种选择

**Comment by leosam1024** [comment]
重复是因为clash的匹配规则是自上往下的。
只要youtube在全球媒体里有，而且全球媒体在规则靠上，那么他就只会走全球媒体，不会走节点选择
重复不重复无所谓，关键是我好维护。

**Comment by KingPollux** [comment]
哦~~这样啊，明白了。
顺便请问下，像mini那个规则，装到路由器老毛子固件里，出现这个循环错误而不能开启clash。
“level=fatal msg="Parse config error: Loop is detected in ProxyGroup, please check following ProxyGroups: [🎯 全球直连 🚀 节点选择]"
这应该怎么解决？（我用机场自带的没有规则的订阅可以正常开启运行。）

**Comment by leosam1024** [comment]
不会啊 ，你可以tg找我看看

**Comment by KingPollux** [comment]
哦，后来我折腾了一下。可以，非常好用。前面是因为用本地后端，路由器不能订阅，然后我就把生成的代码全部复制过去。路由器运行的时候就炸了吧。后来用网页后端，完美解决问题。最后还是非常感谢有这么好的规则。赞一个~
