### ISSUE TITLE
Mozilla相关域名连接极慢

### ISSUE THREAD

**Issue by ccboxes** [ACL4SSR/ACL4SSR#288]
Mozilla相关域名直连虽然可以打开，但在部分省市速度极慢。考虑到其服务器都位于境外（少数境内服务域名均为cn后缀），是否可以删除相关域名的直连规则？

**Comment by leosam1024** [comment]
ok  已经删除

**Comment by ccboxes** [comment]
> ok 已经删除

OK

**Comment by ccboxes** [comment]
> ok 已经删除

并没有删除，firefox.com仍然在全球直连规则组里

**Comment by leosam1024** [comment]
firefox 我不挂代理 300毫秒，挂代理 900毫秒

**Comment by ccboxes** [comment]
> firefox 我不挂代理 300毫秒，挂代理 900毫秒

所以说这就很尴尬，部分省市比如我现在光打开页面就要十几秒，monitor.firefox.com这种还有dns污染

**Comment by leosam1024** [comment]
恩 删了 让他走代理吧

**Comment by ccboxes** [comment]
> 恩 删了 让他走代理吧

firefox.com这种毕竟访问的少，主要还是注重连通性。
