### ISSUE TITLE
“进阶模式”中“包含节点”和“排除节点”功能矛盾

### ISSUE THREAD

**Issue by ioudove** [ACL4SSR/ACL4SSR#29]
“包含节点”和“排除节点”要求输入的内容其实是刚好相对立、相反的内容。因此这两个功能实际上是一个功能。我想在我所有的节点中删除：节点名字中含有“海外直连”的节点。这个结果就无法实现，因为没有符合逻辑的内容可以输入到“包含节点”和“排除节点”中
望改进

**Comment by acl4ssr-sub** [comment]
这个不在我项目里反映，是转换项目的
