### ISSUE TITLE
请添加域名services.googleapis.cn至代理列表

### ISSUE THREAD

**Issue by rospod** [ACL4SSR/ACL4SSR#291]
部分国行手机会因为该项无法代理，导致无法使用play

**Comment by leosam1024** [comment]
ACL里面有啊，这个是在代理列表里面
(^|\.)googleapis\.cn$

另外clash也是代理的
  - DOMAIN-KEYWORD,google,🚀 节点选择

你用的是什么软件?

**Comment by rospod** [comment]
clashR for Android
不过它往直连连了
INF0 [ TCP ]172.31.255.253:56122-->services.googleapis.cn match DomainSuffix using 国内媒体[ DIRECT]

**Comment by leosam1024** [comment]
兄弟，你不是用我的配置，别找我反映啊。

我没国内媒体的分组啊。

你好好看看，你用的谁的规则。

有些后台节点，默认规则，不是我的配置

**Comment by rospod** [comment]
https://gfwsb.114514.best/sub?target=clashr&url=######&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FAC

**Comment by rospod** [comment]
这个是订阅链接

**Comment by leosam1024** [comment]
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/AC

这个config网址 不对啊 

不对的话，他会使用默认的配置的
