### ISSUE TITLE
建议单独列OneDrive OneNote相关规则

### ISSUE THREAD

**Issue by chenxinyucn** [ACL4SSR/ACL4SSR#293]
现有规则仅有“微软服务”规则，但是往往仅OneDrive、OneNote等服务需要代理加速传输，Windows相关服务并不需要通过代理。
希望能够将OneDrive、OneNote相关规则单列，谢谢！

**Comment by leosam1024** [comment]
自己做个配置吧。
暂时没时间做

**Comment by leosam1024** [comment]
OneDrive 已经有了 
OneNote 没时间做。随缘吧
