### ISSUE TITLE
直连规则不完善

### ISSUE THREAD

**Issue by jiangshuwen20010528** [ACL4SSR/ACL4SSR#294]
虎牙直播流量会走代理的

**Comment by leosam1024** [comment]
。。。。
你这说的太不完善了 

用的什么软件 
什么规则

。。。。

这么写 啥也干不了

**Comment by jiangshuwen20010528** [comment]
> 。。。。
> 你这说的太不完善了
> 
> 用的什么软件
> 什么规则
> 
> 。。。。
> 
> 这么写 啥也干不了

**Comment by jiangshuwen20010528** [comment]
![屏幕截图(52)](https://user-images.githubusercontent.com/62324556/77311137-867b9c00-6d3a-11ea-8c55-c540b29082d6.png)
clash开启了本地代理共享，我用手机打开虎牙直播软件时，connetions中显示livewebbs2.msstatic.om：80走的是代理路线，这应该是虎牙直播的流量应该设置为直连吧？

**Comment by leosam1024** [comment]
你需要点击一下这个链接，查看一下他具体是走的那个规则。
我这边是走的geo cn策略

是直连的

**Comment by leosam1024** [comment]
已经强制添加msstatic.om 直连了。
