### ISSUE TITLE
误杀：BanProgramAD.list

### ISSUE THREAD

**Issue by Liquor030** [ACL4SSR/ACL4SSR#297]
DOMAIN-SUFFIX,iadmat.nosdn.127.net
误杀例子：
http://iadmat.nosdn.127.net/55314037f5274f868507a25ca82efd24.jpg
http://iadmat.nosdn.127.net/b0a8990db2f24978af099198844ff652.jpg
http://iadmat.nosdn.127.net/907addd860724bd488325383795c9b4a.jpg

**Comment by leosam1024** [comment]
已经删除，谢谢反馈
