### ISSUE TITLE
banad规则会导致epic不能安装游戏

### ISSUE THREAD

**Issue by lijianbin2** [ACL4SSR/ACL4SSR#302]
epic平台的安装界面被当成广告拦截

**Comment by leosam1024** [comment]
我不用epic ，请告诉一下被拦截的URL

**Comment by lijianbin2** [comment]
> 我不用epic ，请告诉一下被拦截的URL

eulatracking-public-service-prod06.ol.epicgames.com

**Comment by leosam1024** [comment]
如果你用clash的话，安装的时候 暂时放行吧，将拦截改成直连
SSR的话，切换一下acl吧。

主要被tracking 关键字拦截了。

这个用来去除追踪的

**Comment by leosam1024** [comment]
或者我想个法子

**Comment by leosam1024** [comment]
ok 解决了，添加了一个广告白名单

**Comment by lijianbin2** [comment]
ok，辛苦了
