### ISSUE TITLE
漏网之鱼的规则有误报

### ISSUE THREAD

**Issue by Czerror** [ACL4SSR/ACL4SSR#306]
地址是这个 
img4.nga.178.com
最近两周内的规则出现的问题

**Comment by leosam1024** [comment]
不是有geoip cn 兜底吗？
这个178 肯定是中国境内的啊。
不会走兜底规则啊

你更新一下geo ip地址库吧

**Comment by Czerror** [comment]
> 不是有geoip cn 兜底吗？
> 这个178 肯定是中国境内的啊。
> 不会走兜底规则啊
> 
> 你更新一下geo ip地址库吧

3Q 解决问题了  原来是我太久没更新geo ip了
