### ISSUE TITLE
希望加入更多国外广告的过滤

### ISSUE THREAD

**Issue by Platway** [ACL4SSR/ACL4SSR#31]
可参考AdAway原版的广告列表。您的工作十分有价值，非常感谢！

**Comment by BROBIRD** [comment]
感谢您的建议，也希望您继续支持、参与完善我们的项目！

2017年9月3日 10:35，"Platway" <notifications@github.com>写道：

**Comment by leosam1995** [comment]
已添加，要是有更好的广告源 请告知
