### ISSUE TITLE
Netflix节点分组仅有direct

### ISSUE THREAD

**Issue by ColinLeeeee** [ACL4SSR/ACL4SSR#310]
所用配置：ACL4SSR_Online_Full_AdblockPlus
代理客户端: Clash

奈飞节点分组仅有direct，可能是bug？

**Comment by leosam1024** [comment]
不是有手动分组么
如果你有支持奈飞的节点，那么你奈飞节点也会出来的

**Comment by ColinLeeeee** [comment]
![image](https://user-images.githubusercontent.com/33202088/78472089-d3af3300-7768-11ea-8b18-71627dee21cb.png)
![image](https://user-images.githubusercontent.com/33202088/78472094-d873e700-7768-11ea-9a4e-218ee58d81c5.png)
对目前是依靠手动切换。
我的大部分节点都是支持奈飞的，但是奈飞节点分组下只有个direct，不知道为什么。

**Comment by leosam1024** [comment]
这个分组是按节点名称过滤的 (NF|解锁|Netflix|NETFLIX)
可能你节点名称 不包含这几个名称

**Comment by ColinLeeeee** [comment]
哦哦，懂啦。不过这样可能不是很方便很多机场都不在名字里标hh，那么多中转都可以解锁nf

**Comment by wlyzqm** [comment]
很多机场都是全节点解锁Netflix的，建议把所有节点加入Netflix节点列表让用户自己去选。

**Comment by leosam1024** [comment]
你直接选择一下奈飞视频-》手动切换就行。
在手动切换里面 选择一个就行

**Comment by wlyzqm** [comment]
这个方式可以的，只不过有的时候例如Netflix要看美区的时候，其他某个代理组用手动切换就一起跟着去美区了。
我目前是手改了规则。把所有节点一个一个都添加进去了。

**Comment by leosam1024** [comment]
为啥不fork一下我的项目，直接改一下配置，自己做个配置就行。
就不用每次手工添加了

**Comment by wlyzqm** [comment]
-_-! 不太会用，近期fork一下试试。

**Comment by wlyzqm** [comment]
OK fork之后看了下，看懂了，真的好用，非常感谢。
