### ISSUE TITLE
访问某些网站时会出现Dial failed的情况

### ISSUE THREAD

**Issue by wyptaotao** [ACL4SSR/ACL4SSR#314]
现在使用的是无自动测速规则，但之前使用的其他规则也有这个问题。
偶尔会出现这个问题，目前使用steam社区时一定会出现
日志中是
![image](https://user-images.githubusercontent.com/62679796/78672518-5247d400-7913-11ea-873e-c56f0a5b2a07.png)

**Comment by leosam1024** [comment]
跟规则无关，这个可能是网络不稳定、机场断流或者clash内核问题有关

**Comment by wyptaotao** [comment]
更换了一个规则后不再出现……

**Comment by leosam1024** [comment]
你们steam 一般是直连的？

**Comment by wyptaotao** [comment]
不是啊……规则里也是走代理的啊
![image](https://user-images.githubusercontent.com/62679796/78679555-f5e9b200-791c-11ea-9325-be75e7e1573f.png)

**Comment by leosam1024** [comment]
这个肯定是代理的 这2个网站。

**Comment by leosam1024** [comment]
差不多应该好了，应该是dns劫持
