### ISSUE TITLE
完跑跑卡丁车连不上服务器

### ISSUE THREAD

**Issue by demmosee** [ACL4SSR/ACL4SSR#316]
我是通过旁路由用openclash上网的，用规则模式，没办法连上跑跑卡丁车服务器，不通过旁路由就可以连上了~

**Comment by Android-AwesomeRoy** [comment]
> 我是通过旁路由用openclash上网的，用规则模式，没办法连上跑跑卡丁车服务器，不通过旁路由就可以连上了~

我觉得有可能是你OpenClash的配置选项有问题，不要用 `fake-ip`，用 `redir-host`

**Comment by demmosee** [comment]
> > 我是通过旁路由用openclash上网的，用规则模式，没办法连上跑跑卡丁车服务器，不通过旁路由就可以连上了~
> 
> 我觉得有可能是你OpenClash的配置选项有问题，不要用 `fake-ip`，用 `redir-host`

我是用redir–host ,默认就是这个
