### ISSUE TITLE
网页定制订阅转换的时候，能否能增加屏蔽节点的功能？

### ISSUE THREAD

**Issue by lukemin** [ACL4SSR/ACL4SSR#320]
我用的机场部分节点的网络不太好，我想再订阅的时候屏蔽掉部分的节点，应该如何处理？

**Comment by leosam1024** [comment]
进阶模式，里面有排除ExcludeRemarks 、包含IncludeRemarks
可以实现你的需求

**Comment by lukemin** [comment]
我想屏蔽有美国名称的节点，是填在 ExcludeRemarks 里面吗?

**Comment by leosam1024** [comment]
对,填 美 就行

**Comment by lukemin** [comment]
多个节点，中间应该用什么符号？我用的半角逗号不行

**Comment by lukemin** [comment]
![微信截图_20200409200428](https://user-images.githubusercontent.com/12003375/78893150-5dc70680-7a9d-11ea-933b-be725532c00f.png)
我的节点列表

**Comment by leosam1024** [comment]
IncludeRemarks 填 (HK|SGP|NF2)

**Comment by lukemin** [comment]
两个规则没有办法同时填写，填了就出现400错误

**Comment by leosam1024** [comment]
自己看一下 对应的说明文档吧
