### ISSUE TITLE
版本更新覆盖问题

### ISSUE THREAD

**Issue by merry200603** [ACL4SSR/ACL4SSR#321]
最近才开始使用的0.9.4版本，刚发现有0.9.5更新，就下载了，然后覆盖原文件夹。打开新版之后，发现订阅全被清空了

之前使用clash时，新版本是可以直接覆盖旧版本的，希望能处理一下，方便在版本升级的时候可以直接覆盖，谢谢！

还有一个问题，个人用的一个ss站部分节点没有加密（cipher: none），在ssr中可以正常使用，在clashR中貌似是没办法使用的，也希望能解决下，谢谢！

**Comment by leosam1024** [comment]
第一个问题。目录下有个便携目录。自己把以前的替换进去就行，不懂的话 看对应软件的官方文档。
第二个问题。 我不是软件开发者。 支不支持加密我决定不了。你可以上对应项目上进行提issue。
