### ISSUE TITLE
我用的是gfwlist-banAD，你试试看这个？

### ISSUE THREAD

**Issue by shikkoku** [ACL4SSR/ACL4SSR#322]
我用的是gfwlist-banAD，你试试看这个？

_Originally posted by @BROBIRD in https://github.com/ACL4SSR/ACL4SSR/issues/237#issuecomment-613301169_

我有手游要走代理，所以不太想用GFWLIST规则。

**Comment by BROBIRD** [comment]
有必要新开个issue？
