### ISSUE TITLE
[clash规则]google的ip被误分为全球直连

### ISSUE THREAD

**Issue by zhongfly** [ACL4SSR/ACL4SSR#323]
![Screenshot_20200414165459](https://user-images.githubusercontent.com/11155705/79205854-11027780-7e71-11ea-96be-5202461be9c1.png)
如果全球直连选择Direct时会导致无法访问google，这时会报错：
dial 🎯 全球直连 error: dial tcp4 127.0.0.1:443: connect: connection refused

**Comment by zhongfly** [comment]
发现是与网络环境有关，其他运营商网络下正常。
https://github.com/ACL4SSR/ACL4SSR/issues/314

**Comment by leosam1024** [comment]
换个dns 就行。明显的网络dns 劫持。
