### ISSUE TITLE
系统代理自动关闭

### ISSUE THREAD

**Issue by jiangshuwen20010528** [ACL4SSR/ACL4SSR#324]
正常打开系统代理
![QQ截图20200415212822](https://user-images.githubusercontent.com/62324556/79342870-3f12b500-7f60-11ea-9372-af6efb90a282.png)
过一会代理自动关闭（clash里面没显示但是已经不能访问谷歌了）系统代理被自动修改为192.168.0.103
这种情况应该怎么办？我现在直接不开系统代理，只打开局域网共享把那个IP填进去，这样有什么不一样吗？

**Comment by leosam1024** [comment]
这个跟软件有关系。有软件动你系统代理。
如果这个解决不了，浏览器配合Proxy SwitchyOmega插件吧，别开系统代理了
