### ISSUE TITLE
gfwlist规则添加

### ISSUE THREAD

**Issue by Iongtimenosee** [ACL4SSR/ACL4SSR#329]
wikiquote.org维基语录被墙，fullgfwlist.acl，Clash/ProxyGFWlist.list里面都没看到，怎么加进去？

**Comment by leosam1024** [comment]
本项目不进行被墙域名维护。只做GFWlist同步。可以跟GFWlist项目维护者提问。
也可以自己fork一下本项目。自己添加一下
