### ISSUE TITLE
应用后安卓淘宝和JD的LIST图片加载好像受阻

### ISSUE THREAD

**Issue by TsXcd** [ACL4SSR/ACL4SSR#33]
RT

**Comment by BROBIRD** [comment]
请使用“分应用代理”功能

2017年9月6日 16:49，"TsXcd" <notifications@github.com>写道：

**Comment by TsXcd** [comment]
还说需不需要抓包看看是啥规则，果然还是绕过模式吧这些误伤的APP绕开会比较好...
