### ISSUE TITLE
gfwlist列表有版本不同步现象

### ISSUE THREAD

**Issue by Iongtimenosee** [ACL4SSR/ACL4SSR#330]
wikiquote.org维基语录是被墙网站。这里这个项目应该是同步这个地址的吧：https://github.com/gfwlist/gfwlist/blob/master/gfwlist.txt这个列表里面有wikiquote.org这个地址。

这里这个项目的“/master/gfwlist-user.rule”这个文件里面也有这个地址，但是“/master/fullgfwlist.acl”和“/master/Clash/ProxyGFWlist.list”这两个文件却没有。按字面意思理解这些应该都是来自gfwlist里的地址，只是不同格式。但为啥这个域名有的有，有的没有？新手不懂抱歉。

**Comment by BROBIRD** [comment]
刚才确认过了，gfwlist里面没有wikiquote.org这个地址，如果你觉得有问题请向gfwlist项目反馈
gfwlist-user.rule目前处于无限期停更状态
