### ISSUE TITLE
请问 Chains 和 Rule 是如何进行判断的?

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [ACL4SSR/ACL4SSR#331]
![image](https://user-images.githubusercontent.com/19187129/79644912-8ad29200-81de-11ea-9060-30ce6da5f3a0.png)
上面截图中是我发现的没有走 {漏网之鱼} 的网站, 并且在 规则判断上是 `DERECT` 和 `MATCH`, 不过这些域名并没有包含在规则列表里.

---

### 下面是我用于在subconverter生成的规则列表: 
- Groups:
![image](https://user-images.githubusercontent.com/19187129/79644968-edc42900-81de-11ea-913c-bd9a396928d3.png)

- Rulesets:
![image](https://user-images.githubusercontent.com/19187129/79644977-f583cd80-81de-11ea-9588-6eca104d3ceb.png)

---

我的问题是: 一个网站域名, 没有在文件中被匹配到, 为什么没有走 {漏网之鱼} 这个策略呢? 我应该如何设置才能自动去判断或者取消掉 `DERECT` 和 `MATCH`

**Comment by leosam1024** [comment]
先走rule列表，从上往下匹配。
匹配到具体的rule之后。查看该rule对应的分组。
然后在chains链表上一次找该分组对应的最终指向分组。

如果你没有匹配上。那么会被rule列表的最后一条final兜底。这条规则是匹配全部的意思。

**Comment by Android-AwesomeRoy** [comment]
@leosam1024  那我第一张图中的链接，无法匹配到 final，应该怎么解决呢？

**Comment by leosam1024** [comment]
自己编辑一下规则吧
