### ISSUE TITLE
https://acl4ssr.netlify.com   在线订阅转换ssr节点，密码前多了个!<str> 导致错误

### ISSUE THREAD

**Issue by HorrZzz** [ACL4SSR/ACL4SSR#333]
https://acl4ssr.netlify.com   在线订阅转换ssr为clashr，节点密码前多了个!<str> 导致错误

**Comment by leosam1024** [comment]
https://github.com/tindy2013/subconverter 可以在这里提问。
这里是后端接口的开源地址
