### ISSUE TITLE
再次确认过了，gfwlist里面有wikiquote（附地址和截图）

### ISSUE THREAD

**Issue by Iongtimenosee** [ACL4SSR/ACL4SSR#334]
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
这个文件解密后，第7499,7500行，有wikiquote.org这个地址

您这里的一个文件也有：
https://github.com/ACL4SSR/ACL4SSR/blob/master/gfwlist-user.rule
这个文件的4899行，也有wikiquote.org这个地址。

但下面这两个没有：
https://github.com/ACL4SSR/ACL4SSR/blob/master/fullgfwlist.acl
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ProxyGFWlist.list

附上相关截图：
![gfwlist](https://user-images.githubusercontent.com/58037951/79956965-7549ba80-84b3-11ea-9c0b-ad99781a1600.png)
![user](https://user-images.githubusercontent.com/58037951/79956979-7c70c880-84b3-11ea-8a62-291e7b2b27b4.png)

**Comment by BROBIRD** [comment]
`!--`是注释

**Comment by Iongtimenosee** [comment]
既然是注释，为什么这边有的文件启用有的文件不启用？

**Comment by Iongtimenosee** [comment]
> `!--`是注释

既然是注释，为什么这边有的文件启用有的文件不启用？

**Comment by BROBIRD** [comment]
![图片](https://user-images.githubusercontent.com/7692707/79958040-0d946f00-84b5-11ea-9d1d-73b5a911fa3f.png)
看到这个文件的最后更新时间了没？
