### ISSUE TITLE
建议增加有关学术网站直连的代理规则

### ISSUE THREAD

**Issue by Aryous** [ACL4SSR/ACL4SSR#335]
部分高校会提供相关的VPN服务以满足老师及学生文献搜索及下载的需求，然而高校的VPN服务无法与Clash等代理软件共存（规则冲突？），因此希望增加针对有关学术网站直连的规则，以实现在访问学术网站时采用高校的VPN服务，同时不会影响Google等网站的访问。
感谢！

**Comment by leosam1024** [comment]
我不用这些网站，所以无从下手。
如果你可以提供网站列表的话，我可以参考一下。

**Comment by Aryous** [comment]
非常感谢回复！
之前自己尝试添加了一些规则，但是由于自己完全是代码小白，无法实现ini文件的配置，因此每次更新订阅之后，自己需要重新进行规则添加。
感谢帮助！
 
常见学术网站域名：（待补充）
webofknowledge.com
cnki.net
wanfangdata.com
pkulaw.com
westlawchina.com
researchgate.net
springer.com
blackwell-synergy.com
sciencemag.org
jstor.org
cabdirect.org
ieee.org
nature.com
sciencemag.org
osapublishing.org
wiley.com
readcube.com
scopus.com
sciencedirect.com
elsevier.com
deepdyve.com
els-cdn.com
oup.com
cqvip.com

**Comment by leosam1024** [comment]
添加学术网站碎片-Clash/Ruleset/Scholar.list
自己写一个配置文件吧
