### ISSUE TITLE
建议在订阅转换中提供DNS设定

### ISSUE THREAD

**Issue by Thundercup** [ACL4SSR/ACL4SSR#338]
订阅转换所得到的clash配置文件在每次更新后都要手动在文件中设定DNS，造成了不必要的麻烦，希望订阅转换的网页可以直接提供更改clash配置DNS的选项，以此解决这个问题

**Comment by leosam1024** [comment]
推荐看这个 https://github.com/tindy2013/subconverter/blob/master/README-cn.md
自己根据后台接口 ，手工设定不同参数吧。
dns选项可以写到cfw里面的主yml里面。具体看对应官方文档
