### ISSUE TITLE
对ClashR有些疑问

### ISSUE THREAD

**Issue by Gokou-Ruri** [ACL4SSR/ACL4SSR#339]
关于ClashR for Windows有两个疑问请教一下：

1、现在导入了v2ray的节点以后，能使用了，配置用的是 `ACL4SSR_Online_AdblockPlus.ini` ，但是我想添加自定义的域名到ACL文件里（不适合提交到ACL4SSR但对我来说只能走代理的域名），有什么比较好的办法吗？我的意思是，有没有办法像SSR客户端那样添加一个用户自定义PAC/ACL？这样方便我增添域名/IP。

2、我现在有两个不同订阅的v2ray节点（比如A订阅和B订阅是两个不同机场），这两种节点不能混在一起使用吗？我在Profiles中选了A订阅以后，在 Proxies - Rule 里就看不到B订阅的节点了。

**Comment by shikkoku** [comment]
这个项目和ClashR有关系吗……

**Comment by leosam1024** [comment]
本项目 只做规则分流这类的工作。你可以fork一下本项目，自己添加一下自定义规则。
如果不知道怎么fork 编写，推荐搜索引擎搜索一下
具体到软件，推荐看官方文档。软件不支持，我也没办法。

**Comment by Gokou-Ruri** [comment]
> 这个项目和ClashR有关系吗……

我的表达有误，其实准确的说我是想问问ACL2SSR维护者放出的ClashR里的内置规则相关的问题。

**Comment by Gokou-Ruri** [comment]
> 本项目 只做规则分流这类的工作。你可以fork一下本项目，自己添加一下自定义规则。
> 如果不知道怎么fork 编写，推荐搜索引擎搜索一下
> 具体到软件，推荐看官方文档。软件不支持，我也没办法。

感谢回复，向您请教一下TG频道内发布的ClashR内置规则中的“全球直连”和“全球拦截”有什么区别？因为我是第一次用这个程序，有点摸不着头脑，不好意思。
另：请问自定义规则的添加是直接将写好的规则文件放进对应目录吗？会不会因为ClashR版本更新等情况导致被覆盖呢？

**Comment by leosam1024** [comment]
全球直连 是不经过代理直接连接
全球拦截 是直接阻断连接请求，用来屏蔽广告

使用在线订阅，转换出来的订阅。不管在那个版本里 都直接更新就行

**Comment by Gokou-Ruri** [comment]
> 全球直连 是不经过代理直接连接
> 全球拦截 是直接阻断连接请求，用来屏蔽广告
> 
> 使用在线订阅，转换出来的订阅。不管在那个版本里 都直接更新就行

感谢回复！有点明白了，我把问题关了吧，再去摸索看看。
