### ISSUE TITLE
请添加renren.com

### ISSUE THREAD

**Issue by JackChen007** [ACL4SSR/ACL4SSR#34]
人人网站上有很多广告，手机网页快看不到正文了。

**Comment by BROBIRD** [comment]
请提供截图，谢谢

**Comment by JackChen007** [comment]
![screenshot_20170914-153341](https://user-images.githubusercontent.com/5867750/30417406-3135e6fa-9962-11e7-979e-af8746a43c30.png)

**Comment by JackChen007** [comment]
不好意思，上下端的两个广告是我后来把ACL取消了，不知道右边的悬浮图标能否屏蔽，网址是activity.tuia.cn

**Comment by BROBIRD** [comment]
感觉像是某种劫持，下个版本加入

**Comment by leosam1995** [comment]
tuia.cn已添加
