### ISSUE TITLE
对于国行框架手机能不能强制让这个域名googleapis.cn走代理

### ISSUE THREAD

**Issue by SpikerA** [ACL4SSR/ACL4SSR#342]
国行预置框架的商店启动时会向services.googleapis.cn获取数据，而正常情况下(国际版)是向services.googleapis.com获取的。
由于众所周知的原因，googleapis.cn指向了国内的服务器，不能提供完整的服务。

能否在规则上添加googleapis.cn这个域名让其强制走代理？

**Comment by leosam1024** [comment]
ssr 的acl够呛
clash 已经是了

**Comment by BROBIRD** [comment]
ACL里面早就有了
