### ISSUE TITLE
使用在线托管转换器由于配置文件含有GoogleCN.list导致连接失败

### ISSUE THREAD

**Issue by lolicon-cu** [ACL4SSR/ACL4SSR#343]
几天前开始部分地区gstatic.com被阻断了，翻了一下在线规则配置文件发现基本都有这个碎片：
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list

但是GoogleCN.list里的几个与gstatic.com有关的网址使用直连已经无法连接，这会导致谷歌系网站内的部分图标和菜单无法加载，希望可以修复一下

当然个人还是希望能够默认不包含GoogleCN.list这个碎片，谷歌系的网址基本要被屏蔽得七七八八了。。。

**Comment by BROBIRD** [comment]
http://www.17ce.com/site/http/20200427_c17318f0884811ea99f98927441aa9a5:1.html
http://www.17ce.com/site/http/20200427_ea5df370884811ea99f98927441aa9a5:1.html
http://www.17ce.com/site/http/20200427_0a6b5d60884911ea82f00f72e195befa:1.html
http://www.17ce.com/site/http/20200427_1a7b2690884911ea99f98927441aa9a5:1.html
http://www.17ce.com/site/http/20200427_2fafc520884911ea99f98927441aa9a5:1.html

并不存在你所说的问题。
请检查你的DNS
