### ISSUE TITLE
您好，请问能否在分流规则里面加入部分规则

### ISSUE THREAD

**Issue by jh3274** [ACL4SSR/ACL4SSR#347]
例如google，dropbox这些  以方便用大流量服务器专门用来备份资料

另外 希望 视频分流加入 tv-tokyo.co.jp 这个站点 谢谢

**Comment by leosam1024** [comment]
个人维护规则，确实不能很全面，这个是不可避免的
所以考虑到了这一点，我弄了ACL4SSR\Clash\Ruleset 规则碎片集合
这个是方便你们特殊需求，自定义的。

你们可以fork本项目，自己实现一下订阅转换规则配置，很简单，参考config文件就行，以及对应的后端文档。

tv-tokyo.co.jp 可以考虑加上去。

综上所述：添加分组的话，在线配置已经太多了，支持自己弄一个属于自己的配置。特殊网站可以加上去
