### ISSUE TITLE
提交两个挂载代理连不上去的网址

### ISSUE THREAD

**Issue by pudding1111** [ACL4SSR/ACL4SSR#348]
第一个是百度统计，https://tongji.baidu.com/  ，这个反馈ERR_CONNECTION_CLOSED，猜测不允许外网访问，请求添加到放行名单，每一次更新都要手动添加，我想偷偷懒啊。
第二个是看番的地址，http://www.kisssub.org/  这个问题有点迷，我查看log，在“漏网之鱼”设置成“直连”模式，电脑端反馈ERR_EMPTY_RESPONSE，手机端反馈ERR_CONNECTION_RESET，选择节点能正常连接，但是我在相关tg群反馈http://www.kisssub.org/ 打不开时，有群友反馈挂梯子不能上，直连能上，并且截图给我，这明显与我的测试相反，所以来这里反馈，寻求解决办法。

**Comment by leosam1024** [comment]
tongji.baidu.com 是当做广告 被屏蔽的。 是否删掉该条屏蔽，请关注近期提交记录，或者自己fork一下本项目，修改一下。

第二个，这个得看你那边的需求的了，你可以把他加入代理列表，也可以加入直连列表。需要你自己修改了。
这些小众网站，我一般都是支持走兜底代理的。并不会添加

**Comment by pudding1111** [comment]
谢老哥解惑，看到老哥在弄网易云的代理，分享我正在用的规则
 - DOMAIN-SUFFIX,music.126.net,🎯 全球直连
 - DOMAIN-SUFFIX,music.163.com,🎵 网易云解锁
 - DOMAIN-SUFFIX,api.iplay.163.com,🎵 网易云解锁
 - DOMAIN-SUFFIX,mam.netease.com,🎵 网易云解锁
 - DOMAIN-SUFFIX,hz.netease.com,🎵 网易云解锁
 - DOMAIN,api.iplay.163.com,🎵 网易云解锁
 - DOMAIN,apm3.music.163.com,🎵 网易云解锁
 - DOMAIN,apm.music.163.com,🎵 网易云解锁
 - DOMAIN,interface3.music.163.com,🎵 网易云解锁
 - DOMAIN,interface.music.163.com,🎵 网易云解锁
 - DOMAIN,music.163.com,🎵 网易云解锁
 - IP-CIDR,39.105.63.80/32,🎵 网易云解锁
 - IP-CIDR,45.254.48.1/32,🎵 网易云解锁
 - IP-CIDR,47.100.127.239/32,🎵 网易云解锁
 - IP-CIDR,59.111.160.195/32,🎵 网易云解锁
 - IP-CIDR,59.111.160.197/32,🎵 网易云解锁
 - IP-CIDR,59.111.181.35/32,🎵 网易云解锁
 - IP-CIDR,59.111.181.38/32,🎵 网易云解锁
 - IP-CIDR,59.111.181.60/32,🎵 网易云解锁
 - IP-CIDR,101.71.154.241/32,🎵 网易云解锁
 - IP-CIDR,103.126.92.132/32,🎵 网易云解锁
 - IP-CIDR,103.126.92.133/32,🎵 网易云解锁
 - IP-CIDR,112.13.119.17/32,🎵 网易云解锁
 - IP-CIDR,112.13.122.1/32,🎵 网易云解锁
 - IP-CIDR,115.236.118.33/32,🎵 网易云解锁
 - IP-CIDR,115.236.121.1/32,🎵 网易云解锁
 - IP-CIDR,118.24.63.156/32,🎵 网易云解锁
 - IP-CIDR,193.112.159.225/32,🎵 网易云解锁
 - IP-CIDR,223.252.199.66/32,🎵 网易云解锁
 - IP-CIDR,223.252.199.67/32,🎵 网易云解锁
 - DOMAIN,admusicpic.music.126.net,🛑 广告拦截
 - DOMAIN,iadmat.nosdn.127.net,🛑 广告拦截
 - DOMAIN,iadmusicmat.music.126.net,🛑 广告拦截
 - DOMAIN,iadmusicmatvideo.music.126.net,🛑 广告拦截

**Comment by pudding1111** [comment]
分享我在用的网易云规则
 - DOMAIN-SUFFIX,music.126.net,🌏 国内媒体
 - DOMAIN-SUFFIX,music.163.com,🎵 网易云解锁
 - DOMAIN-SUFFIX,api.iplay.163.com,🎵 网易云解锁
 - DOMAIN-SUFFIX,mam.netease.com,🎵 网易云解锁
 - DOMAIN-SUFFIX,hz.netease.com,🎵 网易云解锁
 - DOMAIN,api.iplay.163.com,🎵 网易云解锁
 - DOMAIN,apm3.music.163.com,🎵 网易云解锁
 - DOMAIN,apm.music.163.com,🎵 网易云解锁
 - DOMAIN,interface3.music.163.com,🎵 网易云解锁
 - DOMAIN,interface.music.163.com,🎵 网易云解锁
 - DOMAIN,music.163.com,🎵 网易云解锁
 - IP-CIDR,39.105.63.80/32,🎵 网易云解锁
 - IP-CIDR,45.254.48.1/32,🎵 网易云解锁
 - IP-CIDR,47.100.127.239/32,🎵 网易云解锁
 - IP-CIDR,59.111.160.195/32,🎵 网易云解锁
 - IP-CIDR,59.111.160.197/32,🎵 网易云解锁
 - IP-CIDR,59.111.181.35/32,🎵 网易云解锁
 - IP-CIDR,59.111.181.38/32,🎵 网易云解锁
 - IP-CIDR,59.111.181.60/32,🎵 网易云解锁
 - IP-CIDR,101.71.154.241/32,🎵 网易云解锁
 - IP-CIDR,103.126.92.132/32,🎵 网易云解锁
 - IP-CIDR,103.126.92.133/32,🎵 网易云解锁
 - IP-CIDR,112.13.119.17/32,🎵 网易云解锁
 - IP-CIDR,112.13.122.1/32,🎵 网易云解锁
 - IP-CIDR,115.236.118.33/32,🎵 网易云解锁
 - IP-CIDR,115.236.121.1/32,🎵 网易云解锁
 - IP-CIDR,118.24.63.156/32,🎵 网易云解锁
 - IP-CIDR,193.112.159.225/32,🎵 网易云解锁
 - IP-CIDR,223.252.199.66/32,🎵 网易云解锁
 - IP-CIDR,223.252.199.67/32,🎵 网易云解锁
 - DOMAIN,admusicpic.music.126.net,🌏 国内媒体
 - DOMAIN,iadmat.nosdn.127.net,🌏 国内媒体
 - DOMAIN,iadmusicmat.music.126.net,🌏 国内媒体
 - DOMAIN,iadmusicmatvideo.music.126.net,🌏 国内媒体
 这个规则能用但是手机端用qq登录会显示网络错误，所以需要登录后用代理。

**Comment by leosam1024** [comment]
已经有关于网易云音乐的碎片了。自己可以定制自己的规则

**Comment by pudding1111** [comment]
但是总存在一些问题。

**Comment by leosam1024** [comment]
并没发现什么区别啊

**Comment by pudding1111** [comment]
所以我两都出现了一些问题，
这个规则能用但是手机端用qq登录会显示网络错误，所以需要登录后用代理，同时我也使用老哥更新的网易云规则，发现也会出现网络错误的情况。
其次，clash代理网易云在电脑端和手机端速度延迟也不一样，电脑端非常快，手机端非常慢。

**Comment by leosam1024** [comment]
🎵 网易云解锁 这些位置往上挪，挪到 能最先匹配到位置

**Comment by pudding1111** [comment]
网易云这个位置原本就是是rules的第一行，老哥能登录吗？？

**Comment by leosam1024** [comment]
我不用这个 。我用的是我tg频道里面的 nodejs版的 网易云解锁的
