### ISSUE TITLE
nga论坛帖子打不开

### ISSUE THREAD

**Issue by LiGithubYu** [ACL4SSR/ACL4SSR#349]
RT 论坛里直接点帖子显示空白 刷新一下就正常显示了
![1](https://user-images.githubusercontent.com/48920551/80899251-b27a3c00-8d40-11ea-9d29-d1ce780ef9a9.png)
![2](https://user-images.githubusercontent.com/48920551/80899253-b4dc9600-8d40-11ea-95da-5ece23998582.png)

**Comment by BROBIRD** [comment]
你是如何判断这个和本项目有关的呢？是否有日志？

**Comment by LiGithubYu** [comment]
> 你是如何判断这个和本项目有关的呢？是否有日志？

我把代理关了就能顺利打开啊 clash换其他的托管也可以

**Comment by LiGithubYu** [comment]
奇怪 把代理模式切成direct再切回rule莫名其妙好了 啥时候再次出现我再反馈吧。。。

**Comment by LiGithubYu** [comment]
![Snipaste_2020-05-03_17-59-57](https://user-images.githubusercontent.com/48920551/80911300-064c4b80-8d68-11ea-82db-6e5d2a6f91c0.png)
ctrl+f5又白了 logs里只有这么两个东西

**Comment by leosam1024** [comment]
我这边正常打开啊。你那个被拦截的那几个。是广告域名、

**Comment by LiGithubYu** [comment]
> 我这边正常打开啊。你那个被拦截的那几个。是广告域名、

可能是哪个js被一起拦截了 改成直连后有了缓存就能正常打开 ctrl+f5强制刷新后又不行了 最奇妙的是 正常进入和白板时拦截信息时一样的 很迷。。。

**Comment by leosam1024** [comment]
应该是拦截不够完全，有残余的广告js啥的。
你浏览器装个abp去广告插件试试。

**Comment by LiGithubYu** [comment]
> 应该是拦截不够完全，有残余的广告js啥的。
> 你浏览器装个abp去广告插件试试。

装了uBlock的

**Comment by leosam1024** [comment]
那就不清楚了。可以在浏览该网站的时候，将clash的去广告。暂时改为直连。或者使用别的规则。

**Comment by leosam1024** [comment]
178.com 添加强制直连了。后期可以观察一下。应该没啥问题了

**Comment by nailongzhenren** [comment]
5.7刚更新完规则后，使用nga客户端仍会有这个现象，偶尔会卡加载，怀疑是nga的客户端自身问题。有时直连也会卡加载，电信宽带  119.29.29.29 DNS

**Comment by leosam1024** [comment]
后续你有答案的话，可以进行反馈修改意见。
