### ISSUE TITLE
DNS污染问题

### ISSUE THREAD

**Issue by cnzgray** [ACL4SSR/ACL4SSR#35]
通过读ss-local的代码发现ACL的规则是：
如果地址是域名的，判断是否在域名的黑(白)名单中，如果在则直接代理访问，否则则通过本机的dns服务器查询ip地址，然后查询ip是否在黑(白)名单，如果在则代理访问。

这里也就发生了dns污染问题。目前的dns污染我尝试发现114的、腾讯的和阿里的dns服务器都会被污染。这就使得解决dns污染是一个首要问题。不然就只能一直维护被墙的域名列表了。

**Comment by BROBIRD** [comment]
没明白您的意思……

**Comment by BROBIRD** [comment]
如果您没有其他补充的说明，稍后我们将关闭此issue

**Comment by BROBIRD** [comment]
如果强制要全部走远程DNS的话，就有新的问题：国内的网站可能访问出现问题（如淘宝），因为很多人不喜欢开分应用代理的……

**Comment by cnzgray** [comment]
是这样的，所以目前这个问题其实提麻烦的。
因此我最近也在考虑这个问题，目前来说比较稳妥的做法一种是使用chinadns，另一种就是维护一些被投毒的地址。基本维护比较常用的就够了。

也就是白名单默认是代理+中国ip直连+被投毒域名。

其实我也在死了另一个问题：目前gfwlist就是维护那些被墙的域名，如果**默认代理+中国ip直连+gfwlist**是否有这样的必要。

这种方式和默认直连+gfwlist还是有差别的。
1. 对于默认代理主要是考虑一些地址通过代理进行加速访问，如github。
2. 中国ip直连是让中国地址不走代理
3. gfwlist解决dns投毒问题

基于这个策略个人认为有值得讨论的地方。

**Comment by BROBIRD** [comment]
确实值得讨论……是不是有必要加入gfwlist的部分

**Comment by BROBIRD** [comment]
已经添加了Top blocked sites列表
