### ISSUE TITLE
有几个能直连的网站，建议从漏网之鱼里改为全球直连

### ISSUE THREAD

**Issue by nailongzhenren** [ACL4SSR/ACL4SSR#350]
v2ex.com
www.carrotchou.blog
v2aky.com

**Comment by leosam1024** [comment]
这个服务器是在国外。
国内经常访问不佳。所以最好加入代理吧

**Comment by nailongzhenren** [comment]
> 这个服务器是在国外。
> 国内经常访问不佳。所以最好加入代理吧

v2aky.com 服务器是在国内的，代理访问每次都会有人机验证，有点烦。
v2ex.com和www.carrotchou.blog服务器虽然是在国外，但国内访问正常，移动、联通、电信均测试过，直连没问题。

**Comment by leosam1024** [comment]
v2aky.com 是机场，不会添加到规则里面的

v2ex.com 这个因为你这边访问很正常，但是很多地方，访问不了的。

carrotchou 萝卜的这个 是一个小众网站，没必要给他加入列表。

总体来说。规则里面，直连或者搭理要求，网址是大家常用。那些不常用的，就直接走兜底代理吧。

**Comment by chuang-zhi** [comment]
胡萝卜周博客最近移动无法访问了，要换域名qwq
