### ISSUE TITLE
增加几个开发人员经常下载Docker 镜像大文件的境外域名加速

### ISSUE THREAD

**Issue by gumutianqi** [ACL4SSR/ACL4SSR#351]
```
# Docker Download
hub.docker.com
download.docker.com
gcr.io
k8s.gcr.io
quay.io
access.redhat.com
elastic.com
docker.elastic.co
artifacts.elastic.co
gitlab.com
charts.gitlab.io
raw.githubusercontent.com

# Maven download
maven.apache.org
search.maven.org
repo1.maven.org
repo2.maven.org
repo3.maven.org
oss.sonatype.org
jitpack.io

## Tech Blog
stackoverflow.com
spring.io
spring.net
reddit.com
medium.com
```

**Comment by leosam1024** [comment]
这些不应该都是走兜底代理了吗。 应该不用加吧

**Comment by gumutianqi** [comment]
@leosam1024 有一些并没有，比如artifacts.elastic.co，国内也能访问，龟速，SSR切换到ACL 没有改善，换上全局模式，下载直接到 10MB/s 的速度，这个现象是不是说明 ACL 规则没有匹配到。
还有download.docker.com也是一样

**Comment by gumutianqi** [comment]
@leosam1024 给个地址你测试下，https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-darwin-x86_64.tar.gz

**Comment by leosam1024** [comment]
![image](https://user-images.githubusercontent.com/19237423/81251665-6a1b9080-9056-11ea-93ca-5c2fb512fe52.png)

我这边还行 。走了兜底的。

我想想吧 怎么弄比较好

**Comment by gumutianqi** [comment]
兜底是怎么走？
你这个用的什么工具检测的，学习一下，我好把平时用到比较慢的都测试下

**Comment by leosam1024** [comment]
我这个用的不是ssr 使用的clashr  具体的 可以到我的tg频道里去下载

https://t.me/ACL4SSR/231

**Comment by gumutianqi** [comment]
好的，我是 macOS，用 ClashX玩玩儿试试

**Comment by leosam1024** [comment]
ok 我已经添加了 一个额外部分
Developer 开发者常用国外网站、镜像和论坛

**Comment by gumutianqi** [comment]
@leosam1024 SSR 的订阅地址转换不能用了，这个转换 API 失效了 https://bianyuan.xyz/，你是怎么玩儿的，求赐教

**Comment by leosam1024** [comment]
在线订阅转换：https://acl4ssr.netlify.com

**Comment by gumutianqi** [comment]
ClashXR果然是最佳停机坪，不过还要使用摸索下

新增ACL漏网之鱼：sourcegraph.com:443

**Comment by gumutianqi** [comment]
ACL 规则已经更新生效了，效率 👍 ，测试正常了

**Comment by gumutianqi** [comment]
用了这个本地 convert 服务，相当好用
> https://github.com/ne1llee/v2ray2clash

**Comment by leosam1024** [comment]
多多关注我tg或者相关项目
现在已经是subconverter的天下了
https://github.com/tindy2013/subconverter/blob/master/README-cn.md

**Comment by gumutianqi** [comment]
soga 👍 果断换，已经用上了
subconverter 要是提供一个 macOS homebrew service 就完美了
另外还可以提供 docker image 版本

**Comment by gumutianqi** [comment]
![image](https://user-images.githubusercontent.com/1057589/81268269-52560380-907a-11ea-922d-8617bc72505e.png)


我发现这个 subconverter 的节点选择只有自动啊，Proxy Match最终是路由到自动选择还是全球直连来着，但是就没有找到手动选择节点的地方

**Comment by gumutianqi** [comment]
搞定了，原来要转换成 ClashR 的格式，完美 👍

**Comment by leosam1024** [comment]
你说的 都有。 
可以去https://t.me/subconverter_discuss 看看

docker镜像啥的。 自定义配置 过滤 各种的 都支持
