### ISSUE TITLE
请求添加spark邮箱的规则

### ISSUE THREAD

**Issue by OCD0711** [ACL4SSR/ACL4SSR#352]
如题..spark邮箱无法登陆

**Comment by leosam1024** [comment]
有具体的 网址列表吗

**Comment by OCD0711** [comment]
com.readdle.spark
api.amplitude.com:443
spark的邮箱好像用的google cloud..看surfboard里面有些被拦截了

**Comment by OCD0711** [comment]
> 有具体的 网址列表吗

api.amplitude.com:443
com.readdle.spark
spark的账号服务用的google cloud好像是,surfboard里看有些请求直接被reject了

**Comment by leosam1024** [comment]
已经修复
