### ISSUE TITLE
请问这些规则ios的 Trojan能用嘛

### ISSUE THREAD

**Issue by PPPPzzz** [ACL4SSR/ACL4SSR#355]
~~~

**Comment by leosam1024** [comment]
可以
https://acl4ssr.netlify.app/
自己选择要转换的软件和配置就行

**Comment by PPPPzzz** [comment]
谢谢大佬~~  请问如果要自己精通这类 是要学计算机网络嘛？  我下学期就可以选方向了

**Comment by leosam1024** [comment]
对的。网络io交互，等你工作年限越久，越会觉得这个重要，如果你是走web方向的话

**Comment by PPPPzzz** [comment]
好的 再次感谢
