### ISSUE TITLE
ip138.com切换到全球直连

### ISSUE THREAD

**Issue by IDarkBoss** [ACL4SSR/ACL4SSR#357]
解析了一下`ip138.com`的ip，看起来都是位于中国的。
应该可以把规则放到全球直连里？

**Comment by leosam1024** [comment]
故意的，用来查看代理后的ip的

**Comment by IDarkBoss** [comment]
懂了
![image](https://user-images.githubusercontent.com/26338127/81467703-18693680-920d-11ea-8ac6-92863586bba9.png)
