### ISSUE TITLE
免费 DNS 域名服务 xip.io 被漏过

### ISSUE THREAD

**Issue by gumutianqi** [ACL4SSR/ACL4SSR#359]
首先 `xip.io` 是一个应用非常广泛的 provides wildcard DNS，
```
Using xip.io,
          10.0.0.1.xip.io   resolves to   10.0.0.1
      www.192.168.1.2.xip.io   resolves to   192.168.1.2
   mysite.10.0.0.1.xip.io   resolves to   10.0.0.1
  foo.bar.10.0.0.1.xip.io   resolves to   10.0.0.1
```

开发者在服务端启动 http 服务，通过 `*.<IP>.xip.io` 便可以解析到服务器的 IP，服务器通过 nginx 识别 domain 进行端口转发，就实现了通过免费域名访问服务器了。

这个 `xip.io` 应该配置为强制直连才行。不然成为漏网之鱼之后，会被路由到外网去。

或者， `xip.io` 路由到Proxy，`*.xip.io` 直连

**Comment by leosam1024** [comment]
已经添加
