### ISSUE TITLE
请将cdn供应商cloudflare加入代理

### ISSUE THREAD

**Issue by ikelvingo** [ACL4SSR/ACL4SSR#36]
请将cdn供应商cloudflare加入代理。
当然，可以考虑将所有国外的cdn供应商均加入代理。因为目前部分国外cdn供应商的部分服务器均在gfw的block名单中，即使不在，直连速度也非常不理想。

**Comment by BROBIRD** [comment]
具体是哪个规则，访问什么网页出现的问题，请说明

**Comment by ikelvingo** [comment]
访问theinitium.com的内容，该网站内容通过clouflare加速，但是应该有部分cdn服务器被gfw封锁，因此如果直连则有时可以访问，有时长时间加载，如果通过代理则访问速度正常。
theinitium.com本身是可以正常访问的。

**Comment by BROBIRD** [comment]
老哥……这家用的是cloudfront……
这种CDN干扰有的时候根据网络环境的不同会有很大差异，因此个例我们暂时不考虑添加，您可以自行fork并修改作为个人使用。
