### ISSUE TITLE
HKMTMedia规则

### ISSUE THREAD

**Issue by shenlaizhibi** [ACL4SSR/ACL4SSR#360]
国内媒体(HKMTMedia)节点选台湾 bilibili app 台湾地区资源看不了,但是网页端bilibili能看。
请问能添加个app端规则吗？

**Comment by leosam1024** [comment]
app 应该是用的ip地址啥的，这个没办法搜集。你可以收集一下 我可以合并进来

**Comment by shenlaizhibi** [comment]
> app应该是用的ip地址啥的，这个没办法搜集。你可以收集一下我可以合并进来

小弟不才，是个小白。请问有最新版的clashr for android吗？

**Comment by shenlaizhibi** [comment]
我正在找关于媒体app的规则集，等我找到了再发表，也请看到的广大群众帮忙找找，小弟不胜感激🙏
