### ISSUE TITLE
请求添加 migucloud.com 为国内媒体

### ISSUE THREAD

**Issue by xiaoguoyi** [ACL4SSR/ACL4SSR#361]

**Comment by leosam1024** [comment]
为啥要加这个？说一下理由最好
国内媒体这个分组是为了给划分国内外版权的视频网站用的？

**Comment by xiaoguoyi** [comment]
> 为啥要加这个？说一下理由最好
> 国内媒体这个分组是为了给划分国内外版权的视频网站用的？

嗷，那我描述错了，是加入ChinaDomain里面，这个是咪咕的直播，应该走国内直连的

**Comment by leosam1024** [comment]
已经添加
