### ISSUE TITLE
ACL4SSR_Online_Full.ini 书写询问

### ISSUE THREAD

**Issue by shenlaizhibi** [ACL4SSR/ACL4SSR#362]
求https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Full.ini 中第27行开头有；书写是否正确？

ACL4SSR_Online_Full_AdblockPlus.ini也是同样的问题。
因本人小白，所以不懂，请大神赐教!

**Comment by leosam1024** [comment]
;是注释的意思 并不生效。会自动跳过的，可以删掉

**Comment by shenlaizhibi** [comment]
> ;是注释的意思不是很有效力。会自动跳过的，可以删除



> ;是注释的意思 并不生效。会自动跳过的，可以删掉

正好那条是直连规则（增强中国IP段的名单），请问如果让它生效就把；去掉就行了吗？😃

**Comment by shenlaizhibi** [comment]
> ;是注释的意思不是很有效力。会自动跳过的，可以删除



> ;是注释的意思 并不生效。会自动跳过的，可以删掉



> ;是注释的意思 并不生效。会自动跳过的，可以删掉

正好那条是直连规则（增强中国IP段的名单），请问如果让它生效就把；去掉就行了吗？😃

**Comment by shenlaizhibi** [comment]
> ;是注释的意思 并不生效。会自动跳过的，可以删掉

正好那条是直连规则（增强中国IP段的名单），请问如果让它生效就把；去掉就行了吗？😃

**Comment by leosam1024** [comment]
对 但是没啥必要

**Comment by shenlaizhibi** [comment]
> 对 但是没啥必要

哦，谢谢大神。请大神推荐个clash规则呗，我看规则太多了，不知道选哪个好😊
