### ISSUE TITLE
怎么让B站走自己的分组而不是直连list？（API转换订阅填写远程配置）

### ISSUE THREAD

**Issue by SakuraAaneru** [ACL4SSR/ACL4SSR#368]
如题，直连list里面有b站的域名，在配置文件里B站碎片规则顺位是高于直连的，以及文末也填写了enable_rule_generator=true和overwrite_original_rules=true，但是无论如何日志里B站都是direct，我看配置仓库里好像也没有讲这种情况应该怎么写，那么应该如何实现这一功能？

**Comment by leosam1024** [comment]
往前放！放倒所有直连前面

**Comment by SakuraAaneru** [comment]
> 往前放！放倒所有直连前面

感谢回复，是这样的，我仅仅是在原来的基础上改成了lhie1佬做的后端地址哔哩哔哩分组就可以正常使用了，现在的问题是网易云音乐分组还无法使用（已在设置里勾选使用http代理），我上传了一份我现在正在使用的配置文件，可否请您帮我勘误一下，谢谢。

**Comment by leosam1024** [comment]
DIRECT,rules/ACL4SSR/Clash/ChinaCompanyIp  少了文件list后缀


网易云音乐分组 你那么写 明显不是靠支持网易云解锁内核解锁的 需要一个支持网易云解锁的代理服务器。

可以本机建立 或者 找网上现成的

**Comment by SakuraAaneru** [comment]
> DIRECT,rules/ACL4SSR/Clash/ChinaCompanyIp 少了文件list后缀
> 
> 网易云音乐分组 你那么写 明显不是靠支持网易云解锁内核解锁的 需要一个支持网易云解锁的代理服务器。
> 
> 可以本机建立 或者 找网上现成的

好的，这个明白了，另外问一下就是在移动端CFA（Kr328）上面（CFW暂时未发现这种情况）加了您Help文档推荐的BanAD＋BanProgramAD＋BanEasyListChina或者Hijacking+Reject这两种屏蔽广告的规则组合之后，带有广告的App，比如B站，Nga，Youtube等有时候会直接失去响应（但是用不带去广告规则的订阅就不会出现该情况）想问一下这种情况是属于您所说的可能带有副作用的情况吗？还是说是CFA的问题？

**Comment by leosam1024** [comment]
对的，这些如果产生误拦截的话
3种改法
把广告拦截那个改成直连。
广告屏蔽不要都加上 按需屏蔽。
你自己看日志，找出误拦截的网址，反馈一下，我们给你修复一下。
我自己用的看天天看b站，没怎么发现问题
