### ISSUE TITLE
远程配置节点分组的问题

### ISSUE THREAD

**Issue by 4512369781** [ACL4SSR/ACL4SSR#369]
我用的日本的节点里只有一个“日”字，而配置里的规则是

> custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP)`http://www.gstatic.com/generate_204`300

这就导致日本节点下面为空，望能修改下，不然每次更新后都要手动修改。

**Comment by BROBIRD** [comment]
就一个字的话条件太少了，容易误匹配。暂时应该不会考虑修改

**Comment by 4512369781** [comment]
> 就一个字的话条件太少了，容易误匹配。暂时应该不会考虑修改

但我注意到其他节点的关键字匹配都有单字，比如“美”、“坡”，这些节点就没有误匹配的影响吗？

**Comment by BROBIRD** [comment]
@4512369781 我个人认为“日”这个字作为“天”这个含义有可能出现在节点说明中，比如“单日xxx”，所以考虑维持现状

**Comment by 4512369781** [comment]
> @4512369781 我个人认为“日”这个字作为“天”这个含义有可能出现在节点说明中，比如“单日xxx”，所以考虑维持现状

其实出现这种误匹配也没什么问题吧，节点分组也都是自动测速的，不会选中这个只为了显示信息的说明。
相对来说，对于节点里只有“日1”关键字的来说，肯定利大于弊。

**Comment by BROBIRD** [comment]
@leosam1024 你怎么看？

**Comment by leosam1024** [comment]
已经修了

**Comment by 4512369781** [comment]
> 已经修了

感谢，但是还是有问题，“[^-]日”无法匹配“日”字在首位的情况，还麻烦再修改下。

**Comment by leosam1024** [comment]
我抄subconverter的，以他为主

**Comment by 4512369781** [comment]
> 我抄subconverter的，以他为主

好吧。
