### ISSUE TITLE
腾讯云dnspod域名IP规则添加

### ISSUE THREAD

**Issue by ileeoyo** [ACL4SSR/ACL4SSR#37]
dnspod提供了doh服务，域名是doh.pub，解析的ip是1.12.12.12。

目前ChinaDomain规则和ChinaIp规则都没有规则能匹配，导致最后走了Clash默认的Match规则（我设置默认走代理）。导致doh请求每次走代理延迟很大，很影响网页加载速度。

请求在ChinaDomain增加doh.pub，或者ChinaIp中增加1.12.12.12

**Comment by acl4ssr-sub** [comment]
修复
