### ISSUE TITLE
全分组规则下，网飞节点只有DIRECT一个选项

### ISSUE THREAD

**Issue by chashaodan** [ACL4SSR/ACL4SSR#373]
ACL4SSR_Online_Full_AdblockPlus 全分组 重度用户使用 更多去广告 (与Github同步) 

我使用这个规则在线转换了订阅，大概因为我的机场没有在节点名里包含网飞相关关键词，所以转换出来这个Proxy Group只有DRECET。可是谁会在非回国规则里用直连看网飞啊，希望修改一下加上Selector。

**Comment by leosam1024** [comment]
🎥 奈飞视频`select`[]🎥 奈飞节点`[]🔰 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 手动切换`[]DIRECT

这么多呢 好不?

**Comment by Yinghai75** [comment]
我也是这样，虽然可以为奈飞策略组选择别的节点项，但是如果能自己定义一下奈飞节点的规则就更好了
