### ISSUE TITLE
远程配置中全球直连的连接方式

### ISSUE THREAD

**Issue by zhongwangninja** [ACL4SSR/ACL4SSR#374]
请问是否可以考虑在 https://acl4ssr.netlify.app/ ACL4SSR_Online 的远程配置中，针对“全球直连”添加诸如“自动选择”、“节点选择”的连接方式，现下只有 Direct 一种方式。

- 如果某个直连的网站加入了 GFW 或者出现国内访问延迟的情况，希望走代理
- 全球直连的网站是写在配置文件的，修改并不方便
- 个人感觉成本比较低的方式就是临时修改下全球直连的连接方式，实现全局代理，用完后再改回来

现在“ACL4SSR_Online_Full_AdblockPlus 全分组 重度用户使用 更多去广告”的远程配置中，“全球直连”支持选择代理，但是这个配置分组比较繁杂。所以想把这个推广到其他的配置中，方便使用简洁配置走全局代理。

全球直连分组现有连接方式如下：
![image](https://user-images.githubusercontent.com/1947059/82738635-b0b5fe00-9d6b-11ea-86a5-78416a1d21d0.png)

想请开发组考虑一下的方式如下：
![image](https://user-images.githubusercontent.com/1947059/82738670-f4106c80-9d6b-11ea-8b8b-5ec0fdbab0a1.png)

**Comment by leosam1024** [comment]
全部添加
