### ISSUE TITLE
【Clash】国内网盘 *.115.com 会被抓进漏网之鱼,可否改为直连?

### ISSUE THREAD

**Issue by Shiinakuro** [ACL4SSR/ACL4SSR#377]
使用115网盘挂机下载,起床发现代理流量被吃完了.
Log发现*.115.com都会走漏网之鱼代理,国内网盘应该不需要走代理吧,可否移出漏网之鱼?
谢谢

**Comment by leosam1024** [comment]
晚上回去把115加入直连吧
我们都是走的geo ip 直连，你可以更新一下ip库 先看看

**Comment by leosam1024** [comment]
已经添加
