### ISSUE TITLE
V2ray可以用吗，求大佬

### ISSUE THREAD

**Issue by Columba2017** [ACL4SSR/ACL4SSR#378]
v2ray怎么用啊，是直接复制所有内容粘贴进去吗

**Comment by BROBIRD** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by leosam1024** [comment]
不支持，json格式太复杂了。不适合当acl用
