### ISSUE TITLE
是否有必要制作跨区的 apple 相关域名 rule？

### ISSUE THREAD

**Issue by gth7754125** [ACL4SSR/ACL4SSR#379]
apple 相关的域名如果是对应国内的 apple 服务的话可以直接使用，
然而如果使用了香港或日本地区的 apple 服务的话，相关域名 rule 可能失效。
例如：itunes的日区，若相关链接直接连接，会无法显示界面。
这些还能自己修改，但是像 cdn 的话不清楚能否直连，能否提供双版本的 apple.list以供参考？

**Comment by leosam2048** [comment]
不用苹果，所以也没测试条件。
如果你有搜集的话，可以在这个issue里贴上。
我看情况制作一下

**Comment by gth7754125** [comment]
试着下设置了一部分使用proxy，另一部分保留直连。但是apple music的页面，图片，和串流十分缓慢。。估计是日区的部分域名没有被墙 。但是cdn相关的地址应该是跟国内分开的。所以只能统一设置成代理模式进行访问。
