### ISSUE TITLE
黑名单gfwlist-banAD规则，把小米浏览器自带的新闻过滤了

### ISSUE THREAD

**Issue by stonereese** [ACL4SSR/ACL4SSR#38]
RT，请问，小米自带浏览器新闻能看标题，打不开，这个可以免除过滤么？谢谢~

**Comment by BROBIRD** [comment]
额……没有小米设备，请问能提供一下具体的域名吗……

**Comment by leosam1995** [comment]
恩，是的。我把小米的新闻作为广告了，等抽空打开吧

**Comment by stonereese** [comment]
我看到最新的更新日志，已经解除了对小米浏览器新闻的屏蔽，感谢您的辛苦付出！目前发现还是有大部分新闻打不开，选了几个网址，供您参考
我分享了【出错啦！】, 快来看吧！@小米浏览器 | http://mb.yidianzixun.com/article/0HH96yxE?s=mb&appid=mibrowser&ref=browser_news
http://mb.yidianzixun.com/article/0HHqZ6x3?s=mb&appid=mibrowser&ref=browser_news
http://mb.yidianzixun.com/article/0HI1nP7a?s=mb&ref=hft3ohew
http://mb.yidianzixun.com/article/0HI0fS3S?s=mb&ref=hft3ohew
如果不方便修改或者会对其他规则造成影响，您可以无视此条反馈，一切以您方便为主，再次感谢您为此做出的努力和贡献。

**Comment by stonereese** [comment]
我又测试了一下，上面这些网址用uc打开正常，小米浏览器我清理了缓存、cookies数据也是不行，天知道小米浏览器在后台搞了什么鬼造成的，或许您完全不用考虑这个反馈了。
