### ISSUE TITLE
使用BanProgramAD.list后WPS iOS版部分图片无法加载

### ISSUE THREAD

**Issue by lcysyx** [ACL4SSR/ACL4SSR#380]
系统版本：iOS 13.5
代理软件：Quantumult X v1.0.9-build276
WPS版本：iOS版 v10.10.0
使用规则：BanProgramAD.list
问题：WPS iOS版部分图片无法加载，如“应用”，“我-签到”，以及“我-WPS云服务”（最后这个的截图没截到，关闭了规则后就加载出来了，重启APP后加载的图片也还是在）
截图如下：
![IMG_7442](https://user-images.githubusercontent.com/15268822/83794070-ff4e8b00-a6cf-11ea-9cd8-d2c8d1cfa43e.PNG)
![IMG_7441](https://user-images.githubusercontent.com/15268822/83794054-fc539a80-a6cf-11ea-9e68-605efd7f4907.PNG)

**Comment by leosam2048** [comment]
能看一下屏蔽日志吗？
看看是不是dl.op.wapcdn.cn

**Comment by lcysyx** [comment]
“应用”和“我-WPS云服务”里的图片我已经加载出来了，重启APP图片也还是在所以测试不了，需要找个没装WPS的设备试试，我文件比较多不太方便重装测试。
“我-签到”的测试日志如下图，我进一步试了关掉BanProgramAD.list，手动添加pcfg.wps.cn，图片加载没问题，改为手动添加dl.op.wapcdn.cn图片就加载不出来了，因此应该就是dl.op.wapcdn.cn的问题。
![IMG_7446](https://user-images.githubusercontent.com/15268822/83852682-bd146080-a746-11ea-8f1b-3522ab979ef6.PNG)

**Comment by leosam2048** [comment]
已经修了
