### ISSUE TITLE
有没有办法添加自定义配置或者自己修改的配置不受更新影响

### ISSUE THREAD

**Issue by kettly1260** [ACL4SSR/ACL4SSR#382]
因为自己用的某些节点不支持谷歌学术，谷歌学术之能用特定节点访问，所以自己添加了一个可自主选择的分组专门留给谷歌学术选择。但是每次配置自动更新后自己添加的配置都会被覆盖，如果不更新的话，订阅的节点的变动自己又收不到。不知道这种问题有没有办法解决啊

**Comment by leosam2048** [comment]
简单 ，自己在git上新建个项目，项目建个碎片和配置规则
碎片内部是你的规则。 配置的话，把你碎片的url往上放。
剩下的规则走我的。
这样我这边更新了，你也能收到，节点也一样。而且因为你自己的规则放在前面，优先级更高。

**Comment by kettly1260** [comment]
> 简单 ，自己在git上新建个项目，项目建个碎片和配置规则
> 碎片内部是你的规则。 配置的话，把你碎片的url往上放。
> 剩下的规则走我的。
> 这样我这边更新了，你也能收到，节点也一样。而且因为你自己的规则放在前面，优先级更高。

不是，很懂。意思是建一个list碎片和一个ini配置文件是吗？
那这样的话跟新填的INI就变成我自己的项目了吧？那这样的话还可以用那个订阅网页生成订阅链接吗

**Comment by leosam2048** [comment]
恩 可以啊 配置那一栏 填你自己的raw网址就行

**Comment by kettly1260** [comment]
> 恩 可以啊 配置那一栏 填你自己的raw网址就行

不知道是哪里弄错了，按照这个配置更新好像没办法更新成自己想要的配置，可以帮我看一下吗
https://github.com/kettly1260/clash-scholar.google/blob/master/config/ACL4SSR_Online_scholar_google.ini

**Comment by xie0027** [comment]
按你的方法试过了 配置那一栏无法输入

**Comment by leosam2048** [comment]
https://raw.githubusercontent.com/kettly1260/clash-scholar.google/master/scholar_google.list

**Comment by kettly1260** [comment]
> 填 raw类型的地址
> 
> 配置：
> https://raw.githubusercontent.com/kettly1260/clash-scholar.google/master/config/ACL4SSR_Online_scholar_google.ini
> 
> 规则:
> https://raw.githubusercontent.com/kettly1260/clash-scholar.google/master/scholar_google.list

原来是这样。解决了，谢谢
