### ISSUE TITLE
想问下定制功能里面的网易云有什么作用？

### ISSUE THREAD

**Issue by xie0027** [ACL4SSR/ACL4SSR#383]
试了下 勾选与不勾选 完全没区别

**Comment by leosam2048** [comment]
这个是给有解锁服务器用的

**Comment by xie0027** [comment]
我有服务器  我现在是手动添加rule和节点  就是每次更新完又要修改  就很麻烦  今天看到有个网易云选项就想问问怎么用

**Comment by leosam2048** [comment]
这个得添加额外节点 、订阅节点哪里、具体的查看对应后端文档
