### ISSUE TITLE
在线转换有考虑出API提供

### ISSUE THREAD

**Issue by ccssyybb** [ACL4SSR/ACL4SSR#387]
路由CLASH使用，想做一个在线订阅连接转换的，为了转换需要在路由后台搭建后端的话有点复杂的样子。

**Comment by leosam2048** [comment]
多看看readme啊
官方文档：https://github.com/tindy2013/subconverter/blob/master/README-cn.md
ACL4SSR：提供的https://acl4ssr.netlify.com/
