### ISSUE TITLE
请问acl怎么在ssr win端使用

### ISSUE THREAD

**Issue by zhanggang9920** [ACL4SSR/ACL4SSR#388]
发现win端 代理规则可以选择用户自定义
也找到一位写规则的  但是这位作者的规则大概有2000行？   https://github.com/pcysanji/ssr4p
远远不如作者的8000+ 所以想用作者的acl 
但是好像不能直接吧acl文件发到根目录使用？？
一直在安卓端使用
体验很好
也准备在win端使用

**Comment by BROBIRD** [comment]
@zhanggang9920 user.rule已经停止更新了，如果坚持要在Windows上使用，建议使用clashR

**Comment by zhanggang9920** [comment]
> @ zhanggang9920 user.rule已经停止更新了，如果坚持要在Windows上使用，建议使用clashR

感谢 0.0
