### ISSUE TITLE
对于重度用户全分组的建议

### ISSUE THREAD

**Issue by cskz008** [ACL4SSR/ACL4SSR#389]
可不可以吧auto从全分组中撤销？或者是额外的无auto的全分组，有些鸡c设置同时在线设备不能超过5个或者10个，然而全分组里的自动测速，导致一打开cfa，就开始自动测速，直接超过在线可用设备数，达到15，16这个样子，然后导致鸡c对用户限制使用，就很麻烦，希望可以把全分组中的auto删除或者另创无auto的全分组，谢谢

全分组真的太有用了

**Comment by leosam2048** [comment]
恩 加上了
