### ISSUE TITLE
请问YouTube的广告以前能去的，现在怎么去不掉了

### ISSUE THREAD

**Issue by alexalice** [ACL4SSR/ACL4SSR#39]
恳请开发者大大及时更新，顺便告知哪个线路的YouTube广告可以去除，以前是部分香港线路的YouTube广告可以去除

**Comment by BROBIRD** [comment]
在我这里似乎Youtube一直有广告。。。您确定之前能去广告？

2017年9月15日 01:31，"alexalice" <notifications@github.com>写道：

**Comment by alexalice** [comment]
是的，之前YouTube用香港线路的时候能去掉广告

**Comment by alexalice** [comment]
手机端的，电脑我有插件去广告

**Comment by BROBIRD** [comment]
问了下leosam，他之前尝试抓过，但是广告域名与普通视频域名是同样的，所以没办法屏蔽。
