### ISSUE TITLE
关于重度用户分组的新问题

### ISSUE THREAD

**Issue by cskz008** [ACL4SSR/ACL4SSR#390]
抱歉，可能是我没有表述完整，不仅是前面的auto组，还有后面的各国分类组别，也需要把自动测速去掉，换成可以用户手动切换的，主要截图中的港台狮日美这五组，它们会自动开始测试速度导致在线设备飙增，所以希望可以把下面这5组的自动测速也去掉，换成用户手动切换，谢谢
![QQ截图](https://user-images.githubusercontent.com/63418154/84665680-b52c9b80-af52-11ea-8fb8-c81e17f47c57.png)
![QQ截图2020](https://user-images.githubusercontent.com/63418154/84665723-c2498a80-af52-11ea-898c-ebbca584d352.png)

**Comment by leosam2048** [comment]
恩 好了
