### ISSUE TITLE
使用规则后，qq接不通电话

### ISSUE THREAD

**Issue by shangshanyue** [ACL4SSR/ACL4SSR#394]
规则是这个：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/banAD.acl
安卓10。
劳心你了。

**Comment by BROBIRD** [comment]
哪个规则？交通规则？有没有日志？什么平台？
建议提问前先阅读
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
