### ISSUE TITLE
Clash的新参数可能未修改成功

### ISSUE THREAD

**Issue by cskz008** [ACL4SSR/ACL4SSR#399]
用机场提供的订阅链接可以直接订阅出来，但是在您的订阅转换这里，clash作为源，转换clash，远端配置使用Maying却可以订阅出节点，而全分组无自动测速和全分组更多去广告，都不能成功订阅出节点，仅订阅出规则，请问这是怎么回事？
![1](https://user-images.githubusercontent.com/63418154/85954338-409c2880-b966-11ea-9f54-57ea75620563.png)
![2](https://user-images.githubusercontent.com/63418154/85954341-41cd5580-b966-11ea-935f-df7ac3821432.png)
![3](https://user-images.githubusercontent.com/63418154/85954390-8a850e80-b966-11ea-9f9b-5b72dffe2069.png)
![4](https://user-images.githubusercontent.com/63418154/85954428-d637b800-b966-11ea-9b92-e19dc21502fe.png)

**Comment by leosam2048** [comment]
你再试试，应该好了

**Comment by cskz008** [comment]
> 你再试试，应该好了

OK了
