### ISSUE TITLE
IOS端ChatGPT域名分流没有添加到openai策略组

### ISSUE THREAD

**Issue by kiko923** [ACL4SSR/ACL4SSR#40]
5.19新出的ios版本的chatgpt域名没有在openai的规则里面 他的域名是ios.chat.openai.com 导致分流的是直连 然后ios用这个软件的时候 gpt会连接失败 一直转圈 本人在规则里面手动匹配了这个域名并指向openai策略组后 成功连通 希望能把这个域名加进openai.list里面 谢谢

**Comment by kiko923** [comment]
我的匹配规则如下：
- DOMAIN,ios.chat.openai,💬 OpenAi
希望作者审核后添加进openai的list 谢谢

**Comment by kiko923** [comment]
我还发现 ios端的ChatGPT不仅单纯只是需要把ios.chat.openai.com添加进策略组 因为我测试了 划掉后台 重新进去 又不行了 于是我抓包发现 他是先走了另外几个域名post了一些用户参数 返回之后才会去走ios.chat.openai.com 这是我加的新策略 亲测划掉后台后不会失效
![IMG_0510](https://github.com/ACL4SSR/ACL4SSR/assets/75443014/51f43402-837b-4733-97e8-1695da62a8f8)

我在OpenWrt里面的openclash加的自定义规则如下：
![N3{}8OUOXT $9VE ~`~)55M](https://github.com/ACL4SSR/ACL4SSR/assets/75443014/2c89fc55-06f9-47e1-adb5-34efaaa2bf46)

亲测成功 麻烦作者审核后加入openai策略组 因为好像是必须同ip访问 所以加入其他代理策略组的话 我怕会出错 于是建议加入相同的openai策略组

- DOMAIN,ios.chat.openai,💬 OpenAi
- DOMAIN-KEYWORD,datadoghq,💬 OpenAi
- DOMAIN-KEYWORD,revenuecat,💬 OpenAi
- DOMAIN-KEYWORD,sentry,💬 OpenAi

**Comment by W1nd** [comment]
请问你iOS用的是哪个客户端，小火箭吗？

**Comment by kiko923** [comment]
我用的是ChatGPT 家里软路由连的

**Comment by W1nd** [comment]
好的，不好意思我发现我的问题有歧义。我用小火箭开的科学上网分流的，直接用ios端的chatpgpt没啥问题呢

**Comment by kiko923** [comment]
你没发现我说的是openclash的分流规则么 跟小火箭什么关系

**Comment by W1nd** [comment]
都是代理客户端，小火箭也同样可以分流

**Comment by kiko923** [comment]
你是听不懂吗 你小火箭用openclash的分流？ 我没说我小火箭用不了啊 我说的是我openclash啊 别一来就显得你很懂似的 答非所问

**Comment by W1nd** [comment]
那我这样说吧，我用了clash的客户端（Stash、Pharos都是支持clash的ios客户端）也是可以用的，你最好看看是不是你Openclash插件的问题，Openclash我也用过，会有固件与插件产品冲突的时候导致Openclash无法正常使用，这样总不是答非所问了吧

**Comment by Mythologyli** [comment]
`ios.chat.openai.com` 不是本来就能匹配到吗

```
# 内容：OpenAi
# 数量：6条
DOMAIN-KEYWORD,openai
DOMAIN-SUFFIX,ai.com
DOMAIN-SUFFIX,challenges.cloudflare.com
DOMAIN-SUFFIX,openai.com
DOMAIN-SUFFIX,openaiapi-site.azureedge.net
DOMAIN-SUFFIX,stripe.com
```

<img width="336" alt="image" src="https://github.com/ACL4SSR/ACL4SSR/assets/15955880/8ae76c20-521c-4a7f-82e7-7880929b5736">

sentry 那几个确实要加一下

**Comment by yujun8888** [comment]
如何加入小火箭啊，大佬，iPhone ai gpt 要全局才行
不知道怎么加入策略组，谢谢
