### ISSUE TITLE
请问自己可不可以添加屏蔽的网址链接？

### ISSUE THREAD

**Issue by alexalice** [ACL4SSR/ACL4SSR#40]
如何添加呢

**Comment by leosam1995** [comment]
fork一下本项目，然后就可以在自己项目内添加就行 
或者进行pull request 
直接发网址，觉得合适也可以给你们添加上

**Comment by alexalice** [comment]
呃。。。就是javbus.com上那些广告，能去除吗，emmmmm

**Comment by BROBIRD** [comment]
PC访问的话，浏览器装个uBlock Origin或者ADBlock Plus
手机访问的话，能否请您用wiki上的方法尝试抓取一下广告域名？谢谢！
