### ISSUE TITLE
订阅的问题

### ISSUE THREAD

**Issue by QuteSaltyFish** [ACL4SSR/ACL4SSR#400]
1. 我的trojan的订阅一定要手动设定 skip-cert-verify: true才能用。。不知道是机场问题还是什么问题。
2. full的设定对与youtube的分流好像不太好
![photo_2020-06-29_19-04-47](https://user-images.githubusercontent.com/41997780/85996927-6e06d600-ba3b-11ea-85b3-e6a6102d831b.jpg)
最终的视频流量走的是默认节点，很迷……

**Comment by BROBIRD** [comment]
skip-cert-verify 有可能是你的机场用的是自签名证书……

**Comment by BROBIRD** [comment]
#404
