### ISSUE TITLE
关于trojan节点的订阅转换问题

### ISSUE THREAD

**Issue by yuerongz97** [ACL4SSR/ACL4SSR#404]
由于我的trojan节点增加了中转，所以必须选择跳过验证这个选项，也就是clash配置文件中的skip-cert-verify选项，但是通过trojan链接生成的clash配置文件并没有那一选项，导致无法连接

例：输入链接：trojan://mypassword@www.trojan.xyz:10010?allowInsecure=1#My-trojan-name

配置文件转换输出：
proxies:
  - {name: My-trojan-name, server: www.trojan.xyz, port: 10010, type: trojan, password: mypassword, sni: www.trojan.xyz}

理应得到的值：
  - {name: My-trojan-name, server: www.trojan.xyz, port: 10010, type: trojan, password: mypassword, sni: www.trojan.xyz, skip-cert-verify: true}

**Comment by BROBIRD** [comment]
@yuerongz97 加scv=false参数了吗

**Comment by yuerongz97** [comment]
> @yuerongz97 加scv=false参数了吗

谢大佬，我加了scv=true后就可以使用了，不过请问有没有针对单个节点的方法呢？

**Comment by BROBIRD** [comment]
@yuerongz97 这个功能是由subconverter提供的，你问一下作者，因为我本身不用trojan，所以我也不太清楚

**Comment by yuerongz97** [comment]
> @yuerongz97 这个功能是由subconverter提供的，你问一下作者，因为我本身不用trojan，所以我也不太清楚

好的 谢大佬
