### ISSUE TITLE
[规则]bilibiliPC端用这个list可以访问港澳台，移动端已经不行了，但是加了日志里几个直连域名没有用，希望大佬解决一下

### ISSUE THREAD

**Issue by MinaseInori233** [ACL4SSR/ACL4SSR#405]
RTRTRT

**Comment by leosam2048** [comment]
你自己看一下日志，看看拿一些漏了 我个人不用移动端看B站

**Comment by MinaseInori233** [comment]
> 你自己看一下日志，看看拿一些漏了 我个人不用移动端看B站

多的是无类别域间路由，不知道怎么添加这种
[b港澳台.txt](https://github.com/ACL4SSR/ACL4SSR/files/4872189/b.txt)

**Comment by leosam2048** [comment]
现在只抓了这个
bigfunapp.cn
bigfun.cn

可以在设置-》网络-》仅允许b站打开 再抓一下，要不太乱了

**Comment by MinaseInori233** [comment]
> 现在只抓了这个
> bigfunapp.cn
> bigfun.cn
> 
> 可以在设置-》网络-》仅允许b站打开 再抓一下，要不太乱了

解决了 就是upos-hz-mirrorakam.akamaized.net这个DOMAIN，话说另外就是要解决API转换里的字数限制的话只能自己搭一个吗？

**Comment by leosam2048** [comment]
恩 是的 或者多试试别的后端地址 可能有不限制的

**Comment by JessYi228** [comment]
大佬，我更新了这三条规则以后还是不行😂，移动端还是提示无法播放

**Comment by JessYi228** [comment]
大佬，我更新了这三条规则以后移动端还是提示无法播放
