### ISSUE TITLE
0704维护版本地Subconverter还是0.5.2版本

### ISSUE THREAD

**Issue by FanyangMengDev** [ACL4SSR/ACL4SSR#408]
如题，请检查一下

**Comment by leosam2048** [comment]
是6.0的 重新下载一下吧

**Comment by FanyangMengDev** [comment]
@leosam2048 

请看下列截图，不论是在线订阅转换还是最新本地版0704都是0.5.2，我重新下载了3遍了。。。
![image](https://user-images.githubusercontent.com/53750381/86504540-1b873a00-bdec-11ea-9b0b-8ec6f5c04d5e.png)
![image](https://user-images.githubusercontent.com/53750381/86504545-26da6580-bdec-11ea-9480-f9e217419ef2.png)

**Comment by FanyangMengDev** [comment]
会不会是Sub-Web本身出现的版本号读取错误？

**Comment by leosam2048** [comment]
这个版本号，不是取的本地的，看看就行，前端懒得改
本地的确实是0.6的

**Comment by FanyangMengDev** [comment]
好的，非常感谢

**Comment by leosam2048** [comment]
http://localhost:25500/ 打开会看到0.6

**Comment by FanyangMengDev** [comment]
好嘞，明白，非常感谢您~
