### ISSUE TITLE
无论是白名单还是黑名单,淘宝应用都走的代理

### ISSUE THREAD

**Issue by zzw6776** [ACL4SSR/ACL4SSR#41]
如题,也没拿其他app测试,就用淘宝测试,安卓机
如果用ssrr自带的绕过局域网及国内地址,淘宝正常
如果用自定义acl(白名单,或者黑名单)进淘宝都会走代理导致很慢很慢

**Comment by leosam1995** [comment]
这个是因为你用的服务端的dns解析的，淘宝的ip会解析到国外的服务器，所以会很卡。
推荐你使用最新的SSR版本 （最新版的SSR已经修复这个问题了）
或者使用分应用代理

**Comment by zzw6776** [comment]
我用的最新ssr呀,地址如下:https://github.com/shadowsocksrr/shadowsocksr-android/releases

**Comment by leosam1995** [comment]
我这里测试没问题啊，没有走代理啊，你尝试一下 改一下DNS 或者分应用代理吧。

**Comment by BROBIRD** [comment]
是你自己设置的问题，如果真的如你所说有这种错误，怎么可能留到现在还没解决

2017年9月19日 15:53，"leosam1995" <notifications@github.com>写道：

**Comment by zzw6776** [comment]
蛋疼,算了 懒得折腾了  ssr的分应用代理也有问题,在用分应用代理的情况下它的路由规则有时候会失效

**Comment by zzw6776** [comment]
我没改设置呀,都是默认的,你们用的ssr是哪个版本,我用你们的版本试试

**Comment by BROBIRD** [comment]
如果你不介意的话 把敏感信息打个码 配置打出来看看

2017年9月19日 16:02，"ZZW" <notifications@github.com>写道：

**Comment by zzw6776** [comment]
![screenshot_20170919-160425](https://user-images.githubusercontent.com/14048998/30581897-5960151a-9d54-11e7-80a8-0fa797265387.jpg)

**Comment by BROBIRD** [comment]
你根本没开分应用代理啊

2017年9月19日 16:05，"ZZW" <notifications@github.com>写道：

**Comment by zzw6776** [comment]
是没开呀,我说的就是没开的情况下淘宝也不该走代理啊,因为acl默认直连的话,淘宝ip又不是国外ip

**Comment by leosam1995** [comment]
不啊 淘宝在日本美国好多个服务器的 
你尝试清除dns吧
以前我淘宝也有这个问题
跟作者反馈过，然后后来就修复了

**Comment by zzw6776** [comment]
你们用的ssr是啥版本,发个链接我试试

**Comment by NeveRossa** [comment]
3.3.7.1

**Comment by BROBIRD** [comment]
3.4.0.7

2017年9月19日 16:13，"NeveRossa" <notifications@github.com>写道：

**Comment by zzw6776** [comment]
醉了 换成3.4.0.7就可以了,就是客户端的问题
