### ISSUE TITLE
订阅规则建议

### ISSUE THREAD

**Issue by QuteSaltyFish** [ACL4SSR/ACL4SSR#411]
建议吧loadbalance加入各种套餐里面，这个东西感觉还蛮好用的！只放在mini里面感觉太少了，想看youtube就感觉不太够了，可以放在all里面给每一个国家节点放一个loadbalance。顺便建议all里面增加游戏节点的类型，订阅中有备注为游戏的节点（或者把iplc，iepl，cn2线路等单独分类也不错）

**Comment by leosam2048** [comment]
为啥我觉的贼难用，天天断流
你可以自己fork本项目，加个配置文件，碎片引用我的就行
