### ISSUE TITLE
YouTube是如何判断地区的？

### ISSUE THREAD

**Issue by LzNOHentai** [ACL4SSR/ACL4SSR#412]
将YouTube、YouTube Music、Google三个list组合成一个group并指定走日本节点，地区仍然被判断为指定给境外地址默认分流的香港，只有把境外地址默认分流的节点也改为日本，才能成功识别到日本区域。

**Comment by leosam2048** [comment]
额 自己试验试验吧 我并不对此很了解

**Comment by BROBIRD** [comment]
Youtube不是自己在设置里选择的地区吗？

**Comment by LzNOHentai** [comment]
> Youtube不是自己在设置里选择的地区吗？

那个地区设置估计就影响推荐和广告这种东西，开了地区限制的频道和视频一样看不了。

**Comment by BROBIRD** [comment]
可能需要分析日志才能知道通过什么方式获得地区信息，你可以试一下抓取日志，看一下是否有相关域名走了默认代理节点。
