### ISSUE TITLE
web界面上传配置文件限制

### ISSUE THREAD

**Issue by QuteSaltyFish** [ACL4SSR/ACL4SSR#415]
你好！我想问一下这个上传配置文件的限制能不能放大，我想改一改full放进去，但是被3000个字数限制了不好用

**Comment by BROBIRD** [comment]
看了一下前端的源码，这个限制应该是后端做的，你可以换其他后端试试。

**Comment by BROBIRD** [comment]
刚才看错了= =前端限制了最大长度，请 @leosam2048 修改一下

**Comment by leosam2048** [comment]
我改了。1万字符长度
