### ISSUE TITLE
建议删除ProxyGFWlist内的m-team条目

### ISSUE THREAD

**Issue by breezelol** [ACL4SSR/ACL4SSR#417]

**Comment by leosam2048** [comment]
?理由呢

**Comment by breezelol** [comment]
1、ChinaDomain内同样有m-team条目，订阅到yaml文件内就是同一个域名同时设置了代理和直连规则，记得最后是走的代理规则。
2、m-team是pt站，列在代理列表的话很可能会导致站点判定seedbox，下载也会走代理会触碰规则、大量消耗流量。
望采纳

**Comment by leosam2048** [comment]
删了
