### ISSUE TITLE
请添加这几个规则屏蔽YouTube广告

### ISSUE THREAD

**Issue by alexalice** [ACL4SSR/ACL4SSR#42]
// Youtube
^https?://m.youtube.com/_get_ads - reject
^https?://pagead2.googlesyndication.com/pagead/ - reject
^https?://s0.2mdn.net/ads/ - reject
^https?://stats.tubemogul.com/stats/ - reject

^https?://(www.)?g.cn https://www.google.com.hk 302
^https?://(www.)?google.cn https://www.google.com.hk 302
^https?://youtube.com https://www.youtube.com 302

**Comment by leosam1995** [comment]
surge上的规则SSR不支持
SSR只是一个域名的acl 并不是一个网址的acl
