### ISSUE TITLE
电脑版本clash更新v0.11.0后所有规则不能用

### ISSUE THREAD

**Issue by pudding1111** [ACL4SSR/ACL4SSR#420]
clash电脑版本地址https://github.com/Fndroid/clash_for_windows_pkg/releases
具体情况：rule空白，更新显示    - DOMAIN-SUFFIX,acl4ssr,🎯 全球直连   未发现
回退  v 0.10.4  版本正常使用

**Comment by BROBIRD** [comment]
能否提供更详细的信息？比如截图，日志等？

**Comment by pudding1111** [comment]
不需要提供日志，是clash上游更新了

上游 Clash 核心已移除前向兼容代码

包括但不限于

- 不再解析 "Proxy" "Proxy Group" "Rule" 字段 而 使用 "proxies" "proxy-groups" "rules"
- 不再解析 "rule-provider" 而使用 "rule-providers"
- 不再解析 Shadowsocks 协议的 "obfs", "obfs-host" 而 使用 "plugin" "plugin-opts"
- 不再解析 "FINAL" "SOURCE-IP-CIDR" 而 使用 "MATCH" "SRC-IP-CIDR"

Clash for Android 会为该变更保留 2个月 的前向兼容 各位 用户 及 提供商 尽快适配新的配置文件规范

参见 commit
 - 2781090
 - e57a13e

**Comment by leosam2048** [comment]
转换的时候 默认的ClashR新参数 就可以啊

**Comment by pudding1111** [comment]
一直用的是clash参数，这就去试试clashr的参数

**Comment by BROBIRD** [comment]
@pudding1111 重点是新参数，而不是R……

**Comment by pudding1111** [comment]
了解，更新后神清气爽，一直以为clashr是给酸酸用的
