### ISSUE TITLE
频道中CFW的subconverter自带的pref-acl4ssr.yml存在错误

### ISSUE THREAD

**Issue by zhongfly** [ACL4SSR/ACL4SSR#422]
rulesets部分引入了多余的规则snippets/rulesets.txt（第87行），有规则指向了不存在的proxy group“国内媒体”，而导致clash无法使用生成的配置文件

`  - {import: snippets/rulesets.txt}`
应改为
`#  - {import: snippets/rulesets.txt}`

**Comment by leosam2048** [comment]
恩 改了
