### ISSUE TITLE
建议把小米家的万能遥控和微信公众号的广告增加到拦截列表中

### ISSUE THREAD

**Issue by lolipoi** [ACL4SSR/ACL4SSR#425]
原来的神机规则都能做得到，可惜现在那位大佬弃坑了。而且我也找不到是哪条规则起的作用
![](https://ftp.bmp.ovh/imgs/2020/07/402bd005546dd288.png)

**Comment by lolipoi** [comment]
[Rule]
[Rule]
# DNS
IP-CIDR,1.1.1.1/32,PROXY
IP-CIDR,1.0.0.1/32,PROXY
IP-CIDR,8.8.8.8/32,PROXY
IP-CIDR,8.8.4.4/32,PROXY
IP-CIDR,9.9.9.9/32,PROXY
IP-CIDR,149.112.112.112/32,PROXY
IP-CIDR,208.67.222.222/32,PROXY
IP-CIDR,208.67.220.220/32,PROXY

# Unbreak
# > General
USER-AGENT,coffeecorp*,DIRECT
USER-AGENT,restaurant-mobile*,DIRECT
DOMAIN,app.adjust.com,DIRECT
# > Google
DOMAIN-SUFFIX,googletraveladservices.com,DIRECT
DOMAIN,analyticsinsights-pa.googleapis.com,PROXY
DOMAIN,analyticsreporting.googleapis.com,PROXY
DOMAIN,dl.google.com,DIRECT
DOMAIN,mtalk.google.com,DIRECT
# > Tencent
DOMAIN,livew.l.qq.com,DIRECT
DOMAIN,vd.l.qq.com,DIRECT
# > Strava
DOMAIN,analytics.strava.com,DIRECT

# Advertising 广告
# > General
DOMAIN-KEYWORD,adservice,REJECT

DOMAIN-SUFFIX,adcolony.com,REJECT
DOMAIN-SUFFIX,adinall.com,REJECT
DOMAIN-SUFFIX,admaster.com.cn,REJECT
DOMAIN-SUFFIX,admob.com,REJECT
DOMAIN-SUFFIX,adnxs.com,REJECT
DOMAIN-SUFFIX,adnyg.com,REJECT
DOMAIN-SUFFIX,adsensor.org,REJECT
DOMAIN-SUFFIX,adsymptotic.com,REJECT
DOMAIN-SUFFIX,adthor.com,REJECT
DOMAIN-SUFFIX,adwhirl.com,REJECT
DOMAIN-SUFFIX,amazon-adsystem.com,REJECT
DOMAIN-SUFFIX,amobee.com,REJECT
DOMAIN-SUFFIX,app-adforce.jp,REJECT
DOMAIN-SUFFIX,appads.com,REJECT
DOMAIN-SUFFIX,appcpi.net,REJECT
DOMAIN-SUFFIX,appier.net,REJECT
DOMAIN-SUFFIX,applift.com,REJECT
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT
DOMAIN-SUFFIX,apsalar.com,REJECT
DOMAIN-SUFFIX,apxadtracking.net,REJECT
DOMAIN-SUFFIX,axonix.com,REJECT
DOMAIN-SUFFIX,bayimob.com,REJECT
DOMAIN-SUFFIX,bjvvqu.cn,REJECT
DOMAIN-SUFFIX,bulldogcpi.com,REJECT
DOMAIN-SUFFIX,clotfun.mobi,REJECT
DOMAIN-SUFFIX,clotfun.online,REJECT
DOMAIN-SUFFIX,cloudmobi.net,REJECT
DOMAIN-SUFFIX,crwdcntrl.net,REJECT
DOMAIN-SUFFIX,ctrmi.com,REJECT
DOMAIN-SUFFIX,exosrv.com,REJECT
DOMAIN-SUFFIX,go2cloud.org,REJECT
DOMAIN-SUFFIX,growingio.com,REJECT
DOMAIN-SUFFIX,haloapps.com,REJECT
DOMAIN-SUFFIX,hypers.com,REJECT
DOMAIN-SUFFIX,idealads.net,REJECT
DOMAIN-SUFFIX,inmobi.cn,REJECT
DOMAIN-SUFFIX,inmobi.com,REJECT
DOMAIN-SUFFIX,inmobi.net,REJECT
DOMAIN-SUFFIX,inmobicdn.cn,REJECT
DOMAIN-SUFFIX,inmobicdn.net,REJECT
DOMAIN-SUFFIX,inner-active.mobi,REJECT
DOMAIN-SUFFIX,insurads.com,REJECT
DOMAIN-SUFFIX,ironsrc.com,REJECT
DOMAIN-SUFFIX,irs01.com,REJECT
DOMAIN-SUFFIX,iskyworker.com,REJECT
DOMAIN-SUFFIX,juicyads.com,REJECT
DOMAIN-SUFFIX,kochava.com,REJECT
DOMAIN-SUFFIX,leadboltmobile.net,REJECT
DOMAIN-SUFFIX,lenzmx.com,REJECT
DOMAIN-SUFFIX,liveadvert.com,REJECT
DOMAIN-SUFFIX,lnk0.com,REJECT
DOMAIN-SUFFIX,lnk8.cn,REJECT
DOMAIN-SUFFIX,localytics.com,REJECT
DOMAIN-SUFFIX,mdfull.com,REJECT
DOMAIN-SUFFIX,measurementapi.com,REJECT
DOMAIN-SUFFIX,medialytics.com,REJECT
DOMAIN-SUFFIX,meetrics.com,REJECT
DOMAIN-SUFFIX,meetrics.net,REJECT
DOMAIN-SUFFIX,miaozhen.com,REJECT
DOMAIN-SUFFIX,mmstat.com,REJECT
DOMAIN-SUFFIX,moatads.com,REJECT
DOMAIN-SUFFIX,mobclix.com,REJECT
DOMAIN-SUFFIX,mopub.com,REJECT
DOMAIN-SUFFIX,okjhb.xyz,REJECT
DOMAIN-SUFFIX,openx.net,REJECT
DOMAIN-SUFFIX,outbrain.com,REJECT
DOMAIN-SUFFIX,pubmatic.com,REJECT
DOMAIN-SUFFIX,qchannel01.cn,REJECT
DOMAIN-SUFFIX,rayjump.com,REJECT
DOMAIN-SUFFIX,rtbasia.com,REJECT
DOMAIN-SUFFIX,rubiconproject.com,REJECT
DOMAIN-SUFFIX,scorecardresearch.com,REJECT
DOMAIN-SUFFIX,sdkclick.com,REJECT
DOMAIN-SUFFIX,shuzilm.cn,REJECT
DOMAIN-SUFFIX,smaato.net,REJECT
DOMAIN-SUFFIX,smartadserver.com,REJECT
DOMAIN-SUFFIX,smartnews-ads.com,REJECT
DOMAIN-SUFFIX,supersonic.com,REJECT
DOMAIN-SUFFIX,supersonicads.com,REJECT
DOMAIN-SUFFIX,tagtic.cn,REJECT
DOMAIN-SUFFIX,tanv.com,REJECT
DOMAIN-SUFFIX,tanx.com,REJECT
DOMAIN-SUFFIX,tapjoy.com,REJECT
DOMAIN-SUFFIX,trafficjunky.net,REJECT
DOMAIN-SUFFIX,turn.com,REJECT
DOMAIN-SUFFIX,uri6.com,REJECT
DOMAIN-SUFFIX,vidoomy.com,REJECT
DOMAIN-SUFFIX,vungle.com,REJECT
DOMAIN-SUFFIX,wedolook.com,REJECT
DOMAIN-SUFFIX,xdrig.com,REJECT
DOMAIN-SUFFIX,yumimobi.com,REJECT
DOMAIN-SUFFIX,zu08e.cn,REJECT

DOMAIN-SUFFIX,ad.cmvideo.cn,REJECT
DOMAIN-SUFFIX,ad.daum.net,REJECT
DOMAIN,abema-adx.ameba.jp,REJECT
DOMAIN,ad.12306.cn,REJECT
DOMAIN,ad.360in.com,REJECT
DOMAIN,ad.51wnl-cq.com,REJECT
DOMAIN,ad.caiyunapp.com,REJECT
DOMAIN,ad.huajiao.com,REJECT
DOMAIN,ad.hzyoka.com,REJECT
DOMAIN,ad.jiemian.com,REJECT
DOMAIN,ad.qingting.fm,REJECT
DOMAIN,ad.wappalyzer.com,REJECT
DOMAIN,ad-cn.jovcloud.com,REJECT
DOMAIN,adextra.51wnl-cq.com,REJECT
DOMAIN,api.adnet.mob.com,REJECT
DOMAIN,ads.adadapted.com,REJECT
DOMAIN,ads.chinadaily.com.cn,REJECT
DOMAIN,ads.daydaycook.com.cn,REJECT
DOMAIN,ads.weilitoutiao.net,REJECT
DOMAIN,adsapi.manhuaren.com,REJECT
DOMAIN,adsdk.dmzj.com,REJECT
DOMAIN,adserver.pandora.com,REJECT
DOMAIN,adshow.58.com,REJECT
DOMAIN,adui.tg.meitu.com,REJECT
DOMAIN,adv.bandi.so,REJECT
DOMAIN,app-ad.variflight.com,REJECT
DOMAIN,appnext.hs.llnwd.net,REJECT
DOMAIN,appnext-a.akamaihd.net,REJECT
DOMAIN,ggs.myzaker.com,REJECT
DOMAIN,itad.linetv.tw,REJECT
DOMAIN,ja.chushou.tv,REJECT
DOMAIN,mads.suning.com,REJECT
DOMAIN,mobileads.msn.com,REJECT
DOMAIN,mopnativeadv.037201.com,REJECT
DOMAIN,nativeadv.dftoutiao.com,REJECT

# (0~9)
# > 58 同城
# (A)
# > Apple
DOMAIN-SUFFIX,iadsdk.apple.com,REJECT
DOMAIN-SUFFIX,ads.internal.unity3d.com,REJECT
DOMAIN-SUFFIX,ads.prd.ie.internal.unity3d.com,REJECT
DOMAIN-SUFFIX,unityads.unity3d.com,REJECT
# > Alibaba
DOMAIN,optimus-ads.amap.com,REJECT
DOMAIN,optimus-ads.amap.com.w.alikunlun.com,REJECT
DOMAIN,tunion-api.m.taobao.com,REJECT
# > AutoHome
DOMAIN,adproxy.autohome.com.cn,REJECT
DOMAIN,rd.autohome.com.cn,REJECT
DOMAIN,al.autohome.com.cn,REJECT
DOMAIN,applogapi.autohome.com.cn,REJECT
# (B)
# > Baidu
DOMAIN-SUFFIX,cpro.baidu.com,REJECT
DOMAIN-SUFFIX,pos.baidu.com,REJECT
DOMAIN,afd.baidu.com,REJECT
DOMAIN,als.baidu.com,REJECT
DOMAIN,duclick.baidu.com,REJECT
DOMAIN,mobads.baidu.com,REJECT
DOMAIN,mobads-logs.baidu.com,REJECT
DOMAIN,nsclick.baidu.com,REJECT
# > ByteDance
DOMAIN,ad.toutiao.com,REJECT
# > BitAuto
DOMAIN,adx.yiche.com,REJECT
DOMAIN,log.ycapp.yiche.com,REJECT
# > 百词斩
DOMAIN,advertise.baicizhan.com,REJECT
DOMAIN,advertise.baicizhan.org,REJECT
# (C)
# > CNTV
DOMAIN,galaxy.bjcathay.com,REJECT
DOMAIN,mdrecv.app.cntvwb.cn,REJECT
DOMAIN,sdapprecv.app.cntvwb.cn,REJECT
DOMAIN,vdapprecv.app.cntvwb.cn,REJECT
# > ChinaTelecom
DOMAIN,ad.21cn.com,REJECT
DOMAIN,ad.k.21cn.com,REJECT
DOMAIN,admarket.21cn.com,REJECT
DOMAIN,adshows.21cn.com,REJECT
# > 车来了
DOMAIN,atrace.chelaile.net.cn,REJECT
DOMAIN,logs.chelaile.net.cn,REJECT
# (G)
# > Google
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,googleadservices.com,REJECT
DOMAIN-SUFFIX,googleadsserving.cn,REJECT
DOMAIN-SUFFIX,googlesyndication.com,REJECT
# (H)
# > HunanTV
DOMAIN-SUFFIX,da.mgtv.com,REJECT
DOMAIN-SUFFIX,da.hunantv.com,REJECT
# > Hupu
DOMAIN,adx.hupu.com,REJECT
DOMAIN,adx-api.hupu.com,REJECT
DOMAIN,goblin.hupu.com,REJECT
# (I)
# > iQiyi
DOMAIN,t7z.cupid.iqiyi.com,REJECT
IP-CIDR,101.227.97.240/32,REJECT,no-resolve
IP-CIDR,101.227.200.11/32,REJECT,no-resolve
IP-CIDR,101.227.200.28/32,REJECT,no-resolve
IP-CIDR,124.192.153.42/32,REJECT,no-resolve
# > Ifeng
DOMAIN-SUFFIX,deliver.ifeng.com,REJECT
DOMAIN,api.newad.ifeng.com,REJECT
DOMAIN,ifengad.3g.ifeng.com,REJECT
# (K)
# > KuGou and Kuwo
DOMAIN,adserviceretry.kugou.com,REJECT
DOMAIN,ads.service.kugou.com,REJECT
DOMAIN,adsfile.bssdlbig.kugou.com,REJECT
DOMAIN,g.koowo.com,REJECT
DOMAIN,kgmobilestat.kugou.com,REJECT
DOMAIN,kgmobilestatbak.kugou.com,REJECT
DOMAIN,mobilelog.kugou.com,REJECT
DOMAIN,mobilead.kuwo.cn,REJECT
DOMAIN,rich.kuwo.cn,REJECT
# > Kingsoft
DOMAIN,ad-stat.ksosoft.com,REJECT
DOMAIN,img.auction-ads.wpscdn.cn,REJECT
DOMAIN,counter.kingsoft.com,REJECT
DOMAIN,counter.ksosoft.com,REJECT
DOMAIN,minfo.wps.cn,REJECT
DOMAIN,mobad.ijinshan.com,REJECT
DOMAIN,ups.ksmobile.net,REJECT
DOMAIN,ws.ksmobile.net,REJECT
# (L)
# > Le
DOMAIN-SUFFIX,webp2p.letv.com,REJECT
DOMAIN,ark.letv.com,REJECT
DOMAIN,emma-414870e223.huodonghezi.com,REJECT
DOMAIN,g3.letv.com,REJECT
DOMAIN,n.mark.letv.com,REJECT
# > 乐播投屏
DOMAIN,ad.hpplay.cn,REJECT
DOMAIN,adcdn.hpplay.cn,REJECT
DOMAIN,adeng.hpplay.cn,REJECT
DOMAIN,rp.hpplay.cn,REJECT
# (M)
# > MI
DOM

附上一个神机大佬的规则吧，kitsunebi上用体验还行，clash用不了

**Comment by leosam2048** [comment]
我也不知道。自己抓抓日志吧

**Comment by leosam2048** [comment]
差不多加了几个

**Comment by lolipoi** [comment]
> 差不多加了几个

小米万能遥控器的广告域名
cdn.cnbj1.fds.api.mi-img.com
