### ISSUE TITLE
BanProgramAD.list列表中对于淘宝系APP直通车跳转链接的误杀

### ISSUE THREAD

**Issue by LittPigu** [ACL4SSR/ACL4SSR#426]
BanProgramAD.list这个列表里，有一条 DOMAIN-SUFFIX,click.mz.simba.taobao.com
click.mz.simba.taobao.com这个链接为阿里巴巴旗下App直通车跳转链接，如果拦截此域名，会导致点击相关物品的链接无法跳转到淘宝相应的宝贝界面，这个有点严重影响正常使用了。而且这条并不是很讨人厌的广告行为，所以建议放行此域名。

**Comment by leosam2048** [comment]
@LittPigu 已经删除 如果有其他影响使用的请及时提出好做修复
