### ISSUE TITLE
Full全分组中的改进建议

### ISSUE THREAD

**Issue by harnseen** [ACL4SSR/ACL4SSR#429]
#### 以下是正常的电报分组规则：
![](https://i.niupic.com/images/2020/07/20/8r8X.png)
#### 以下是节点选择分组中的重复段：
![](https://i.niupic.com/images/2020/07/20/8r8V.png)
#### 以下几条规则有几率拦截百度的正常访问，建议从应用净化分组中删除
``` 
entry.baidu.com
msite.baidu.com
static.bshare.cn
```
#### 添加Amazonip段后虽然能解决提示代理的问题，但有会造成部分其他网站也走奈飞视频的分组，已知的有Instagram

**Comment by leosam2048** [comment]
1. 重复
 这个是属于不同分组的，有些碎片会有重复，但是他是按顺序匹配的，所以有少许重复无所谓的
2. 百度
 考虑一下，90%会删除
3. 奈飞
 这个真的属于每个人有每个人的用处了，加这个肯定是有副作用的，所以我是推荐实在影响使用了，可以自己自定义一个ini配置

**Comment by harnseen** [comment]
@leosam2048 

![](https://i.niupic.com/images/2020/07/20/8r9B.png)
在没有使用奈飞的情况下，可以看到 **i.instagram.com**  走的是奈飞分组
其实走奈飞的分组倒也没什么，但是**有可能**会导致在使用Instagram的时候，一部分走奈飞视频分组，另一部分走节点选择分组，当两个分组的节点不同时，IG可能会检测出同时有两个ip，根据Facebook严格的条款，会大大增加账号被封的可能性

**Comment by leosam2048** [comment]
恩 已经修了
