### ISSUE TITLE
转换工具

### ISSUE THREAD

**Issue by EDISON-Z** [ACL4SSR/ACL4SSR#43]
您好，请问有没有ACL转Surge或者Shadowrocket的工具呢？

**Comment by leosam1995** [comment]
surge装acl里面有个shortcuts.xml文件。
自己替换到自己到notepad++ 安装目录下 就有了。
自己做的一个宏文件，利用正则转换的。实用性不太强。凑合用用心，批量转换不太现实。
![Alt text](https://ww4.sinaimg.cn/large/0060lm7Tly1fjusjxolu1j307g09qwek.jpg)
