### ISSUE TITLE
希望这些Mini配置也能添加上OpenAi分组

### ISSUE THREAD

**Issue by misakaok** [ACL4SSR/ACL4SSR#43]
由于不是重度用户 全分组的配置用不上 希望能给这些精简过的Mini配置加上OpenAi分组

![CleanShot 2023-06-01 at 09 39 00@2x](https://github.com/ACL4SSR/ACL4SSR/assets/10344793/30480377-3d03-4a1e-8094-3382234d94c5)

**Comment by acl4ssr-sub** [comment]
添加了一个ai分组配置
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online_Mini_Ai.ini
