### ISSUE TITLE
和平精英没法玩了，能进入大厅，不能进入游戏

### ISSUE THREAD

**Issue by bengdan** [ACL4SSR/ACL4SSR#430]
如题

**Comment by leosam2048** [comment]
没日志，咋解决

**Comment by leosam2048** [comment]
算了 既然没发日志，
只能给你建议，分应用代理吧，游戏这类的，大量使用udp协议，对代理这东西，不好兼容

**Comment by BROBIRD** [comment]
@leosam2048 其实主要是因为ss/ssr的Golang版本没有实现UDP

**Comment by bengdan** [comment]
怎么捕获和平精英的日志啊，手机里面的请求杂乱的一批。

**Comment by leosam2048** [comment]
分应用代理吧，
日志，clash里面应该有，但是就算捕获了，也比较难写规则

**Comment by bengdan** [comment]
抓出来了全部是direct的规则，害。

**Comment by bengdan** [comment]
> 分应用代理吧，
> 日志，clash里面应该有，但是就算捕获了，也比较难写规则

我也想分应用，可是我家是路由器clashr

**Comment by leosam2048** [comment]
direct 应该没问题啊，clash应该可以设置，不代理UDP的。具体的得看路由器了，我没用过
