### ISSUE TITLE
广告屏蔽问题

### ISSUE THREAD

**Issue by QuteSaltyFish** [ACL4SSR/ACL4SSR#431]
请问一下使用了fake ip之后就无法进行youtube的广告屏蔽，于是我想问问看有没有什么情况能够把adguardhome的各种广告规则转换成openclash可以用的规则呢

**Comment by leosam2048** [comment]
已经有了啊，就是那些abp的规则，BanEasyList BanEasyListChina BanEasyPrivacy
但是只能屏蔽域名罢了。这个没办法，clash只支持域名级别的屏蔽
