### ISSUE TITLE
订阅转换后clash不能更新订阅，全部显示400

### ISSUE THREAD

**Issue by a8778700** [ACL4SSR/ACL4SSR#433]
[](url)
![TIM截图20200723165503](https://user-images.githubusercontent.com/13430342/88269218-33285300-cd06-11ea-99b0-e0e340b12f1a.png)
这个是机场的原因吗？

**Comment by leosam2048** [comment]
@a8778700 浏览器直接打开转换后的网址，应该是被过滤了 自己看转换接口文档。或者多试试

**Comment by a8778700** [comment]
> 
> 
> @a8778700 浏览器直接打开转换后的网址，应该是被过滤了 自己看转换接口文档。或者多试试

The following link doesn't contain any valid node  浏览器打开是这样的，我看了别的机场能直接在浏览器打开

**Comment by leosam2048** [comment]
@a8778700 自己看看是不是类型选择错了。

**Comment by a8778700** [comment]
应该不是，因为是最近突然不能更新的，之前订阅成功了

**Comment by leosam2048** [comment]
@a8778700 没动过 自己检查吧 或者换个后端服务。具体的你应该去找后端项目提问题，不应在我项目里

**Comment by a8778700** [comment]
小白不是很懂，谢谢你的解答

**Comment by leosam2048** [comment]
@a8778700 可以telegram 进@subconverter_discuss 询问
