### ISSUE TITLE
被 jsdelivr 封了？

### ISSUE THREAD

**Issue by ju0632** [ACL4SSR/ACL4SSR#434]
打开 https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/

显示：User ACL4SSR is blacklisted.

**Comment by leosam2048** [comment]
@ju0632 额 不知道咋封了 可以自己fork一下本项目 用fork后的地址呗

**Comment by walkxspace** [comment]
可以换用 Staticaly 作为镜像
比如 banAD.acl 的镜像地址就是[https://cdn.staticaly.com/gh/ACL4SSR/ACL4SSR/master/banAD.acl](https://cdn.staticaly.com/gh/ACL4SSR/ACL4SSR/master/banAD.acl)

**Comment by gth7754125** [comment]
域名和协议不分大小写，但是后面路径部分可能区分，这个得看 github。结果 github 可能不分的，所以改改小写就能找回来。但是 jsdelivr 如果把你全名统一大小写处理一下再存到 blacklist 里面，那你就得跪了。。
建议多 fork 一下这个项目里面关键的 BanAD/BanEasyList/....China/ProgramAD。

**Comment by BROBIRD** [comment]
@gth7754125 实际上我这几天了解了一下，因为jsdelivr是有国内节点的，所以他们也要考虑国内的监管要求，所以暂时不建议继续用jsdelivr……

**Comment by MinaseInori233** [comment]
> @gth7754125 实际上我这几天了解了一下，因为jsdelivr是有国内节点的，所以他们也要考虑国内的监管要求，所以暂时不建议继续用jsdelivr……

但是有些地区dns污染严重pref.ini里只能用CDN访问，应该怎么解决这个问题？

**Comment by leosam2048** [comment]
@MinaseInori233 jsdelivr你改一下项目名的大小写应该可以，或者市面上 好多github的镜像，或者自己fork一下也行

**Comment by MinaseInori233** [comment]
> @MinaseInori233 jsdelivr你改一下项目名的大小写应该可以，或者市面上 好多github的镜像，或者自己fork一下也行

Staticaly好像不能同步GITHUB的更新，大佬有遇到这种情况吗

**Comment by KhaosChow** [comment]
修改大小写已经没用了
