### ISSUE TITLE
想问下 为什么最近的生成的配置文件里面有bypass？

### ISSUE THREAD

**Issue by xie0027** [ACL4SSR/ACL4SSR#435]
想问下 为什么最近的生成的配置文件里面有bypass？
然后实际测试这个bypass完全不起作用，所以想问下大佬这个应该怎么使用？

**Comment by leosam2048** [comment]
@xie0027 跳过系统代理的，没啥用 不用管就行

**Comment by xie0027** [comment]
那就是说还是以config里面的bypass为准是吧  包括节点排序 打断连接参数 可以这么理解吗？

**Comment by leosam2048** [comment]
@xie0027 恩 对使用没任何影响

**Comment by xie0027** [comment]
好的 谢谢解惑  辛苦大佬了
