### ISSUE TITLE
Quantumult使用在线订阅转换后的链接显示“远程文件中未包含有效对应类型的配置”

### ISSUE THREAD

**Issue by dtpoi** [ACL4SSR/ACL4SSR#437]
已检查源链接为Quantumult配置
转换后使用网页打开检查确认是Quantumult配置
已经尝试了在线转换的5个后端 都是同样的情况
显示“远程文件中未包含有效对应类型的配置”

版本 Quantumult 2.2.13(Build 627)
点开查看动图
[![](https://i.imgur.com/fX5p7oc.png)](https://imgur.com/HTUJfqg)

**Comment by leosam2048** [comment]
@dtpoi @subconverter_discuss 加这个tg 提供订阅 以便检查
