### ISSUE TITLE
v2ray h2 丢失 outbounds.streamSettings.httpSettings.path 值

### ISSUE THREAD

**Issue by zhongwangninja** [ACL4SSR/ACL4SSR#438]
我有一个机场使用的 vmess h2 协议，使用机场原订阅正常工作，使用 https://acl4ssr.netlify.app/ 转换后无法访问外网，对比配置 json 发现唯一的差别在于 outbounds.streamSettings.httpSettings.path 这个值转化后丢失了。怀疑异常和这点相关。

https://acl4ssr.netlify.app/
- 订阅链接：`vmess://eyJwb3J0IjoiNDQzIiwicHMiOiLljp/niYgiLCJ0bHMiOiJ0bHMiLCJpZCI6IjEyMzQ1Njc4LTEyMzQtMTIzNC0xMjM0LTEyMzQ1Njc4OTAxMjMiLCJhaWQiOiIyIiwidiI6IjIiLCJob3N0IjoicnV4eHgueHh4LmNuIiwidHlwZSI6Im5vbmUiLCJwYXRoIjoiXC9kb3dubG9hZCIsIm5ldCI6ImgyIiwiYWRkIjoicnV4eHgueHh4LmNuIn0=`
- 客户端 v2ray
- 远程配置 ACL4SSR_Online 默认版 分组比较全 (与Github同步)
- 后端地址 gfwsb.114514.best(subconverter作者提供1)

转换结果为
- 定制订阅 https://suo.yt/kOKBZzU
- vmess `vmess://eyJwb3J0IjoiNDQzIiwicHMiOiLljp/niYgiLCJ0bHMiOiJ0bHMiLCJpZCI6IjEyMzQ1Njc4LTEyMzQtMTIzNC0xMjM0LTEyMzQ1Njc4OTAxMjMiLCJhaWQiOiIyIiwidiI6IjIiLCJob3N0IjoicnV4eHgueHh4LmNuIiwidHlwZSI6Im5vbmUiLCJwYXRoIjoiIiwibmV0IjoiaDIiLCJhZGQiOiJydXh4eC54eHguY24ifQ==`

对比前后的 json 差异就是 outbounds.streamSettings.httpSettings.path=/downloads 值被忽略了。

> vmess 链接已隐藏节点、id。

**Comment by leosam2048** [comment]
@zhongwangninja 如果订阅转换有问题，转换最好上这里提https://github.com/tindy2013/subconverter/issues

我只能解决有些误拦截之类的问题，规则这类的😂😂

**Comment by zhongwangninja** [comment]
> @zhongwangninja 如果订阅转换有问题，转换最好上这里提https://github.com/tindy2013/subconverter/issues
> 
> 我只能解决有些误拦截之类的问题，规则这类的😂😂

好的，谢谢！辛苦啦
