### ISSUE TITLE
游戏平台steam分流规则

### ISSUE THREAD

**Issue by everypath** [ACL4SSR/ACL4SSR#440]
在游戏平台分组中，steam社区与商店同是在游戏平台中的，导致商店和社区都是同一规则。但无法实现直连商店，代理访问社区。会使得steam客户端访问社区出现错误，只能用浏览器访问社区。希望能将规则改成只代理社区、直连商店

**Comment by leosam2048** [comment]
@everypath # 内容：Steam
# 数量：6条
DOMAIN-SUFFIX,fanatical.com
DOMAIN-SUFFIX,humblebundle.com
DOMAIN-SUFFIX,steam-chat.com
DOMAIN-SUFFIX,steamcommunity.com
DOMAIN-SUFFIX,steampowered.com
DOMAIN-SUFFIX,steamstatic.com    

这些那些你觉得是需要直连的

**Comment by everypath** [comment]
DOMAIN-SUFFIX,fanatical.com
DOMAIN-SUFFIX,humblebundle.com
-------------
这几个直连好像都是OK的可能比较慢，所以可以代理我也赞同

DOMAIN-SUFFIX,steampowered.com这个域名中steam客服support.steampowered.com我觉得代理了会比较快一点
但是store.steampowered.com使用代理连接了，就会出现登陆地满世界乱飘的情况，感觉直连乖乖呆在中国大陆的ip就好了

**Comment by leosam2048** [comment]
别用自动测速IP就不会飘了。steampowered.com我这边直连都打不开。。

**Comment by everypath** [comment]
行吧我临时改下规则。
我这边网络都够惨了，许多酸酸乳节点机场别人都能用就我不行。
那大佬steam不是都注册不了国区了
