### ISSUE TITLE
Amazon.list有一条与github疑似相关的DOMAIN会影响github的下载

### ISSUE THREAD

**Issue by MinaseInori233** [ACL4SSR/ACL4SSR#442]
github-production-release-asset-2e65be.s3.amazonaws.com 

日志里看了一下，这条域名会影响github下载，如果这条域名和github被定向到不同节点的话，下载会一直loading

**Comment by leosam2048** [comment]
？？ 这个本来就是github的cdn啊

**Comment by MinaseInori233** [comment]
> ？？ 这个本来就是github的cdn啊

好吧不是很懂这个cdn，因为我这边github的group和amazon的group用的ip完全不一致

**Comment by leosam2048** [comment]
@MinaseInori233 如果自制的话，github的碎片 放在Amazon的前面就行
