### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by alililala** [ACL4SSR/ACL4SSR#445]
clash更新了，老大麻烦更新一下你的那个集成版哦，TG里边，或者能教一下怎么手动更新吗？主要想要点一下就能更新IP那个功能，其次是集成的那些转换功能。

**Comment by leosam2048** [comment]
@alililala 不更新了 因为都支持SSR了。 我自己还用老版呢

**Comment by alililala** [comment]
> @alililala 不更新了 因为都支持SSR了。 我自己还用老版呢

哦，好吧。
