### ISSUE TITLE
添加anti-AD去广告

### ISSUE THREAD

**Issue by gyj1109** [ACL4SSR/ACL4SSR#447]
能否添加[anti-AD](https://github.com/privacy-protection-tools/anti-AD)去广告？我自己加了一行，但就是用不了，用subconverter生成后就是没有anti-AD的内容。
```
surge_ruleset=🛑 广告拦截,https://anti-ad.net/surge.txt
```
谢谢！

**Comment by leosam2048** [comment]
@gyj1109 这么写是没问题，但是现在转换有最大行数限制。你这个应该是超出限制了。然后转换的时候跳过了

**Comment by gyj1109** [comment]
哦好，谢谢了
