### ISSUE TITLE
可以新增维基百科的规则吗？

### ISSUE THREAD

**Issue by walkxspace** [ACL4SSR/ACL4SSR#448]
因为维基百科编辑的话默认是封禁代理服务器的，需要使用原生IP，因此有这个维基的规则碎片的话就更好了

**Comment by leosam2048** [comment]
@walkxspace 可以考虑加上

**Comment by leosam2048** [comment]
@walkxspace 就一个域名啊，没必要单出一个碎片吧

**Comment by walkxspace** [comment]
@leosam2048 维基基金会的项目不止一个 有百科 词典 文库等等 都是封禁了非原生IP的

**Comment by leosam2048** [comment]
DOMAIN-SUFFIX,wikipedia.org
我proxyList里有啊

**Comment by leosam2048** [comment]
已经添加一个比较全的

**Comment by walkxspace** [comment]
@leosam2048 反馈一下：wikileaks不是维基基金会的项目

**Comment by walkxspace** [comment]
> @leosam2048 反馈一下：wikileaks不是维基基金会的项目

https://zh.wikipedia.org/zh-cn/Wikipedia:%E7%B6%AD%E5%9F%BA%E8%A7%A3%E5%AF%86%E8%88%87%E7%B6%AD%E5%9F%BA%E7%99%BE%E7%A7%91%E7%84%A1%E9%97%9C

**Comment by leosam2048** [comment]
@walkxspace 无所谓了，反正多一条不多
