### ISSUE TITLE
clash使用bing搜索

### ISSUE THREAD

**Issue by VoidXia** [ACL4SSR/ACL4SSR#449]
求问规则要如何设置才能使必应搜索正常打开？
clash配置在树莓派上作为旁路由。
试了好几个规则都无效，具体表现为www.bing.com 及 cn.bing.com的反复重定向，最终抛出重定向过多错误。
clash状态设置成GLOBAL和DIRECT都能够分别正确的打开www.bing.com及cn.bing.com。
理想的状态是bing正常走代理Proxy，使用全球版必应搜索。
想请教各位该如何解决？

**Comment by VoidXia** [comment]
也尝试了将微软域名全部走Proxy，仍然无效。

**Comment by leosam2048** [comment]
@VoidXia 额 我的规则是bing全部走代理的
