### ISSUE TITLE
matlk.google.com走代理

### ISSUE THREAD

**Issue by stp88888** [ACL4SSR/ACL4SSR#45]
matlk.google.com走代理的话，手机上的GCM无法正常工作，希望能改进一下。另外能让pixiv（www.pixiv.net）能走代理么？

**Comment by BROBIRD** [comment]
老哥……mtalk.google.com境内一般网络环境下无法访问……您是想达到什么目的？

2017年9月25日 19:29，"stp88888" <notifications@github.com>写道：

**Comment by stp88888** [comment]
只是想让mtalk.google.com走直连，其他的不变，顺便那个pixiv被墙了，能加上不？

**Comment by BROBIRD** [comment]
mtalk.google.com走直连就不通了
pixiv的话，近期会跟进一波gfwlist，稍等哈~

**Comment by BROBIRD** [comment]
pixiv已加入

**Comment by BROBIRD** [comment]
mtalk.google.com 暂时不予加入……除非有更充分的理由

**Comment by crazystone19840328** [comment]
现在是mtalk4.google.com
