### ISSUE TITLE
动画疯分流有问题，全局能看，规则模式下则不行

### ISSUE THREAD

**Issue by eric1ee94** [ACL4SSR/ACL4SSR#454]

**Comment by leosam2048** [comment]
我不用动画疯
想排查问题，请贴日志！

**Comment by eric1ee94** [comment]
解决了，是去广告把开头的广告拦截了导致无法播放，广告拦截改Direct后正确播放。感谢大佬！

**Comment by eric1ee94** [comment]
> 我不用动画疯
> 想排查问题，请贴日志！
解决了，是去广告把开头的广告拦截了导致无法播放，广告拦截改Direct后正确播放。感谢大佬！
