### ISSUE TITLE
可以把acl当作pac文件配置么

### ISSUE THREAD

**Issue by fuzheng1998** [ACL4SSR/ACL4SSR#457]
pac一般用的都gfwlist.txt，请问这个acl文件能替换gfwlist.txt么

**Comment by BROBIRD** [comment]
@fuzheng1998 答案显而易见，难道你觉得gfwlist.txt和acl文件长得很像吗？

**Comment by fuzheng1998** [comment]
哦，那抱歉。给你提个建议，不要总反问，搞得我云里雾里
