### ISSUE TITLE
https://acl4ssr-sub.github.io/ 转换 Clash 导入异常

### ISSUE THREAD

**Issue by zhongwangninja** [ACL4SSR/ACL4SSR#459]
订阅链接 `https://cdn.x-ssr.cc/s/rpE3k_CLASH`
客户端 `Clash 新参数`
远程配置 `ACL4SSR_Online_Full 全分组 重度用户使用 (与Github同步)`

在 Mac Clash 最新版更新时报错提示
```
Remote Config Format Error: Rules[2061] [DOMAIN-SUFFI,🌍 国外媒体] error: unsupported rule type DOMAIN-SUFFI
```

访问配置 `https://subcon.py6.pw/sub?target=clash&new_name=true&url=https%3A%2F%2Fcdn.x-ssr.cc%2Fs%2FrpE3k_CLASH&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full.ini&emoji=true&list=false&udp=false&tfo=false&scv=false&fdn=false&sort=false` 确实搜索到一个 `- DOMAIN-SUFFI,🌍 国外媒体`这样的规则

配置一直保持没变，上午更新时第一次出现这个报错，麻烦大佬看看是否可能是最近更新导致的 bug。

**Comment by leosam2048** [comment]
@zhongwangninja 我来看看

**Comment by zhongwangninja** [comment]
已可以正常更新，辛苦大佬！
