### ISSUE TITLE
有关 ChinaIP.yaml 的疑问（使用 Clash For Android ）

### ISSUE THREAD

**Issue by stars-island** [ACL4SSR/ACL4SSR#461]
在配置文件里导入 **rule-providers** 和 **rules** 之后，加载配置文件，弹出错误如下：

` initial rule provider ChinaIP error: File must have a 'payload' field`

我查看您制作的 yaml 文件，发现每条 ip 地址前面都没有 **IP-CIDR** 的字样，搞不懂它的用意是什么。

换成 **ChinaDomain.yaml** 之后就没有问题了。是我哪里出错了吗？望指教，谢谢！

**Comment by leosam2048** [comment]
全是IP的，behavior直接选择ipcidr就行
https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

**Comment by stars-island** [comment]
感谢解答！
刚才重新写了一下，终于可以加载啦
