### ISSUE TITLE
is it a typo?

### ISSUE THREAD

**Issue by dev4u** [ACL4SSR/ACL4SSR#462]
https://github.com/ACL4SSR/ACL4SSR/blob/e7d142e001bde5aad530d407e353acb1a5baf79d/gfwlist-banAD.acl#L405

**Comment by dev4u** [comment]
(^|\.)adv\.sec\.intl\.miui.com$

**Comment by dev4u** [comment]
(^|\\.)adv\\.sec\\.intl\\.miui\\.com$

**Comment by leosam2048** [comment]
应该，少了一个斜杠。
但是影响不大。正则语法的话，两者差不多通用，有时间我改改

**Comment by dev4u** [comment]
**\\.sec.\\intl**
this is a wrong syntax of regex
