### ISSUE TITLE
acl4ssr-sub.github.io 默认规则 google play 商店无法下载 app

### ISSUE THREAD

**Issue by free4537** [ACL4SSR/ACL4SSR#464]
如题，卡在正在下载那里。
大概前天，也就是没有国内媒体分组时，是没有这个问题的。

**Comment by leosam2048** [comment]
?? 我一直没问题呀

**Comment by JPLiu** [comment]
这个可能跟 UDP 有关，Play 在下载的时候会产生到 services.googleapis.cn 的 UDP 连接，在不启用 UDP 支持（subconverter 默认也是）的情况下，UDP 的这个链接会被定向到 DIRECT，机场支持的话，订阅转换时加上 &udp=true 可解。
