### ISSUE TITLE
增加一个游戏平台规则代理和直连

### ISSUE THREAD

**Issue by s2270661782** [ACL4SSR/ACL4SSR#467]
希望增加一个游戏平台规则

**Comment by leosam2048** [comment]
@s2270661782 没懂，full模式里面 不是有个游戏平台么，包含Epic Steam。 你的意思单独来个游戏配置，里面是各个游戏的分组，比如stream分组、epic分组、绝地求生分组啥的么？

**Comment by s2270661782** [comment]
有吗？

**Comment by s2270661782** [comment]
@

**Comment by leosam2048** [comment]
@s2270661782 现在没有，但是如果需求人多的话，可以加一个。但是我不玩游戏，规则的话，可能得需要大家齐心协力来帮忙完成

**Comment by s2270661782** [comment]
最好+个epic 因为这个下载游戏 会直接代理下载

**Comment by s2270661782** [comment]
上次下个gta5直接90g没了

**Comment by s2270661782** [comment]
找到了  谢谢

**Comment by leosam2048** [comment]
@s2270661782 啥？？？

**Comment by s2270661782** [comment]
你说的 那个 full 全分组 有游戏平台分组

**Comment by s2270661782** [comment]
没有bilibili分组

**Comment by leosam2048** [comment]
@s2270661782 有 那个叫出海媒体分组。。。

**Comment by s2270661782** [comment]
是包含bilibili吗

**Comment by leosam2048** [comment]
@s2270661782 包含bilibili港澳台 爱奇艺港澳台

**Comment by s2270661782** [comment]
哦哦 谢谢解答

**Comment by s2270661782** [comment]
我没啥问题了
