### ISSUE TITLE
和网易UU加速器冲突

### ISSUE THREAD

**Issue by DogFather** [ACL4SSR/ACL4SSR#470]
游戏平台是DIRECT,开加速器进origin可以登陆,进游戏不能上线,也无法同步云端数据,关掉加速器可以正常同步,可以上线,大佬该如何解决?之前用其它规则都是正常的,我用的openclash
![918EF3EF-6381-4A48-9F57-4E3194D1AFBC](https://user-images.githubusercontent.com/33054546/93170935-bd1af800-f75a-11ea-9dc8-a26a485663f8.jpeg)

**Comment by leosam2048** [comment]
没日志。无法解决。 可以试试我游戏平台的普通或者mini分组

**Comment by DogFather** [comment]
大佬我明白了,是openclash的问题,不用fake-ip，用 redir-host就没有问题😅
