### ISSUE TITLE
不建议PT站点使用直连规则，或者能否将PT站点单独列出一个list

### ISSUE THREAD

**Issue by LzNOHentai** [ACL4SSR/ACL4SSR#478]
1.PT站点服务器多在国外，直连访问缓慢。
2.PT站点一般不会将访问站点的IP作为判断是否是seedbox的依据，而是会根据当前运行BT客户端的IP进行判断。
3.不必担心BT客户端是否会走代理而让代理服务器或PT账号承担风险，主流BT客户端默认下载不启用代理，且可以自行进行客户端的代理设置。

4.如果实在有用户有以上担心，建议将PT站点单独列出一个list供使用者自行配置。

**Comment by LzNOHentai** [comment]
还有一个小问题，就不再开一个issue了

amazon的图片服务器，ssl-images-amazon.com不应该全部指定为直连，亚马逊中国使用的是“images-cn-*.ssl-images-amazon.com”，其中*是数字，或者仅images-cn前缀。
其余前缀均为海外服务器，应指定走代理。

**Comment by leosam2048** [comment]
第一个问题是：取决于现状好多机场将BT进行封禁，放到直连上防止机场封号的，不是防止PT站点封号的
已经有单独list了，有PT代理需求的可以自行配置
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/PrivateTracker.list

第二个问题：感谢反馈，有时间我会研究一下，争取能有比较好的解决方式。

**Comment by leosam2048** [comment]
ssl-images-amazon.com 已经删掉了 
images-cn-8.ssl-images-amazon.com  有个关键字匹配 -cn 所以可以直连的
