### ISSUE TITLE
pixiv和日本雅虎挂了

### ISSUE THREAD

**Issue by cmmdwl** [ACL4SSR/ACL4SSR#48]

**Comment by cmmdwl** [comment]
似乎目前只是被污染。

**Comment by BROBIRD** [comment]
1、发issure前请确认自己反馈的问题是当前版本出现的
2、如果你说的是 `https://www.yahoo.co.jp/` 那么根据现有信息未发现有无法访问的情况。请您提供具体无法访问的域名。
