### ISSUE TITLE
DAZN规则 直播不能正常播放 回放正常

### ISSUE THREAD

**Issue by chenqiannice** [ACL4SSR/ACL4SSR#482]
DAZN 分流规则 不能观看直播 看回放正常
把国外视频 选择跟DAZN 一样线路 直播就可以正常观看了
大佬能不能看下 是不是直播走国外视频的线路了

**Comment by chenqiannice** [comment]
大佬 你的DAZN和国外媒体同时使用会有冲突 
能不能让DAZN和国外媒体不走同一条线

**Comment by leosam2048** [comment]
你看看日志 那条网址漏了
