### ISSUE TITLE
ios端浏览器使用百度引擎无法进行搜索

### ISSUE THREAD

**Issue by lucenli** [ACL4SSR/ACL4SSR#483]
用的是  Merlin Clash0923版本，384 v8平台

规则用的是acl4ssr转的，online no auto的规则

怀疑是应用净化或者全球拦截把百度的唤醒百度自家app的链接杀掉了。但是这对正常使用造成了一定影响

另外，百度网页版唤醒其他app的链接也会被杀掉，比如知乎，但是这种情况相对少见。

**Comment by lucenli** [comment]
![QQ图片20200925085340](https://user-images.githubusercontent.com/16946496/94215587-af5e3300-ff0f-11ea-86a3-9887ceea357a.png)
具体遇到的问题如图。

**Comment by leosam2048** [comment]
有具体日志吗？

**Comment by lucenli** [comment]
> 有具体日志吗？

倒是没有，经过和群里的几位大佬探讨之后找到了一个解决方案
  - DOMAIN-SUFFIX,shifen.com,DIRECT
  - DOMAIN-SUFFIX,ashifen.com,DIRECT

把上述两个属于banad规则集的域名从reject改成direct就可以了，估计是误杀了这两个域名。
建议考虑放行

**Comment by leosam2048** [comment]
@lucenli fixed
