### ISSUE TITLE
发现开了过滤新浪博客、百度贴吧都上不了了

### ISSUE THREAD

**Issue by oklong** [ACL4SSR/ACL4SSR#484]
发现开了过滤新浪博客、百度贴吧都上不了了

**Comment by leosam2048** [comment]
@oklong ？网页还是软件 我这边软件一点问题都没有

**Comment by oklong** [comment]
是网页，用的clash for windows

**Comment by leosam2048** [comment]
我没问题 网页啥的 你需要检查一下你的网络配置 广告过滤插件啥的

**Comment by oklong** [comment]
我用clash for windows订的通用在线规则，开了过滤就上不了，关掉过滤就可以上了，奇怪

**Comment by leosam2048** [comment]
@oklong 你打开日志那个页面 看看啥被拦截了！！！ 提交上来我好修复
