### ISSUE TITLE
[Bug] Scholar 规则组中不应当出现 Google Scholar 搜索引擎

### ISSUE THREAD

**Issue by Leo-Mu** [ACL4SSR/ACL4SSR#487]
Scholar 组内包含用来阅读学术文献的期刊等网站，它们根据 IP 来判断阅读权限，是一类特殊的需要用校园 IP 直连的境外网站。搜索引擎不在这个范畴，并且 Google Scholar 无法直连访问，不应该放到 scholar 组里面。现在这样是没法查找学术文献的，并不利于学术阅读体验。
https://github.com/ACL4SSR/ACL4SSR/blob/10bd1215f65386c5e942cf569c09e95493485ea5/Clash/Providers/Ruleset/Scholar.yaml#L4
https://github.com/ACL4SSR/ACL4SSR/blob/10bd1215f65386c5e942cf569c09e95493485ea5/Clash/Ruleset/Scholar.list#L3
https://github.com/tindy2013/subconverter/issues/253#issuecomment-703699113
https://github.com/tindy2013/subconverter/commit/167adc457e3f1c44834a501a7d321d14a6492323#r42948068

**Comment by luanshixiao** [comment]
我就说这几天怎么打不开google scholar了。。

**Comment by leosam2048** [comment]
@luanshixiao fixed

**Comment by Leo-Mu** [comment]
> @luanshixiao fixed

多谢多谢，感谢付出
