### ISSUE TITLE
默认allow-lan: true，能否改成false

### ISSUE THREAD

**Issue by tlerbao** [ACL4SSR/ACL4SSR#490]
默认allow-lan: true的话会导致
我开发项目的时候 hosts模拟的本地域名 127.0.0.1 xxx.dev 无法访问

**Comment by leosam2048** [comment]
没有这个问题吧？

**Comment by tlerbao** [comment]
@leosam2048 我刚测试了一下，好像不是allow-lan:true的问题。

但是我的另一个机场是机场官网提供的clash配置，用那个profiles，就不会导致我本机的站点打不开

用acl4ssr生成的profiles就会导致这个问题，我比对配置文件看区别是机场官网提供的配置文件里的allow-lan是false，所以以为是这个问题，看来不是。

现在不知道为啥了，问题确实存在，切换配置就没问题了。

**Comment by leosam2048** [comment]
你最好提供一下  127.0.0.1 xxx.dev 具体的网站

**Comment by tlerbao** [comment]
@leosam2048 这是随机的啊 
我修改hosts模拟一个域名指向我本机做本地站点的开发
可能是 127.0.0.1 shengxin.test
也可能是 127.0.0.1 bbb.com
也可能是 127.0.0.1 aaa.com

我本机有多少个项目就有可能模拟多收个域名
我并不是要把互联网上的某个网站修改hosts指向127.0.0.1

**Comment by leosam2048** [comment]
@tlerbao 我这边没这个问题啊，你可以用cn后缀的域名模拟吧。你这大概率自己写的域名，被规则代理转发的服务器去了

**Comment by tlerbao** [comment]
@leosam2048 刚测试了一下，确实如果是用shengxin.cn 指向本机可以访问
如果是shengxin.test 就访问不到，

哈哈，一般开发喜欢用 xxx.test 这样跟互联网的域名不冲突做本机开发 
不过我搜索了一下配置文件也没有针对.test后缀的设置啊 这就不知道为啥了

**Comment by leosam2048** [comment]
你可以尝试更新一下IP库。
或者将你自己的域名，放到跳过系统代理啥的。防止被clash代理

**Comment by tlerbao** [comment]
@leosam2048 IP库？如何更新

Clash刚开始用还不太会用，我这个机场需要经常更新订阅，我发现我在profiles里新增的规则，更新订阅后就覆盖了，是我姿势不对吗？

**Comment by leosam2048** [comment]
https://github.com/alecthw/mmdb_china_ip_list

**Comment by tlerbao** [comment]
@leosam2048 应该跟IP库没关系吧，我分析，如果是，另外的机场配置文件应该也不行。
问题应该就产生在profiles里
