### ISSUE TITLE
[规则添加]网站——动漫屋

### ISSUE THREAD

**Issue by zhongfly** [ACL4SSR/ACL4SSR#493]
该网站会根据ip显示内容，当为大陆ip时，会有部分漫画页面提示屏蔽，并且漫画图片地址无法打开（[测试页面](http://www.dm5.com/manhua-huayuanjiadeshuangzi/)）；当使用代理时，可正常显示所有页面及漫画图片。
所以希望添加到代理列表中去，涉及以下规则。
```
DOMAIN-SUFFIX,dm5.com
DOMAIN-SUFFIX,cdndm5.com
DOMAIN-SUFFIX,manhuaren.com
```
其中manhuaren.com是用以匹配该网站的搜索接口bi.manhuaren.com

**Comment by leosam2048** [comment]
@zhongfly 漏网之鱼，不要直连，选择代理就行

**Comment by zhongfly** [comment]
有时会被ChinaIP匹配到

leosam2048 <notifications@github.com> 于 2020年10月13日周二 14:49写道：

**Comment by zhongfly** [comment]
![Screenshot_20201013145706](https://user-images.githubusercontent.com/11155705/95826109-6ce88300-0d64-11eb-8f78-853fbb32f5ff.png)
移动4G网络下，ip被geoip判断成国内 直连
网站返回的ip可能也和运营商有关
