### ISSUE TITLE
请求加入reddit的规则

### ISSUE THREAD

**Issue by QuteSaltyFish** [ACL4SSR/ACL4SSR#494]
RT，好像在规则集里面也没有

**Comment by leosam2048** [comment]
DOMAIN-SUFFIX,reddit.com,🚀 节点选择
有

**Comment by QuteSaltyFish** [comment]
我觉得可以搞一个reddit的规则集，应该有
DOMAIN-SUFFIX,reddit.com
DOMAIN-SUFFIX,redditmedia.com
DOMAIN-SUFFIX,redd.it
