### ISSUE TITLE
期望去掉一个规则

### ISSUE THREAD

**Issue by EndureBlaze** [ACL4SSR/ACL4SSR#495]
期望不再拦截 `tracking.miui.com`，拦截会导致小米笔记本上的 `Mi Servce` 频繁请求导致 CPU 占用过高

**Comment by leosam2048** [comment]
@EndureBlaze 晚上可以给你去除一下

**Comment by leosam2048** [comment]
@EndureBlaze fixed

**Comment by EndureBlaze** [comment]
> @EndureBlaze fixed

thx 😁😘
