### ISSUE TITLE
一条苹果的规则放错了，还请去除。

### ISSUE THREAD

**Issue by wangliangliang2** [ACL4SSR/ACL4SSR#496]
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ProxyGFWlist.list
里面有一条
DOMAIN-SUFFIX,cdn-apple.com 放于CFW下，但是这条明显可以访问。如果直接放在GFW里面会导致
 **某些 应用** 从  **apple store**  下载软件走 **代理流量**
**软件更新** updates-http.cdn-apple.com 也走**代理流量**  
比如：https://support.apple.com/zh-mo/HT210060 里面就列着updates-http.cdn-apple.com 的说明。
因此相当的耗代理流量。
还请把这条剔除了。

**Comment by leosam2048** [comment]
@wangliangliang2 这个是同步的GFWlist列表 ，并未做改动，可以去对方项目上提问，如果删掉的话，我这可以做一个同步
