### ISSUE TITLE
增加国内网站直连

### ISSUE THREAD

**Issue by GeT1t** [ACL4SSR/ACL4SSR#499]
```DOMAIN-SUFFIX,5ewin.com```

**Comment by GeT1t** [comment]
```DOMAIN-SUFFIX,pediy.com```

**Comment by leosam2048** [comment]
@GeT1t 不需要添加，clash会默认判断ip位置的 。如果走了兜底代理的话说明IP库太旧了，可以自己更新 https://github.com/alecthw/mmdb_china_ip_list

**Comment by GeT1t** [comment]
更新了ip库一些国内的站还是走的兜底代理

www.chinapyg.com

**Comment by GeT1t** [comment]
感谢！
