### ISSUE TITLE
全分组重度用户使用（与 Github同步）可否增加一个无故障转移和均衡负载的选项

### ISSUE THREAD

**Issue by kamen-exaid** [ACL4SSR/ACL4SSR#502]
ACL4SSR Online Full全分组重度用户使用（与 Github同步）可否增加一个无故障转移和均衡负载的选项呢？
现在有这么一个情况：我增加了解锁网易云音乐的节点，当机场的某一节点挂掉后，故障转移会帮我切换到网易云解锁节点上，而这个节点是网易云专用的。

虽然下面的Noauto无自动测速确实没有故障转移，但是每次自己手动测ping，也是比较麻烦。

感谢

**Comment by leosam2048** [comment]
@kamen-exaid 你是要一个 有自动测速+无故障转移+无负载均衡的？？？

**Comment by kamen-exaid** [comment]
我记得很久之前有一版是这样的吧，有自动测速没有故障转移的全分组。
现在的全分组使用起来机场节点一旦挂掉一两个就自动跳到解锁网易云的节点（是因为这个节点的ping最低？）是比较麻烦。
假设在没有添加解锁网易云这种低ping节点的情况下，如果机场订阅中有中继和专线节点的话，当使用的低倍率中继节点出现问题时故障转移也会自动落到高倍率的专线节点上
希望您能考虑一下这个选项。如果您觉得没必要的话，我们用户使用NoAuto的配置也挺好的，就是不能自动测速看ping会有一些遗憾。

再次感谢您，让我们用上这么方便的规则

在 2020年10月28日，10:23，leosam2048 <notifications@github.com> 写道：

﻿

@kamen-exaid <https://github.com/kamen-exaid> 你是要一个 有自动测速+无故障转移+无负载均衡的？？？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ACL4SSR/ACL4SSR/issues/502#issuecomment-717653445>, or
unsubscribe

**Comment by leosam2048** [comment]
@kamen-exaid ACL4SSR_Online_Full.ini 将故障转移和负载均衡删掉了。 将老的迁移到ACL4SSR_Online_Ful_MultiMode.ini中了
