### ISSUE TITLE
请将China Play 加入直连列表

### ISSUE THREAD

**Issue by ccboxes** [ACL4SSR/ACL4SSR#503]
`*.chinaplay.store/*`
`chinaplay.store/*`

折扣游戏售卖网站，服务器在墙外但只允许中国大陆访问

**Comment by leosam2048** [comment]
@ccboxes 网站可以访问 只是付款方式 paymentwall 不让非中国用户访问

**Comment by ccboxes** [comment]
> 
> 
> @ccboxes 网站可以访问 只是付款方式 paymentwall 不让非中国用户访问

我的意思是把他加入ChinaDomain列表，这个网站是专门为大陆用户服务的，只允许中国IP访问，但是服务器在墙外，不强制直连会被代理。

**Comment by leosam2048** [comment]
@ccboxes added
