### ISSUE TITLE
小白求助，怎么用？

### ISSUE THREAD

**Issue by curryhendry** [ACL4SSR/ACL4SSR#505]
各位大佬，我使用clash X，也买了节点，但是想用更人性化的一些规则，请问应该怎么操作？
是否可以随着节点的更新自动更新？

**Comment by leosam2048** [comment]
@curryhendry 订阅转换吧 https://acl4ssr.netlify.app/

**Comment by curryhendry** [comment]
> @curryhendry 订阅转换吧 https://acl4ssr.netlify.app/

感谢回复，不过我现在是节点可用，是想完善一下白名单、去广告等规则。

**Comment by leosam2048** [comment]
@curryhendry 自己编写一下规则配置文件或者规则碎片吧。可以fork一下本项目，自己编写就行

**Comment by curryhendry** [comment]
> @curryhendry 自己编写一下规则配置文件或者规则碎片吧。可以fork一下本项目，自己编写就行

确实我比较菜，搞不定。有啥傻瓜一键操作的方法么。

**Comment by leosam2048** [comment]
@curryhendry 这个真的没有。 一键转换已经是最傻瓜的了。想自定义的话肯定得挨个来的。

**Comment by curryhendry** [comment]
> @curryhendry 这个真的没有。 一键转换已经是最傻瓜的了。想自定义的话肯定得挨个来的。
好的明白了，十分感谢！
