### ISSUE TITLE
提一个小建议~

### ISSUE THREAD

**Issue by FunAomi** [ACL4SSR/ACL4SSR#507]
![image](https://user-images.githubusercontent.com/38908099/99069484-66f6f380-25e9-11eb-8bdf-5dfd539ad0cc.png)
在节点选择里面直接加 .*  把所有的节点都列进来， 没必要再弄个手动切换了。

之前也是我自己写的  后来就懒得改了  所以提个建议

**Comment by leosam2048** [comment]
防止节点过多
