### ISSUE TITLE
AD 规则误伤 monitor.ustclug.org

### ISSUE THREAD

**Issue by yjh1021317464** [ACL4SSR/ACL4SSR#509]
去广告规则中的 `DOMAIN-KEYWORD,monitor` 误伤 `monitor.ustclug.org` 导致 [https://mirrors.ustc.edu.cn/status/](https://mirrors.ustc.edu.cn/status/) 显示异常

![image](https://user-images.githubusercontent.com/29970829/99105687-ed2d2d00-261d-11eb-88a1-e3f0dc83d31a.png)
![image](https://user-images.githubusercontent.com/29970829/99105713-f7e7c200-261d-11eb-9950-786be544c336.png)

**Comment by leosam2048** [comment]
fixed
