### ISSUE TITLE
SSR C#规则 gfwlist-user.rule 如何使用？

### ISSUE THREAD

**Issue by thisisjin** [ACL4SSR/ACL4SSR#51]
是下载后直接放进SSR文件夹，还是更名为suer.rule替换原来的?

另外黑名单gfwlist-banAD.acl 我SSR使用后无法打开GOOGLE play商店了，换成白名单一切正常

**Comment by BROBIRD** [comment]
下载后重命名为user.rule，替换原有的文件

发送自 Windows 10 版邮件应用

发件人: Okita
发送时间: 2017年10月10日 19:49
收件人: ACL4SSR/ACL4SSR
抄送: Subscribed
主题: [ACL4SSR/ACL4SSR] SSR C#规则 gfwlist-user.rule 如何使用？ (#51)

是下载后直接放进SSR文件夹，还是更名为suer.rule替换原来的?

**Comment by thisisjin** [comment]
@BROBIRD 好的，谢谢

**Comment by sirliu** [comment]
请问如何设置ACL（安卓端）和user.rule（PC端）才能链接Tor网络？测试用全局模式能连上TOR网络，但是使用用户自定义不行。
