### ISSUE TITLE
添加两条dazn规则

### ISSUE THREAD

**Issue by chenqiannice** [ACL4SSR/ACL4SSR#510]
DOMAIN-SUFFIX,optimizely.com
DOMAIN-SUFFIX,akamaized.net

请大佬添加一下

**Comment by edgexyz** [comment]
akamaized.net 已经在rule里了啊![image](https://user-images.githubusercontent.com/32131214/99139428-630fb380-2673-11eb-9722-d9e83f448786.jpeg)

**Comment by chenqiannice** [comment]
另外一条也在里面吗

**Comment by leosam2048** [comment]
@chenqiannice optimizely.com 是一个广告域名，如果它会导致dazn使用不了，我再删除。akamaized.net是一个全球公共cdn，所以最好给一下他的子域名

**Comment by chenqiannice** [comment]
子域名我不知道
今天中午dazn的女排比赛看不了 把这两条添加进去就能看了

**Comment by leosam2048** [comment]
@chenqiannice 自己看日志吧 akamaized.net不敢直接把主域名加进去

**Comment by chenqiannice** [comment]
logx.optimizely.com:443会导致dazn部分比赛使用不了

**Comment by chenqiannice** [comment]
app-measurement.com:443这个是不是子域名

**Comment by chenqiannice** [comment]
dcblivedazn.akamaized.net:443
这个是不是子域名

**Comment by leosam2048** [comment]
@chenqiannice optimizely 可以删除 dcblivedazn.akamaized.net 是子域名 可以加上
