### ISSUE TITLE
请问一下iOS版的Shadowrocket怎么导入使用？

### ISSUE THREAD

**Issue by lirunext** [ACL4SSR/ACL4SSR#511]
请问一下iOS版的Shadowrocket怎么导入使用？找了很久都没找到方法，所以问一下大佬，如何把项目的.acl格式文件转成Shadowrocket用的.conf格式？

**Comment by leosam2048** [comment]
@lirunext 用订阅转换网站转换一下吧， https://acl4ssr.netlify.app/
