### ISSUE TITLE
ACL4SSR 规则 Online Full NoAuto的baidu.com怎么搞到节点选择里去了

### ISSUE THREAD

**Issue by ForestL18** [ACL4SSR/ACL4SSR#515]
![Screenshot 2020-11-29 145924](https://user-images.githubusercontent.com/45709305/100535416-a8c3a300-3253-11eb-8e57-2d9ff755eb91.png)

**Comment by ForestL18** [comment]
请管理员尽快修改一下，谢谢

**Comment by leeshaoheng** [comment]
QQ也是。。。在代理列表了
![image](https://user-images.githubusercontent.com/46926283/100537255-c7c93180-3261-11eb-8aad-f878fedc4814.png)

**Comment by ForestL18** [comment]
ACL4SSR 规则 Online Full NoAuto有太多国内域名被错误的添加到代理规则列表，如qq,aliyun,sina,weibo,baidu，影响非常严重，请使用此规则的同学注意。另外，如果有谁知道怎么已联系到管理员，麻烦尽快联系一下，谢谢。

**Comment by dev4u** [comment]
蜜罐已在路上

**Comment by leosam2048** [comment]
已经修复了，写脚本的的时候忘记有部分是白名单了。
