### ISSUE TITLE
ACL4SSR 规则 Online Full NoAuto有太多国内域名被错误的添加到代理规则列表

### ISSUE THREAD

**Issue by ForestL18** [ACL4SSR/ACL4SSR#517]
ACL4SSR 规则 Online Full NoAuto有太多国内域名被错误的添加到代理规则列表，如qq,aliyun,sina,weibo,baidu，影响非常严重，请使用此规则的同学注意。另外，如果有谁知道怎么已联系到管理员，麻烦尽快联系一下，谢谢。

**Comment by leosam2048** [comment]
已经修复了，写脚本的的时候忘记有部分是白名单了。

**Comment by 4512369781** [comment]
> 已经修复了，写脚本的的时候忘记有部分是白名单了。

Clash-Providers文件夹里的还没有修复。请处理下，谢谢。

**Comment by leosam2048** [comment]
好了
