### ISSUE TITLE
[规则补充]向SteamCN.list中添加3个可直连域名

### ISSUE THREAD

**Issue by zhongfly** [ACL4SSR/ACL4SSR#519]
> DOMAIN-SUFFIX,steamstore-a.akamaihd.net
> DOMAIN-SUFFIX,steamcommunity-a.akamaihd.net
> DOMAIN-SUFFIX,steamuserimages-a.akamaihd.net

这3个域名个人测试是可以直连（SteamCN中也已经有类似的规则steamcdn-a.akamaihd.net），前2个直接访问即可测试出来，最后一个可以通过steam社区中一些图片链接测试，[示例](https://steamuserimages-a.akamaihd.net/ugc/760472985787859203/9AE26A0ECCE365773C9C87E7C2B98E19777B6183/)。

目前会被ProxyLite.list中# Instagram 里的如下规则匹配，使得其被代理。

> DOMAIN-SUFFIX,akamaihd.net

**Comment by leosam2048** [comment]
恩 添加了 steamcommunity但是这种的有可能会出问题 先加吧

**Comment by fxzxmicah** [comment]
```
steamstore-a.akamaihd.net
steamcdn-a.akamaihd.net
```
这两个貌似已经被屏蔽。

**Comment by zhongfly** [comment]
@fxzxmicah 用ipip.net的工具测试，大部分地区访问正常
![1](https://user-images.githubusercontent.com/11155705/102790632-b0084780-43e0-11eb-9096-4544ace7da9c.png)
![2](https://user-images.githubusercontent.com/11155705/102790640-b3033800-43e0-11eb-809e-2f75acd09f4b.png)

**Comment by leosam2048** [comment]
暂时删了吧。虽然我这边也能直连。

**Comment by fxzxmicah** [comment]
@zhongfly 你这样没啥意义啊，Steam中那么多个akamaihd.net的域名，但是我这里确实只有那两个访问不了，其它正常，我能怎么办。

**Comment by zhongfly** [comment]
只能说你那里网络算是少数情况吧，测试的意思是表示大部分地区都可以正常访问。

>

**Comment by fxzxmicah** [comment]
@leosam2048 我这里今天又暴毙了两个：
```
cdn.cloudflare.steamstatic.com
community.cloudflare.steamstatic.com
```
不知道什么情况……

**Comment by fxzxmicah** [comment]
啊，我刚发完又好了，刚才最少有一个小时连不上。
