### ISSUE TITLE
汇报一个 嗶咔漫畫 picacomic 的广告

### ISSUE THREAD

**Issue by xream** [ACL4SSR/ACL4SSR#52]
`(^|\.)pica-juicy\.picacomic\.com$`

**Comment by BROBIRD** [comment]
可以确认吗？能否提供一下广告页面的截图？谢谢！

**Comment by xream** [comment]
能确认 已经在用了
启动广告和内页广告 nsfw 就不发图了...

**Comment by BROBIRD** [comment]
噗。。。OK，我去加上，谢谢这位绅士（滑稽

2017年10月13日 16:55，"Hsiaoyi Hsu" <notifications@github.com>写道：

**Comment by BROBIRD** [comment]
已更新
