### ISSUE TITLE
建议作者合并ACL4SSR_Online_Full_NoAuto.ini中的哔哩哔哩和出海媒体规则

### ISSUE THREAD

**Issue by ForestL18** [ACL4SSR/ACL4SSR#521]
建议作者合并ACL4SSR_Online_Full_NoAuto.ini中的哔哩哔哩和出海媒体规则，否则想让哔哩哔哩换区的话会因为没有调整出海媒体选项而无法成功。而其他的国内媒体也不会因为出海规则受影响。
![image](https://user-images.githubusercontent.com/45709305/101456494-1c119700-396f-11eb-8c92-e37b1519f1c5.png)

**Comment by ForestL18** [comment]
建议全部合并到哔哩哔哩规则里去

**Comment by leosam2048** [comment]
恩 我把出海媒体删了吧。 接受你的意见

**Comment by ForestL18** [comment]
> 恩 我把出海媒体删了吧。 接受你的意见

感谢，好用的规则需要大家一起使用和反馈👍👍👍

**Comment by ZerOri** [comment]
求问这个项目是如何使用的
