### ISSUE TITLE
本地地址未直连

### ISSUE THREAD

**Issue by fxzxmicah** [ACL4SSR/ACL4SSR#524]
![image](https://user-images.githubusercontent.com/48860358/101546799-4b162000-39e4-11eb-8073-6be3f7b02161.png)
clash使用的是PAC模式

https://github.com/Fndroid/clash_for_windows_pkg/issues/1401

**Comment by leosam2048** [comment]
@fxzxmicah IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve  有这行规则，应该没问题

**Comment by fxzxmicah** [comment]
![image](https://user-images.githubusercontent.com/48860358/101612771-fb684080-3a45-11eb-9870-f1c12d28a67b.png)
规则是有，但是貌似没有生效。

**Comment by leosam2048** [comment]
恩 因为,no-resolve 是不解析域名的意思。只对IP生效。
你可以用 xxxx.local  啥的 。 这样可以本地域名访问了。

**Comment by fxzxmicah** [comment]
其实就是”IP规则只适用于通过IP访问的情况，不适用于解析到本地的域名这种情况“的意思吧？

**Comment by leosam2048** [comment]
是的，有些规则会把,no-resolve 去掉，这样ip和本地域名都可以。
但是有问题就是，如果有dns欺骗，比如把谷歌地址解析到本地ip上，那就访问不了。
