### ISSUE TITLE
tg群组这里是只有我被禁言了还是大家都被禁言了

### ISSUE THREAD

**Issue by OXERIS** [ACL4SSR/ACL4SSR#527]
![Screenshot_20201213-102421_Plus](https://user-images.githubusercontent.com/18722082/102001538-62c80e00-3d2e-11eb-98ca-e51d09521375.jpg)
我的用户名是@OXERIS

**Comment by BROBIRD** [comment]
@OXERIS 群组只是为了启用评论功能而设置的，所以请不要加入。如需评论，请直接点击频道内推文下方的评论按钮（没有按钮的话就请升级到 Telegram 的最新版本），那个功能不需要加入群组也可以正常使用。
如果加入了那个群，会被机器人踢出并封禁 1 天，被封禁的时候评论功能也是不可用的。
