### ISSUE TITLE
网易新闻网页无法打开

### ISSUE THREAD

**Issue by aabeuv** [ACL4SSR/ACL4SSR#53]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

**Comment by BROBIRD** [comment]
所以你的问题是什么？

**Comment by aabeuv** [comment]
![screenshot_20171019-092700](https://user-images.githubusercontent.com/32299357/31750045-261b1556-b4b0-11e7-9a11-b933f748e5fc.png)

**Comment by aabeuv** [comment]
打开网易就是这样子

**Comment by BROBIRD** [comment]
我这里同规则测试打开正常

2017年10月19日 09:31，"aabeuv" <notifications@github.com>写道：
