### ISSUE TITLE
全球拦截，关键词，规则 BanAD.list，抖音购物车不能打开！

### ISSUE THREAD

**Issue by cdnoss** [ACL4SSR/ACL4SSR#531]
全球拦截，关键词，规则 BanAD.list，抖音购物车不能打开！希望修复，谢谢
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list

**Comment by leosam2048** [comment]
@cdnoss 自己看日志，看那个被拦截，发上来，我删掉

**Comment by cdnoss** [comment]
![image](https://user-images.githubusercontent.com/65028966/102683658-76331780-420d-11eb-8980-f907bec572e6.png)

**Comment by leosam2048** [comment]
下次更新修复
