### ISSUE TITLE
ProxyMedia 中存在一部分重复和多余空格

### ISSUE THREAD

**Issue by VegeHime** [ACL4SSR/ACL4SSR#533]
DOMAIN, atv-ps.amazon.com
DOMAIN, fls-na.amazon.com
DOMAIN-SUFFIX, media-amazon.com
三行多了空格
DOMAIN-SUFFIX,execute-api.ap-southeast-1.amazonaws.com
DOMAIN,44wilhpljf.execute-api.ap-southeast-1.amazonaws.com

DOMAIN,d151l6v8er5bdm.cloudfront.net
DOMAIN-SUFFIX,d151l6v8er5bdm.cloudfront.net
DOMAIN-SUFFIX,d1sgwhnao7452x.cloudfront.net
DOMAIN,d3cv4a9a9wh0bt.cloudfront.net
DOMAIN,dai3fd1oh325y.cloudfront.net
DOMAIN,d3c7rimkq79yfu.cloudfront.net
DOMAIN-SUFFIX,d3c7rimkq79yfu.cloudfront.net
DOMAIN,d349g9zuie06uo.cloudfront.net
DOMAIN,d1k2us671qcoau.cloudfront.net
DOMAIN,d2anahhhmp1ffz.cloudfront.net
DOMAIN,dfp6rglgjqszk.cloudfront.net
DOMAIN-SUFFIX,cloudfront.net
这些行相互重复

**Comment by leosam2048** [comment]
空格的已经删掉了。
重复的就让他重复吧，问题不大
