### ISSUE TITLE
Spark 服务已被屏蔽，请移除 ChinaDomain 直连

### ISSUE THREAD

**Issue by YohaneWW** [ACL4SSR/ACL4SSR#535]
https://github.com/ACL4SSR/ACL4SSR/blob/749784c430aba73c752d4cfc4a547fca88fb21ca/Clash/ChinaDomain.list#L299

**Comment by YohaneWW** [comment]
且现存列表不全，如果可以的话请求加入 [ProxyLite](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ProxyLite.list) 。
```
DOMAIN-SUFFIX,amplitude.com
DOMAIN-SUFFIX,firebaseio.com
DOMAIN-SUFFIX,hockeyapp.net
DOMAIN-SUFFIX,smartmailcloud.com
DOMAIN-SUFFIX,readdle.com
```

**Comment by leosam2048** [comment]
fixed
