### ISSUE TITLE
大佬。麻烦将config内ini加上容差值字段吧

### ISSUE THREAD

**Issue by flyhigherpi** [ACL4SSR/ACL4SSR#536]
urltest要用到
比如
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300
改
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,200

**Comment by leosam2048** [comment]
添加了。50ms
