### ISSUE TITLE
FCM规则的问题

### ISSUE THREAD

**Issue by Iy204** [ACL4SSR/ACL4SSR#538]
使用的是转换网站的默认版。
我发现mtalk.google.com被加入全球直连并且在FCM规则组前面。
这样FCM分组选择代理也没用。

**Comment by leosam2048** [comment]
没有啊 
fcm分组是放在直连前面的。
mtalk.google.com 可以受fcm分组控制的

**Comment by Iy204** [comment]
我在https://acl4ssr-sub.github.io/转换的默认版。
虽然分组里fcm在直连前面。可是具体的规则直连在fcm前面。
我在Connection里面看mtalk.google.com都是走Direct。而不是受fcm分组控制。

**Comment by sjdhome** [comment]
> 没有啊
> fcm分组是放在直连前面的。
> mtalk.google.com 可以受fcm分组控制的

之前我也提过类似的问题，重复的规则是会互相影响的。我fork了一份把重复的部分去掉就正常了。
https://github.com/sjdhome/ACL4SSR/commit/c972caa5e6d564e705691bd8c4a0db5ab41c538a

**Comment by leosam2048** [comment]
@sjdhome @Iy204

**Comment by sjdhome** [comment]
> @sjdhome @Iy204
> 差不多懂了，UnBan.list里面冲突了
> 删掉就好了。

GoogleCN.list里面没有影响么，那个也设定为全球直连了

**Comment by leosam2048** [comment]
@sjdhome 没啥影响，如果你使用带fcm分组的话。 一会缓存失效了。你可以更新一下试试
