### ISSUE TITLE
能把xvideos.com加入到ProxyMedia.list里面吗？

### ISSUE THREAD

**Issue by Microactive** [ACL4SSR/ACL4SSR#539]
pronhub是全球最大的老司机网站，xvideo是全球第二大的老司机网站，现在pronhub面临整顿，希望能把xvideos相关域名加入到ProxyMedia.list( https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ProxyMedia.list ) 里面。

#  xvideos
DOMAIN-SUFFIX,xvideos-cdn.com
DOMAIN-SUFFIX,xvideos.com

**Comment by leosam2048** [comment]
已经在ProxyLite.list里了
