### ISSUE TITLE
如何让被污染的博客域名加入到代理规则中

### ISSUE THREAD

**Issue by hwanz** [ACL4SSR/ACL4SSR#543]
我博客被DNS污染了，已经加入到了gfwlist了。请问怎么加入到这里的规则里面？

**Comment by leosam2048** [comment]
@hwanz 一般兜底代理就行，网站不放国内就行。

**Comment by hwanz** [comment]
兜底代理是什么意思，网站不在国内，但是域名被dns污染了。

**Comment by leosam2048** [comment]
@hwanz 只要没在国内最后都会被代理的

**Comment by hwanz** [comment]
好的。请问项目日常更新的gfwlist是这里的吗：https://github.com/gfwlist/gfwlist

**Comment by leosam2048** [comment]
@hwanz 是
