### ISSUE TITLE
请求精简github相关规则

### ISSUE THREAD

**Issue by Oosl** [ACL4SSR/ACL4SSR#545]
在Clash/ProxyGFWlist.list中与github相关的规则有好多条，这导致我在手机上使用时会无法访问github，请求精简只剩下
`DOMAIN-KEYWORD,github`
这一条就好了

**Comment by leosam2048** [comment]
@Oosl 有DOMAIN-KEYWORD,github ，所以你需要检查一下你自己手机

**Comment by Oosl** [comment]
是的，是存在 ```DOMAIN-KEYWORD,github``` 。
我目前的问题是，直接使用Clash/ProxyGFWlist.list走代理会导致github无法访问，然后删除掉其中除 ```DOMAIN-KEYWORD,github``` 外的所有与github相关的规则后就可以正常访问github了。
目前没发现其他原因/解决办法。

**Comment by leosam2048** [comment]
@Oosl 那需要你自己检查一下日志

**Comment by Oosl** [comment]
好的，刚发现确实好像是别的问题。
