### ISSUE TITLE
请求加入这三个广告域名进行屏蔽

### ISSUE THREAD

**Issue by Hard2crossWa11** [ACL4SSR/ACL4SSR#546]
https://ad-channel.wikawika.xyz/

**Comment by Hard2crossWa11** [comment]
是某粉色app的贴图广告，
漫画看到中间的时候会跳出来......
开始播放动图，
很突兀和不协调（不！够！色！）
之前用QuanX试了可以用Host匹配再reject的方式
让它变成只有关闭按钮的空白贴图，
阅读体验会好很多。

**Comment by zhongfly** [comment]
还有一个
ad-display.wikawika.xyz

**Comment by leosam2048** [comment]
已添加

**Comment by Hard2crossWa11** [comment]
非常感谢

leosam2048 ***@***.***> 于2021年4月3日周六 下午8:35写道：
