### ISSUE TITLE
请求加入origin下载CDN

### ISSUE THREAD

**Issue by Scarecrow-ai** [ACL4SSR/ACL4SSR#547]
国内使用origin的香港akamai cdn时是满速的,但走了节点选择

域名:
origin-a.akamaihd.net
对应规则:
 - DOMAIN-SUFFIX,akamaihd.net,🚀 节点选择
 
 希望能加入游戏平台或直连

**Comment by xzsk2** [comment]
建议尽快修复，已经被橘子跑掉100g了😅

**Comment by leosam2048** [comment]
fixed
