### ISSUE TITLE
能否将Twitter相关代理地址单独列一个分组？

### ISSUE THREAD

**Issue by kingofotaku** [ACL4SSR/ACL4SSR#552]
最近发现使用香港的服务器上Twitter会出现点击用户名查看主页时出现“此用户不存在”的情况，此问题有人已在知乎上讨论过。详见：[https://www.zhihu.com/question/411022482](url) 若独立出来，可以方便将Twitter代理指向美日等没有此问题的地区。

**Comment by leosam2048** [comment]
@kingofotaku 推荐自制配置文件。

**Comment by kingofotaku** [comment]
> @kingofotaku 推荐自制配置文件。

那么能否至少将Twitter地址独立成一个规则碎片？

**Comment by leosam2048** [comment]
@kingofotaku 多看看 多找找 。。。
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Twitter.list

**Comment by kingofotaku** [comment]
> @kingofotaku 多看看 多找找 。。。
> https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Twitter.list

确实疏忽了，抱歉。
