### ISSUE TITLE
海底捞app不能正常打开

### ISSUE THREAD

**Issue by tengyuankoo** [ACL4SSR/ACL4SSR#556]
需要删除：
- DOMAIN-SUFFIX,duiba.com.cn,🛑 全球拦截

**Comment by leosam2048** [comment]
@tengyuankoo 分应用代理或者发一下被拦截的日志。duiba是广告域名，一般不会予以解封的

**Comment by tengyuankoo** [comment]
activity.m.duiba.com.cn:443
activity-1.m.duiba.com.cn:443
embedlog.duiba.com.cn:443
这3个地址

**Comment by BROBIRD** [comment]
建议需要使用海底捞APP的时候临时关闭代理软件，广告域名暂时不予移除
