### ISSUE TITLE
请问可以给一个最新域名获取方式吗？

### ISSUE THREAD

**Issue by RoyRao2333** [ACL4SSR/ACL4SSR#557]
请问可以在github项目仓库里的readme文件里加上在线订阅转换的最新域名吗？虽然目前的我已经收藏书签了，但怕万一以后这个链接不能用了，又找不到新的域名。。。谢谢！

**Comment by leosam2048** [comment]
@RoyRao2333 如果不能用了，就代表acl彻底不维护了
