### ISSUE TITLE
格式错误

### ISSUE THREAD

**Issue by MXKecetyCN** [ACL4SSR/ACL4SSR#566]
Providers里的ChinaCompanyIp和AmazonIp的格式不正确
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/ChinaCompanyIp.yaml
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/Ruleset/AmazonIp.yaml

**Comment by leosam2048** [comment]
@MXKecetyCN 咋不对，这是专门ip段的格式

**Comment by MXKecetyCN** [comment]
behavior: ipcidr
抱歉，是我用错方式了…………
