### ISSUE TITLE
www.gstatic.com 和 ssl.gatatic.com 怎么变成全球直连了

### ISSUE THREAD

**Issue by isArtJay** [ACL4SSR/ACL4SSR#567]
![image](https://user-images.githubusercontent.com/48620527/109238211-1741de00-780e-11eb-91e8-064df260f58a.png)

**Comment by BROBIRD** [comment]
@isArtJay 一直都是全球直连

**Comment by isArtJay** [comment]
> @isArtJay 一直都是全球直连

好吧
