### ISSUE TITLE
Microsoft Store应用商店在开启系统代理后无法打开

### ISSUE THREAD

**Issue by wangbo-ops** [ACL4SSR/ACL4SSR#571]
Microsoft Store应用商店在开启系统代理后无法打开，选择direct模式也不行。关闭系统代理后可以正常打开。

**Comment by wangbo-ops** [comment]
微软服务分组选择的是全球直连

**Comment by BROBIRD** [comment]
UWP Loopback 打开了吗？另提问请附日志，方便分析问题。
