### ISSUE TITLE
屏蔽运营商本机号码认证业务域名

### ISSUE THREAD

**Issue by Riajyuu** [ACL4SSR/ACL4SSR#572]
电信 id6.me
移动 cmpassport.com
联通 opencloud.wostore.cn
联通 nishub1.10010.com:38750

还有两个认证SDK的业务域名
极验 onepass.geetest.com
ADmobile 114dev.com

来自 @MitaZ

**Comment by MitaZ** [comment]
这个不知道适不适合加入到规则里🤔，我感觉有的人喜欢这个功能，毕竟不用输验证码了。

（虽然我自己是屏蔽了）

**Comment by dev4u** [comment]
屏蔽的意思是让这些域名走直连？还是扔黑洞？

**Comment by MitaZ** [comment]
> 屏蔽的意思是让这些域名走直连？还是扔黑洞？

当然是扔黑洞/reject，走直连不就相当于没屏蔽吗😄

另外很欣慰地看到即将上线的MIUI 13要对一键登录做出管制了：
![image](https://user-images.githubusercontent.com/15263016/124611004-9d98bb80-dea3-11eb-86c9-823a930b80f1.jpeg)

**Comment by dev4u** [comment]
> > 屏蔽的意思是让这些域名走直连？还是扔黑洞？
> 
> 当然是扔黑洞/reject，走直连不就相当于没屏蔽吗😄
> 
嗯嗯，我睡迷糊了。
`应用可以通过你的IP地址查到中间四位数`这句话是认真的吗？除了运营商，其他人应该不会知道当中的关系啊！

**Comment by MitaZ** [comment]
> 嗯嗯，我睡迷糊了。
> `应用可以通过你的IP地址查到中间四位数`这句话是认真的吗？除了运营商，其他人应该不会知道当中的关系啊！

手机号归属地数据已经烂大街了，且不说收费API，免费的数据都有很多地方可以下载到，比如[这个知乎提问](https://www.zhihu.com/question/20117808)、[这个repo](https://github.com/ls0f/phone)，把数据整理之后用来做反向查询理论上是可行的。

**Comment by dev4u** [comment]
> 手机号归属地数据已经烂大街了，且不说收费API，免费的数据都有很多地方可以下载到，比如[这个知乎提问](https://www.zhihu.com/question/20117808)、[这个repo](https://github.com/ls0f/phone)，把数据整理之后用来做反向查询理论上是可行的。

原来你说的是号码归属地啊，现在都不玩这个了，毕竟都已经开放了携号转网。

**Comment by loongfzs** [comment]
这太棒了！
