### ISSUE TITLE
请求在DOMAIN-SUFFIX中加入Reddit媒体服务器相关网址

### ISSUE THREAD

**Issue by Sherman-Liu** [ACL4SSR/ACL4SSR#573]
请求增加规则
DOMAIN-SUFFIX,redditmedia.com
DOMAIN-SUFFIX,redd.it
目前规则中仅有
DOMAIN-SUFFIX,reddit.com
导致Reddit的媒体服务器(以上两个新增域名)无法通过代理访问，且媒体服务器亚洲地区的解析位于香港，已经被GFW屏蔽，无法直连。

**Comment by BROBIRD** [comment]
https://github.com/ACL4SSR/ACL4SSR/blob/d31c186f6e1997953cde9d01c0e728ec1efc93b3/Clash/ProxyGFWlist.list#L3929

https://github.com/ACL4SSR/ACL4SSR/blob/d31c186f6e1997953cde9d01c0e728ec1efc93b3/Clash/ProxyGFWlist.list#L3932

找了一下一直有这两条啊

**Comment by Sherman-Liu** [comment]
开发者您好，我仔细检查了一下配置文件的引用，发现使用ACL4SSR转换订阅时，除了ACL4SSR的Full版订阅引用了ProxyGFWlist.list，Mini和普通版引用的ProxyLite.list和ProxyMedia.list均未包含以上两个域名，请问是否可以将Reddit的三个域名都默认包含在普通版和Mini版引用的配置文件里，谢谢！

**Comment by Sherman-Liu** [comment]
因为在使用在线订阅转换服务的时候，很难搭配组合自己想用的规则碎片，Full版的规则过于繁杂，移动设备上使用受性能限制，还是希望能把以上两条规则包含在普通和Mini版内，谢谢！
