### ISSUE TITLE
仓库现有的规则似乎全部回退到老版本（2020年8月）了？

### ISSUE THREAD

**Issue by ResidualBlood** [ACL4SSR/ACL4SSR#577]
比如说 [BanEasyList.list](https://github.com/ACL4SSR/ACL4SSR/blob/e7d142e001bde5aad530d407e353acb1a5baf79d/Clash/BanEasyList.list) 更新时间变为了：2020-08-28 23:35:26， 原先为：2021-02-27 19:10:45
commit时间变为了[Oct 15, 2020](https://github.com/ACL4SSR/ACL4SSR/commits/master/Clash/BanEasyList.list)

**Comment by ResidualBlood** [comment]
另外，本仓库作为上游时进行合并出现大量冲突

**Comment by leosam2048** [comment]
可能让鸟哥给提交成老版本了 晚上回去修复一下

**Comment by BROBIRD** [comment]
抱歉，我本地操作的时候操作错仓库了，已经恢复

**Comment by ResidualBlood** [comment]
Ok，稳
