### ISSUE TITLE
请求加入1条友盟广告域名，谢谢

### ISSUE THREAD

**Issue by cxlg325** [ACL4SSR/ACL4SSR#58]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

提交1条友盟的广告域名页
alog.umeng.com

**Comment by cxlg325** [comment]
我自己增加了

**Comment by BROBIRD** [comment]
已加入。
