### ISSUE TITLE
Should dl.google.com be connected directly?

### ISSUE THREAD

**Issue by lifansama** [ACL4SSR/ACL4SSR#580]
dl.google.com is in the `GoogleCN.list` .
Some files like Chrome Offline Installer cannot be downloaded because of dl.google.com connected directly.

```
https://dl.google.com/release2/chrome/GhyeF19qcgzTvU87ncEAdQ_89.0.4389.90/89.0.4389.90_chrome_installer.exe
```

**Comment by BROBIRD** [comment]
@lifansama Check your DNS first and report your operator and location to us please.

**Comment by lifansama** [comment]
The ISP's DNS is to blame.
