### ISSUE TITLE
mini noauto微信表情加载不出来？

### ISSUE THREAD

**Issue by zerotwo0002** [ACL4SSR/ACL4SSR#586]
不知道是不是我自己的问题，打开clash微信表情就一直转圈圈，关了就好了，规则用的是mini noauto😂

**Comment by edgexyz** [comment]
clash 不会按 js 去匹配 uri 的吧....

**Comment by leosam2048** [comment]
@zerotwo0002 推荐像微信、支付宝、QQ这些还是直接按应用跳过代理吧。

**Comment by zerotwo0002** [comment]
> @zerotwo0002 推荐像微信、支付宝、QQ这些还是直接按应用跳过代理吧。

好的
有的时候谷歌翻译会登录上，但有的时候又不会登录，杀后台重新进就又登录了，这个也是我clash的问题吗😂

**Comment by zerotwo0002** [comment]
> clash 不会按 js 去匹配 uri 的吧....

😂不懂这些复杂的，要挑个时间好好学习一下
