### ISSUE TITLE
个人认为 ChinaDomain 不该 包含m-team 域名甚至  Private Tracker 这个大类.

### ISSUE THREAD

**Issue by tanpengsccd** [ACL4SSR/ACL4SSR#59]
关于 ChinaDomain 该不该 包含m-team 域名甚至  Private Tracker 这个大类.
由于大部份站点 为了规避风险 都是 国外服务器+ CF ,实际不应该算在国内.至少 m-team  不应该加入,m-team 在国内已经被阻断了.tracker叶连接不上.
如果需要可以自己更加精细的添加  Private Tracker.

**Comment by acl4ssr-sub** [comment]
同意
