### ISSUE TITLE
使用ACL4SSR_Online_Full.ini配置后，无法观看央视影音直播

### ISSUE THREAD

**Issue by Aryous** [ACL4SSR/ACL4SSR#590]
错误提示P507

**Comment by leosam2048** [comment]
@Aryous 贴日志，看那个网址呗拦截了

**Comment by Aryous** [comment]
![image](https://user-images.githubusercontent.com/59194462/115141976-d5951d00-a071-11eb-91cb-ebc4160db5d0.png)
我使用的是openclash，fakeip模式，未开启UDP转发，在iPad（分配的IP地址为192.168.0.193）上无法使用央视影音观看直播，日志显示当我在观看直播时均为直连模式，同时刚刚央视影音弹窗告知我被识别到了台湾地区，所以无法观看，原因未知。

**Comment by leosam2048** [comment]
@Aryous 那这个感觉不是规则的问题，应该是dns或者别的问题

**Comment by Aryous** [comment]
似乎确实是DNS的问题，我开启了adguard home服务，关闭后可以正常播放。
![image](https://user-images.githubusercontent.com/59194462/115180983-75ea5080-a109-11eb-9c1f-188aa8cd491d.png)
![image](https://user-images.githubusercontent.com/59194462/115180993-7be03180-a109-11eb-9521-e5ad3b1d6697.png)
![image](https://user-images.githubusercontent.com/59194462/115181003-800c4f00-a109-11eb-95e7-1b2b15281513.png)
![image](https://user-images.githubusercontent.com/59194462/115181094-bba71900-a109-11eb-9016-5ba93354aa2f.png)
这是我的adguard home设置，open clash的dns劫持处于关闭状态，请问有什么地方冲突吗？

**Comment by Aryous** [comment]
经测试，只有在iPad上央视影音app无法观看直播，报错p507，iPhone上可以正常使用，应该不是规则的问题，可能网络配置有问题。

**Comment by Aryous** [comment]
可能是这样的吗？突然想到的，iPad是Wi-Fi版本，没有蜂窝数据网络，家里使用了软路由开启规则代理后，地区只能识别大陆之外，因为这两天我发现自带的地图里面的数据服务商由高德地图变为了tomtom，而且无法使用路线规划。￼￼￼

**Comment by BROBIRD** [comment]
我觉得是你设置的DoH服务器的问题
