### ISSUE TITLE
能否设定不根据节点名称判定emoji国家？

### ISSUE THREAD

**Issue by 2guan** [ACL4SSR/ACL4SSR#597]
节点名称与节点归属地无关的时候，会自动根据节点名称前两个字母判定emoji图标。有时会比较困扰。能否增加一个不添加国家emoji的选项？

**Comment by BROBIRD** [comment]
@2guan 可以自己修改配置文件提供给后端接口

**Comment by 2guan** [comment]
多谢回复！！如何修改呢？我只是想生成一个v2ray的订阅链接。

**Comment by BROBIRD** [comment]
@2guan 详情请移步subconverter项目，需要修改的参数是订阅链接的config参数
