### ISSUE TITLE
services.googleapis.cn 需要加入到谷歌服务FCM里

### ISSUE THREAD

**Issue by zhangj3** [ACL4SSR/ACL4SSR#600]
手机是红米K20pro MIUI11,谷歌商店可以正常打开和搜索，但就是下载不了应用，排查后发现是services.googleapis.cn不在FCM上，请帮忙添加 谢谢
![image](https://user-images.githubusercontent.com/49198958/117166724-37d37900-adf9-11eb-881d-6eca67a21f90.png)

**Comment by BROBIRD** [comment]
@zhangj3 services.googleapis.cn 这个域名如果直连的话是无法加载Google Play商店的

**Comment by zhangj3** [comment]
> @zhangj3 services.googleapis.cn 这个域名如果直连的话是无法加载Google Play商店的

你好 稍等 我再切换回ACL的转换订阅截图给你看看 现在是换成朋友的，识别没有问题
![image](https://user-images.githubusercontent.com/49198958/117176231-3d818c80-ae02-11eb-84b1-e516f012e7fc.png)

**Comment by zhangj3** [comment]
你好，可以刚刚是一些其他原因导致这个cn域名识别错误的，这会儿又好了...这个问题我先关闭，谢谢！
![image](https://user-images.githubusercontent.com/49198958/117177211-59d1f900-ae03-11eb-8f17-1769003e50f5.png)
