### ISSUE TITLE
希望适配次元壁纸

### ISSUE THREAD

**Issue by linger040831** [ACL4SSR/ACL4SSR#607]
![Screenshot_20210531-000407](https://user-images.githubusercontent.com/84896599/120111375-4b79c180-c1a4-11eb-84ff-4c36e56cdbff.png)

> kha.g.img.13th.tech match Match() using 🐟 漏网之鱼[🇯🇵 日本 |流媒体|NF=SG|X1|Linode Japan 1]

> lux1.g.img.13th.tech match Match() using 🐟 漏网之鱼[🇯🇵 日本 |流媒体|NF=SG|X1|Linode Japan 1]

> 这两个貌似是域名

**Comment by leosam2048** [comment]
fixed
