### ISSUE TITLE
用这个规则一段时间后容易出现断流和不稳定的情况

### ISSUE THREAD

**Issue by OXERIS** [ACL4SSR/ACL4SSR#612]
如题，不论cfw，还是cfa，我都遇到了这种情况，能通过重启客户端恢复。
但是使用其他规则就没有问题

**Comment by BROBIRD** [comment]
不上传日志，这是要我们帮你算命吗？

**Comment by OXERIS** [comment]
不知道日志在哪，有个记录发起链接的日志有用吗？

BROBIRD ***@***.***> 于 2021年6月22日周二 21:37写道：

**Comment by OXERIS** [comment]
> 不上传日志，这是要我们帮你算命吗？
以前的日志似乎没保存，需要重新测试一段时间，问题先别关吧
