### ISSUE TITLE
redirector.gvt1.com直连报400

### ISSUE THREAD

**Issue by AoEiuV020** [ACL4SSR/ACL4SSR#615]
走代理正常，这域名是不是无法直连了，
下载android studio时卡在这步，
https://redirector.gvt1.com/edgedl/android/studio/install/4.2.2.0/android-studio-ide-202.7486908-windows.exe

**Comment by Arunmor1510** [comment]
这个域名是跳转用的域名，请求之后会重定向到实际的下载服务器。经过测试，不管跳转还是下载在国内都是正常的。有可能你分配到的下载服务器是有问题的（猜测可能是四川移动的IP？），建议放出完整日志。

**Comment by dev4u** [comment]
google相关的域名，建议全部走代理，哪怕是在国内能够直连得上的。

**Comment by BROBIRD** [comment]
@dev4u 如果有特殊需求可以自行修改配置

**Comment by dev4u** [comment]
> @dev4u 如果有特殊需求可以自行修改配置

你说得没错。不过太多选择给他们，可能不是什么好事。
