### ISSUE TITLE
运营商广告IP有误伤

### ISSUE THREAD

**Issue by cyouhi** [ACL4SSR/ACL4SSR#62]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
101.227.200.22 此IP为 爱奇艺轮播台所用IP
61.160.200.242/16 这段IP是否写错了？是不是61.160.200.242/32？

**Comment by leosam1995** [comment]
删掉啦
