### ISSUE TITLE
规则设定里面，Netflix只能选择direct，没有proxy可选

### ISSUE THREAD

**Issue by iamjimmycheng** [ACL4SSR/ACL4SSR#620]
规则设定里面，Netflix只能选择direct，没有proxy可选；

这问题好久了，能更新一下吗？

**Comment by leosam2048** [comment]
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT



不是有好多选项吗
