### ISSUE TITLE
steam规则好混乱啊，下载游戏的时候会直连到香港新加坡的服务器

### ISSUE THREAD

**Issue by Faramitas** [ACL4SSR/ACL4SSR#621]
我用的redirhost模式的，open clash

**Comment by Faramitas** [comment]
一年了好像还是没有解决

**Comment by Faramitas** [comment]
steamstatic.com
steampowered.com
steam-chat.com
建议这三个改为全球直连，这样登陆的时候就不会认到国外，并且，steam应该只需要社区代理就可以了
我把这三个改为直连后，似乎结局了这个问题。

**Comment by leosam2048** [comment]
已经在代理中删掉了。过会更新一下，如果还有问题，再comment

**Comment by Faramitas** [comment]
> 已经在代理中删掉了。过会更新一下，如果还有问题，再comment

好的，麻烦你了，我更一下看看

**Comment by Faramitas** [comment]
> > 已经在代理中删掉了。过会更新一下，如果还有问题，再comment
> 
> 好的，麻烦你了，我更新一下看看
