### ISSUE TITLE
能给一个ini文件编写的教程吗？

### ISSUE THREAD

**Issue by yeiiii** [ACL4SSR/ACL4SSR#626]
我想自己写一个ini配置文件，找了好久都没有找到教程

**Comment by zhongfly** [comment]
https://github.com/tindy2013/subconverter/blob/master/README-cn.md#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE

**Comment by ResidualBlood** [comment]
如果你是自建转换后需要配置ini
可以参考下我的博客一系列记录[https://lwnlh.com/14.html](https://lwnlh.com/14.html)
