### ISSUE TITLE
cdnjs.tacool.com  误封

### ISSUE THREAD

**Issue by itcut** [ACL4SSR/ACL4SSR#63]
https://bbs.kafan.cn/ 在加载网页前会先加载两个js用于防护，EasyListChina中存在tacool.com，会导致网页一直处于加载中，请移除

![image](https://github.com/ACL4SSR/ACL4SSR/assets/115387130/32099cd0-8fec-4deb-99f4-85455407f985)

**Comment by acl4ssr-sub** [comment]
已经没了
