### ISSUE TITLE
Facebook ip-cidr 组中的部分域名指向youtube

### ISSUE THREAD

**Issue by ForestL18** [ACL4SSR/ACL4SSR#635]
![image](https://user-images.githubusercontent.com/45709305/131882519-fc3a3d95-9dad-460c-9192-3b3abbe191cc.png)

**Comment by ForestL18** [comment]
@leosam2048

**Comment by ForestL18** [comment]
![image](https://user-images.githubusercontent.com/45709305/131882677-bb88ae36-90bf-42f9-968c-c1c1764e4b16.png)

**Comment by leosam2048** [comment]
但这个看归属确实是facebook的

**Comment by ForestL18** [comment]
难道机场的dns被污染了？
