### ISSUE TITLE
Clash 规则没有考虑通过主机名访问局域网的情况

### ISSUE THREAD

**Issue by necan** [ACL4SSR/ACL4SSR#639]
虽然匹配了局域网的 IP 段，但有些人会用主机名访问，比如我，默认的规则会导致按“漏网之鱼”代理走，建议添加一条

```
GEOIP,LAN,🎯 全球直连
```

即可解决此问题

**Comment by leosam2048** [comment]
@necan 不太管用吧，我配置了一下，本地启动了一个8888端口，
访问http://localtest.me:8888/  还是走漏网之鱼啊

**Comment by necan** [comment]
@leosam2048 你确定你的本机 hostname 是 localtest.me 吗？如果你只是单纯的在本地 hosts 文件加的 localtest.me 是没有用的。路由器的 DHCP 表中记录了 hostname 和 IP 的对应关系，`GEOIP,LAN,🎯 全球直连` 就是把 DNS 解析交给路由器，路由器通过 DCHP 表可以查到正确的 IP。

**Comment by necan** [comment]
@leosam2048 你必须把系统的主机名改为 localtest.me 或者直接在路由上的DHCP分配处手动指定。

**Comment by leosam2048** [comment]
添加了
