### ISSUE TITLE
是否能添加一下 全局走代理 屏蔽广告

### ISSUE THREAD

**Issue by Biu95** [ACL4SSR/ACL4SSR#65]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：能不能国内外都走代理而且屏蔽广告

**Comment by BROBIRD** [comment]
可以描述一下您是想用在什么样的场景下吗？

**Comment by sumsethan** [comment]
onlybanAD不就是么

**Comment by BROBIRD** [comment]
= =我才发现我傻了
