### ISSUE TITLE
fonts.gstatic.com

### ISSUE THREAD

**Issue by charlestang** [ACL4SSR/ACL4SSR#657]
这个域名经常会突然访问失败。这个规则是配置成全球直连的。GoogleCN.list 里面的。但是我认为这个每个月有两三次是完全无法直连访问的。是不是考虑加到代理列表里？

这个资源会导致 google 依赖的一些字体文件失效，导致很多界面图标变成了字符串。会撕裂整个页面无法正常显示。

**Comment by BROBIRD** [comment]
@charlestang 请检查你的DNS是否配置正确

**Comment by charlestang** [comment]
@BROBIRD  谢谢回复，DNS 我配置的 4.2.2.2, 4.2.2.1, 119.29.29.29, 223.5.5.5

**Comment by BROBIRD** [comment]
@charlestang 你需要检查一下出问题的域名是否正确返回了位于中国大陆的IP地址，如果不正确，应该想办法让这些域名由中国大陆的DNS进行解析，或者使用hosts

**Comment by Sansui233** [comment]
挖个坟，我这边也有时会出现这个问题，后面发现是浏览器开了 AdBlock 的关系，关掉相关的广告屏蔽就好了。原因是 fonts.google.com 是 gstaticadssl.l.google.com 的 CNAME。

```sh
$ nslookup fonts.gstatic.com 223.5.5.5
Server:		223.5.5.5
Address:	223.5.5.5#53

Non-authoritative answer:
fonts.gstatic.com	canonical name = gstaticadssl.l.google.com.
Name:	gstaticadssl.l.google.com
Address: 142.250.204.67
```
