### ISSUE TITLE
Clash/Providers/ChinaIp.yaml 格式无法被视频

### ISSUE THREAD

**Issue by wxchil** [ACL4SSR/ACL4SSR#66]
下图这个无法识别
<img width="492" alt="image" src="https://github.com/ACL4SSR/ACL4SSR/assets/44988562/89cf7b6b-3dba-46f7-ad23-119d271a93fb">

IPV6的可以
<img width="470" alt="image" src="https://github.com/ACL4SSR/ACL4SSR/assets/44988562/3483baee-8f03-4644-a230-e1004addf4d6">

**Comment by acl4ssr-sub** [comment]
ChinaIp.yaml 格式为 ipcidr
