### ISSUE TITLE
WhatsApp无法使用

### ISSUE THREAD

**Issue by YandexStudio** [ACL4SSR/ACL4SSR#66]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
 请求将whatsapp.net和whatsapp.com强制使用远程DNS

**Comment by BROBIRD** [comment]
能否提供一下抓包的信息？谢谢！

**Comment by BROBIRD** [comment]
根据现有的信息判断，似乎这几个域名并没有被DNS污染

**Comment by YandexStudio** [comment]
> 根据现有的信息判断，似乎这几个域名并没有被DNS污染

所有国内解析到的都在省级节点处空路由

**Comment by BROBIRD** [comment]
不是DNS的问题，代理列表里面的域名肯定是远程解析的

**Comment by BROBIRD** [comment]
花了很长时间研究，不知道原因是什么，希望您能提供更多信息
