### ISSUE TITLE
希望添加哔哩哔哩东南亚版 bilibili.tv 视频 cdn

### ISSUE THREAD

**Issue by CytusWS** [ACL4SSR/ACL4SSR#667]
`upos-bstar1-mirrorakam.akamaized.net`
<img width="341" alt="Screen Shot 2021-12-16 at 23 12 53" src="https://user-images.githubusercontent.com/63197619/146397444-5ec8c2e1-bd21-4a5a-ae56-aa353853967c.png">

**Comment by leosam2048** [comment]
添加了，还添加了另外几条

DOMAIN,p.bstarstatic.com
DOMAIN,p-bstarstatic.akamaized.net
DOMAIN,upos-hz-mirrorakam.akamaized.net
DOMAIN,upos-bstar-mirrorakam.akamaized.net
DOMAIN,upos-bstar1-mirrorakam.akamaized.net

**Comment by Jiew-KueJwiaeng** [comment]
这个p.bstarstatic.com主要是起什么作用的？
