### ISSUE TITLE
关于领英规则问题

### ISSUE THREAD

**Issue by cheneyxx** [ACL4SSR/ACL4SSR#668]
现在访问linkedin.com 会重定向到linkedin.cn 需要强制走代理而不是直连了

**Comment by edkkb** [comment]
我已经设置走代理的但是还是会重定向到LinkedIn.cn问下如何强制走代理，

**Comment by cheneyxx** [comment]
把规则里direct改成proxy

edkkb ***@***.***> 于 2021年12月21日周二 09:27写道：

**Comment by leosam2048** [comment]
添加到代理了
