### ISSUE TITLE
是否可以将 acl 文件 转为 user.rule 文件?

### ISSUE THREAD

**Issue by arfaWong** [ACL4SSR/ACL4SSR#67]
是否可以将 acl 文件 转为 user.rule 文件?

**Comment by BROBIRD** [comment]
手动转呗……

**Comment by BROBIRD** [comment]
话说你的需求是什么

**Comment by arfaWong** [comment]
@BROBIRD 我想在 C# 客户端上使用 banAD.acl 这个规则

**Comment by BROBIRD** [comment]
PC上有很多更好的去广告软件，没有必要用ACL。给你推荐一个[ADM](http://www.admflt.com)。然后代理的部分你用PAC一般就可以了。
因为做一个user.rule实在是太费时间，两者语法和格式差异比较大，所以我们不打算为每一个ACL创建一个user.rule版本，请您谅解。

**Comment by arfaWong** [comment]
好叻
