### ISSUE TITLE
建议添加 jsdelivr 的代理

### ISSUE THREAD

**Issue by EndureBlaze** [ACL4SSR/ACL4SSR#671]
现在国内 cdn 证书炸了，不知道什么时候恢复

**Comment by BROBIRD** [comment]
@EndureBlaze 现在不是已经切换到 Fastly 了吗？

**Comment by RSSYLY** [comment]
我这边还是炸的

**Comment by BROBIRD** [comment]
@RSSYLY 清一下DNS缓存

**Comment by EndureBlaze** [comment]
> 

我的意思是，还有很多第三方网站使用 jsdelivr，现在无法访问，如果我需要代理 jsdelivr 的话就需要使用全局模式，或者自己修改规则，但是自己修改会在下次更新定义之后被覆盖掉

**Comment by EndureBlaze** [comment]
> @EndureBlaze 现在不是已经切换到 Fastly 了吗？

我的意思是，现在有很多第三方的网站还在使用 jsdelivr 导致无法访问，如果我想代理 jsdelivr 的话要么使用全局代理，要么手动添加规则，但是更新订阅之后会被覆盖。这两种方式都不太方便。

**Comment by leosam2048** [comment]
已删除对jsdelivr的直连，走默认兜底代理即可
