### ISSUE TITLE
哔哩哔哩代理问题

### ISSUE THREAD

**Issue by gingerbreap** [ACL4SSR/ACL4SSR#673]
`www.bilibili.tv`
已知这个域名是b站东南亚（泰国）版，且
`global.bilibili.com`
也会重定向到这个地址，该网址下所有的页面在检测到为【中国大陆、香港、澳门、台湾】地区IP时会自动拒绝访问
现在的政策貌似是将其与主站（bilibili.com）相同处理于【哔哩哔哩】代理组下，但这难免会出现一方打得开，另一方却打不开的问题
因此，是否需要将其另划代理组为【哔哩哔哩东南亚】？

附：东南亚版域名、CDN相关列表（#667）
```
DOMAIN,www.bilibili.tv
DOMAIN,p.bstarstatic.com
DOMAIN,p-bstarstatic.akamaized.net
DOMAIN,upos-hz-mirrorakam.akamaized.net
DOMAIN,upos-bstar-mirrorakam.akamaized.net
DOMAIN,upos-bstar1-mirrorakam.akamaized.net
```

**Comment by leosam2048** [comment]
@gingerbreap BilibiliHMT.list 里面都有。比这个还能全一些

**Comment by gingerbreap** [comment]
@leosam2048 那至少我觉得【东南亚哔哩哔哩】不应该和哔哩哔哩主站放到同一组，或者至少放到常驻代理组而非direct组，以保证两方都能正常打开😢

**Comment by leosam2048** [comment]
@gingerbreap 如果不加主站的话，有些人用APP的，可能切换不到国外去

**Comment by gingerbreap** [comment]
@leosam2048 我的建议是，对于常用的几个列表，可以把平常并不常用的东南亚的加到【国外媒体】组，这样可以保证列表的简洁，现有的【哔哩哔哩】组改为【哔哩主站】，更新日志里说明一下。这样会不会更好一点？

**Comment by leosam2048** [comment]
@gingerbreap BilibiliHMT 去掉主站了。
如果bilibili要区分国内外的话。推荐自制配置文件吧

**Comment by gingerbreap** [comment]
@leosam2048 HMT去掉主站反而可能会出问题……害 算了 感觉也不是很好处理东南亚bilibili和两岸四地哔哩哔哩的规则……

**Comment by Jiew-KueJwiaeng** [comment]
哇，才知道哔哩哔哩有东南亚版，这具体是指哪些国家的服务？我简单搜索了下，就只有关于泰国和马来西亚的消息，是只限这两个国家吗？还是“泰国”和“东南亚”又各自分一个版？

**Comment by gingerbreap** [comment]
> 哇，才知道哔哩哔哩有东南亚版，这具体是指哪些国家的服务？我简单搜索了下，就只有关于泰国和马来西亚的消息，是只限这两个国家吗？还是“泰国”和“东南亚”又各自分一个版？

都是同样的 只不过泰国解锁的番剧相对最多 所以东南亚会用泰国代称

另外 这个issue已经close了 想了解具体的话可以前往专门讨论泰区番剧的地方了解
https://github.com/ipcjs/bilibili-helper/issues/722
