### ISSUE TITLE
建议整一套tiktok分流规则

### ISSUE THREAD

**Issue by dddfgeer** [ACL4SSR/ACL4SSR#675]
做电商直播的 需要软路由分流tiktok规则 能不能解决谢谢

**Comment by leosam2048** [comment]
有。
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/TikTok.list
需要你自己做个配置文件即可

**Comment by SeanZheng11** [comment]
额，小白问一下怎么从这个tiktok.list 做成配置文件？

**Comment by Eden1114** [comment]
> 

每一行后面加一个`,<proxy_group_name>，`放到yaml配置文件里
