### ISSUE TITLE
ClashX Pro更新最新版，遇到的问题

### ISSUE THREAD

**Issue by renkx** [ACL4SSR/ACL4SSR#676]
![image](https://user-images.githubusercontent.com/26194193/148162875-72429b8f-5364-4af0-8e35-6df27acdfb5d.png)
ClashX Pro更新之后，ACL4SSR的规则里的vmess都不能用了，ClashX Pro回退上个版本就可以用了，有人遇到没

**Comment by mengdie101** [comment]
ws-opts那个地方不一样，要改成新格式
