### ISSUE TITLE
自建节点转化订阅链接遇到问题

### ISSUE THREAD

**Issue by itcodes** [ACL4SSR/ACL4SSR#679]
![telegram-cloud-photo-size-5-6264782608575606274-y](https://user-images.githubusercontent.com/8282645/149161355-2f4c2297-088f-43c0-b3f6-46cfa8d6477d.jpg)
自见梯子，添加配置文件后，如图所示。。求问下这个是啥原因？
难道是先添加订阅链接，再添加分流规则吗？
我用的是quantumultx

**Comment by leosam2048** [comment]
@itcodes 找个在线转换的吧。127.0.0.1是本地地址，应该是配置文件没弄好

**Comment by itcodes** [comment]
> @itcodes找个在线转换的吧。127.0.0.1是本地地址，应该是配置文件没弄好

谢谢。我试试
