### ISSUE TITLE
Clash 的规则文件 Download.yaml 为什么注释了？

### ISSUE THREAD

**Issue by lazureice** [ACL4SSR/ACL4SSR#681]
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/Download.yaml
我想使用您的规则，发现这个文件里很多规则都注释了，是因为在 Clash 中不生效吗？

**Comment by leosam2048** [comment]
@lazureice 感觉没啥用，你自己可以复制一份，把注释打开

**Comment by lazureice** [comment]
好的。
