### ISSUE TITLE
ACL文件中部分规则有重复

### ISSUE THREAD

**Issue by MkQtS** [ACL4SSR/ACL4SSR#684]
列表如下：

| 有效规则                   | 重复规则                  |
| -------------------------- | --------------------------------- |
| `(^\|\.)wip3\.adobe\.com$`  | `(^\|\.)ereg\.wip3\.adobe\.com$`; `(^\|\.)activate\.wip3\.adobe\.com$` |
| `(^\|\.)share\.baidu\.com$` | `(^\|\.)bdimg\.share\.baidu\.com$` |
| `(^\|\.)xtgreat\.com$`      | `(^\|\.)cc\.xtgreat\.com$`         |
| `(^\|\.)pos\.baidu\.com$`   | `(^\|\.)cm\.pos\.baidu\.com$`; `(^\|\.)snippet\.pos\.baidu\.com$`; `(^\|\.)wn\.pos\.baidu\.com$` |
| `(^\|\.)imageter\.com$` | `(^\|\.)d\.dsp\.imageter\.com$`|
| `(^\|\.)l\.ykimg\.com$` | `(^\|\.)p\.l\.ykimg\.com$` |
| `(^\|\.)(a\|adm\|adscdn\|afd\|als\|anquan\|appc\|as\|c\|cb\|cbjs\|cbjslog\|cjhq\|cpro\|cpro2\|cpu-admin\|crs\|drmcmm\|e\|eclick\|eiv)\.baidu\.(com\|cn)$` | `(^\|\.)s\.cpro\.baidu\.com$` |
| `(^\|\.)(pups\|rj\|rp\|spcode\|tk\|tuisong\|ucstat\|union\|utility\|utk\|videopush\|wangmeng\|wm\|znsv)\.baidu\.(com\|cn)$` | `(^\|\.)sa\.tuisong\.baidu\.com$` |
| `(^\|\.)pos\.baidu\.com$` | `(^\|\.)snippet\.pos\.baidu\.com$`; `(^\|\.)wn\.pos\.baidu\.com$`; `(^\|\.)cm\.pos\.baidu\.com$` |
| `(^\|\.)8le8le\.com$` | `(^\|\.)uat1\.bfsspadserver\.8le8le\.com$` |

**Comment by leosam2048** [comment]
参考
https://github.com/ACL4SSR/ACL4SSR/issues/623#issuecomment-886193384
