### ISSUE TITLE
请问安卓版CLASH能使用去广告规则吗

### ISSUE THREAD

**Issue by pekinghot** [ACL4SSR/ACL4SSR#686]
如果可以，有操作教程吗？我股沟翻了遍都没找到，求好心人谢谢😭

**Comment by leosam2048** [comment]
@pekinghot https://acl4ssr-sub.github.io/  复制一下你的订阅地址 选择一个配置文件。点击生成

**Comment by pekinghot** [comment]
> @pekinghot https://acl4ssr-sub.github.io/  复制一下你的订阅地址 选择一个配置文件。点击生成

爹，我有份自己整理的广告域名列表想要合并到BanAD.list里，应该怎么操作啊，是一份hosts，点我头像可以看到的

**Comment by pekinghot** [comment]
https://raw.githubusercontent.com/pekinghot/ACL4SSR/rm/PekinghotBanAD.list
刚上传好了

**Comment by cheneyxx** [comment]
@leosam2048 什么时候ACL4SSR_Online_NoReject.ini这些配置文件的转换能支持Clash v1.9.0 目前搭建好的转换出来新版客户端v2 ws的用不了

**Comment by leosam2048** [comment]
@cheneyxx 参考：https://github.com/tindy2013/subconverter/issues/442

**Comment by cheneyxx** [comment]
> @cheneyxx 参考：[tindy2013/subconverter#442](https://github.com/tindy2013/subconverter/issues/442)

感谢 我已经弄好了
