### ISSUE TITLE
关于自定义列表内容

### ISSUE THREAD

**Issue by pekinghot** [ACL4SSR/ACL4SSR#687]
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_AdblockPlus.ini
对上述的链接进行自定义，增加一行
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/pekinghot/ACL4SSR/rm/PekinghotBanAD.list
在其中，但clash订阅后却消失了谷歌FMC、应用净化、AdBlock的标签，却多了国内媒体的标签，请问是怎么回事呢？
如果我想把我的个人广告列表增添到本项目，又应该怎么做呢

**Comment by leosam2048** [comment]
你这个PekinghotBanAD.list 应该是行数太多了，订阅转换后端好像限制了最高3万条

另外不要用DOMAIN-KEYWORD, 用DOMAIN-SUFFIX,
