### ISSUE TITLE
关于 DNS 转发的问题

### ISSUE THREAD

**Issue by diobrando357** [ACL4SSR/ACL4SSR#69]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
最近换回 Android 做主力机，使用 SSR + banAD.acl，UDP 转发，没有分应用代理，国内 App 遇到走代理（可能）或者无法加载（确定）的问题，在微博客户端情况下最明显
经过多次尝试和研究，发现是因为开启了 DNS 转发的原因，但是 SSR 客户端不像原版 SS 客户端可以单独关闭 DNS 转发，是和 UDP 转发的开关在一起，我目前的科学上网服务在关闭 UDP 转发的情况下无法连接
想继续使用作者的 ACL 规则， 请问有解决方法吗？

**Comment by BROBIRD** [comment]
`我目前的科学上网服务在关闭 UDP 转发的情况下无法连接`
我不明白这是什么样的状况，能否详细说明？

**Comment by BROBIRD** [comment]
另外如果你R版出现APP走代理的话，原版同样会遇到这个问题。因为都是转发了所有DNS查询。

**Comment by diobrando357** [comment]
关闭「UDP 转发」无法连接是因为客户端的 BUG，提示「后台服务启动失败：无法连接远程服务器：length=1;index=1」
以我目前得到的信息：
原版是默认开启「UDP 转发」，并且不能关闭，只能关闭「DNS 转发」；
R 版是「UDP 转发」和「DNS 转发」都可以开启和关闭，但是是同一个开关，无法分别操作
我现在的情况是关闭「DNS 转发」的情况下一切正常
或者您可否告诉我 R 版客户端如何正确设置？是否需要设置 DNS？我看默认的有 China DNS 和 DNS 两个

**Comment by BROBIRD** [comment]
R版DNS是否转发是在ACL中定义的
两个DNS使用默认的配置就可以了
我也没有遇到过这种状况，所以……爱莫能助，请询问一下您的服务提供商

**Comment by BROBIRD** [comment]
您连接的服务器是否是域名形式的？这种情况我猜测可能是服务器域名被DNS污染了，您手动改成正确的IP地址试试

**Comment by diobrando357** [comment]
连接的服务器确实是域名形式的，刚刚尝试改为 IP 地址后还是一样的问题，我自己再想办法吧
总之感谢您的解答，谢谢！

**Comment by BROBIRD** [comment]
鄙人能力有限，确实是不知道如何解决，希望您能够找到解决方案，谢谢！
