### ISSUE TITLE
请将Xbox的下载域名加入到直连中，不然下载游戏走的是代理流量！

### ISSUE THREAD

**Issue by Lllinya** [ACL4SSR/ACL4SSR#692]
![image](https://user-images.githubusercontent.com/92159997/149865959-4d814ad4-6a98-47ec-9d52-e7b990458219.png)

**Comment by dykderrick** [comment]
xbox下载游戏的算法比较玄学，有时是连到微软的数据中心，有时是p2p下载

**Comment by loongfzs** [comment]
xbox下载用的akamai 的服务器，有的人与akamai连接太差，需要挂代理下载，建议你手动添加一下即可
