### ISSUE TITLE
日本圆谷官网被误杀屏蔽

### ISSUE THREAD

**Issue by KawausoJyou** [ACL4SSR/ACL4SSR#694]
网址是https://m-78.jp/
这是日本圆谷公司，也是奥特曼制作公司的官网，被规则误杀，希望可以解决一下。
谢谢。
![image](https://user-images.githubusercontent.com/92703641/150961844-ca1cb431-4ce2-4b89-8dad-a3e129063ee0.png)

**Comment by leosam2048** [comment]
已经删除
