### ISSUE TITLE
Surge 4 的转换链接自我更新url错误

### ISSUE THREAD

**Issue by Elias-Song** [ACL4SSR/ACL4SSR#699]
使用默认参数转换Surge 4 订阅。
在Surfboard中查看配置文件显示如下：
`#!MANAGED-CONFIG http://127.0.0.1:25500/sub?target=surge&ver=4&url=https%3A%2F%2F...`
导致不能更新订阅，因为指向了127.0.0.1的无效地址。正确地址应指向后端sub.id9.cc/

**Comment by leosam2048** [comment]
@Elias-Song 这个需要先对应的后端提供者改正

**Comment by Elias-Song** [comment]
@leosam2048 更换后端后正常了，非常感谢您的解答。
