### ISSUE TITLE
能否强制 WX 走PROXY？

### ISSUE THREAD

**Issue by nictse2013** [ACL4SSR/ACL4SSR#702]
？

**Comment by loongfzs** [comment]
自行添加即可

**Comment by nictse2013** [comment]
能说的具体点么？

**Comment by loongfzs** [comment]
就是wx加入代理并非大众人的需求，你可以在客户端手动修改一下配置文件。当然你也可以fork本项目，自行增删规则。

**Comment by loongfzs** [comment]
https://www.google.com/search?q=clash+%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6+%E7%BC%96%E8%BE%91
