### ISSUE TITLE
有自动测速的配置能否加入tolerance参数

### ISSUE THREAD

**Issue by exlulu** [ACL4SSR/ACL4SSR#705]
以FULL.INI为例
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
最后的50是否代表tolerance: 50？
但是生成订阅之后的配置如下，只有interval: 300，没有tolerance: 50
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AAA
      - BBB
这是转换BUG了吗？

**Comment by exlulu** [comment]
已确定为转换BUG，自建后端转换后就有tolerance参数了

**Comment by leosam2048** [comment]
@exlulu 这个得找转换服务的提供者改才行，我至少收集了几个后端，并无其权限

**Comment by exlulu** [comment]
> @exlulu 这个得找转换服务的提供者改才行，我至少收集了几个后端，并无其权限

我试了很多个在线转换都不行，最后用最新的v0.7.1版本后端自建就能正常转换出带tolerance参数的配置文件
