### ISSUE TITLE
请求将DOMAIN-SUFFIX,growingio.com移除广告联盟规则

### ISSUE THREAD

**Issue by wavecao** [ACL4SSR/ACL4SSR#706]
我注意到growingio.com被认为是国内广告联盟，但域名所有者同时也是正常的商业公司，我们日常要用到该公司的数据工具，是否可以考虑将该域名移除广告联盟

**Comment by Mythologyli** [comment]
这种现象还挺多，建议自行排除，用 Parsers 之类的

**Comment by leosam2048** [comment]
@wavecao 选择去广告的副作用，自己做个无去广告的或者无广告联盟配置的 配置文件吧
