### ISSUE TITLE
可以举例说明这些不同规则的使用场景嘛

### ISSUE THREAD

**Issue by Joehaivo** [ACL4SSR/ACL4SSR#71]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：请问列表里的默认代理和默认直连是针对什么来说的，不是很理解，还有白名单黑名单是在什么情况下使用呢，可以列举举个使用场景吗，非常感谢。

**Comment by BROBIRD** [comment]
首页的README.md不是有个表格吗_(:з」∠)_

**Comment by Joehaivo** [comment]
比如 backcn-banAD.acl | 直连 | 是 | 直连 | 有-代理 | 无 | 直连
直连是说当匹配到规则里的网址和ip是不走代理吗

**Comment by BROBIRD** [comment]
你看表格第一行的说明啊（😂
~~你这句话里有3个“直连”~~
你可以打开acl文件看一下，前几行也有语法说明
