### ISSUE TITLE
移动端爱奇艺会走代理

### ISSUE THREAD

**Issue by exlulu** [ACL4SSR/ACL4SSR#711]
使用ACL4SSR_Online_Full.ini

PC和电视的奇异果没有问题，移动端无论安卓还是IOS都是会提示【因版权问题，你所在的地区无法观看此视频】

**Comment by leosam2048** [comment]
发一下请求日志。
看看是那个域名被代理了

**Comment by exlulu** [comment]
> 发一下请求日志。 看看是那个域名被代理了

er..........我重启了一下CLASH就正常了，我当时看了下请求日志的，就是普通的 iqiyi.com，
data.video.iqiyi.com 等等
