### ISSUE TITLE
epsilon.com用于邮件内的图片加载

### ISSUE THREAD

**Issue by dykderrick** [ACL4SSR/ACL4SSR#714]
https://github.com/ACL4SSR/ACL4SSR/blob/093c3cdce886dd288f264cbb8f043ebe7d21f42c/Clash/BanAD.list#L192

FYI 各位如果发现有邮件的图片（比如National Geographic的邮件推送服务）无法加载，可能是因为用了这个网站。

<img width="650" alt="image" src="https://user-images.githubusercontent.com/33169107/158042083-30f79fe9-04e4-4e89-9654-11c214ef5244.png">

**Comment by leosam2048** [comment]
后续删除
