### ISSUE TITLE
转 surfboard，分组缺少「负载均衡」项

### ISSUE THREAD

**Issue by wolf3c** [ACL4SSR/ACL4SSR#715]
在「节点选择」分组中，有「负载均衡」选项，但后面实际并没有「负载均衡」选项，导致错误，弹窗提示无法导入。

![IMAGE 2022-03-14 14:50:26](https://user-images.githubusercontent.com/9410030/158119625-092149e5-ef71-40b2-a054-2a3a3d4e2580.jpg)

**Comment by leosam2048** [comment]
使用的是哪个配置？？

**Comment by leosam2048** [comment]
规则没问题
这个是转换服务有点问题，可以去https://github.com/tindy2013/subconverter 提问
我这里只能帮忙看看规则。
