### ISSUE TITLE
请问怎么配合ShadowsockX使用

### ISSUE THREAD

**Issue by tanglueyi** [ACL4SSR/ACL4SSR#72]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
请问要怎么配合ShadowsockX使用？具体配置教程有吗？

**Comment by BROBIRD** [comment]
你说的是 https://github.com/shadowsocks/ShadowsocksX-NG 吗？

**Comment by tanglueyi** [comment]
不好意思，是NG-R8

**Comment by BROBIRD** [comment]
@qinyuhang 老师做的那个吗？那应该有一个自定义规则的选项，替换里面的URL就可以了，入口你找一下，我上一次接触OSX还是很久以前，忘记具体的位置啦= =
