### ISSUE TITLE
开启规则后京东访问速度慢，无法访问等情况

### ISSUE THREAD

**Issue by LimeZky** [ACL4SSR/ACL4SSR#724]
开启规则后，发现京东无法正常访问，查阅log发现大量如下情况
![IMG_20220409_211612](https://user-images.githubusercontent.com/31511420/162579420-78543058-0b05-49c2-88cf-5778f520963b.jpg)
同时，微信部分头像无法正常加载，显示为原始头像

**Comment by BROBIRD** [comment]
截图看起来是你自己设备的网络有问题，和规则无关

**Comment by 47987** [comment]
> 开启规则后，发现京东无法正常访问，查阅log发现大量如下情况 ![IMG_20220409_211612](https://user-images.githubusercontent.com/31511420/162579420-78543058-0b05-49c2-88cf-5778f520963b.jpg) 同时，微信部分头像无法正常加载，显示为原始头像

我也是一样的情况，请问你解决了吗

**Comment by bamboo512** [comment]
I have the same issue like yours. But after closing Clash, it seems to have no problem.
![Screenshot_2023-02-18-15-59-57-537_com github kr328 clash-edit](https://user-images.githubusercontent.com/16702370/219849059-c038a8e0-1dc9-4e92-9018-afc8c03039b1.jpg)
