### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by Speechless22** [ACL4SSR/ACL4SSR#728]
希望Clash分流规则能加入Spotify的直连/代理选项，因为对于免费计划的Spotify，在大陆直连能够规避广告。

**Comment by ldsoy** [comment]
ACL4SSR这边大概是没有这些规则了，建议去这里https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash找Spotify规则，并fork一份acl的模板修改
