### ISSUE TITLE
SSR最新版本屏蔽应用广告不成功

### ISSUE THREAD

**Issue by ELOVSA** [ACL4SSR/ACL4SSR#73]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
在华为mate9上SSR屏蔽广告不成功啊

**Comment by BROBIRD** [comment]
检查你的设置

2017年11月23日 16:39，"ELOVSA" <notifications@github.com>写道：

**Comment by ELOVSA** [comment]
都是按照教程设置的呢，不过我用的是ssr最新版本的3.5.1.1

**Comment by BROBIRD** [comment]
没见过3.5.x……
另外您也没说是什么地方的广告无法屏蔽，具体配置也没有截图提供（发布之前请给敏感信息打码），我也没办法提供帮助呀= =

**Comment by ELOVSA** [comment]
怎么截图给你呢？

**Comment by BROBIRD** [comment]
评论里贴截图= =

**Comment by ELOVSA** [comment]
![_20171123172636](https://user-images.githubusercontent.com/33925014/33165952-7f7c2a7a-d073-11e7-8e88-2d4cf2688912.jpg)

**Comment by ELOVSA** [comment]
![_20171123172719](https://user-images.githubusercontent.com/33925014/33165974-961ee880-d073-11e7-9085-5e9edd616717.jpg)

**Comment by ELOVSA** [comment]
截图已附上，请帮忙看看哪里有问题

**Comment by BROBIRD** [comment]
配置似乎没什么问题，出现广告的位置是？

**Comment by ELOVSA** [comment]
APP开机报头，视频前贴片都有呢

**Comment by BROBIRD** [comment]
请理解本项目的功能局限性= =
我们并不能保证去除 现存的 所有的 广告，只是尝试去除= =很多广告的投放方式以SSR的功能实现是无能为力的。。。

**Comment by ELOVSA** [comment]
理解。我就是反馈下

**Comment by ELOVSA** [comment]
像这种app应用广告，如果关闭ssr的话，是不是后台会偷偷下载广告

**Comment by BROBIRD** [comment]
这要看下载的地址在不在屏蔽列表里了

**Comment by ELOVSA** [comment]
如果下载的地址在屏蔽列表里，SSR处于关闭状态  也能屏蔽么？

**Comment by BROBIRD** [comment]
当 然 不 能
