### ISSUE TITLE
微信知乎小程序，开启应用净化后，报错无网络连接

### ISSUE THREAD

**Issue by iPixelOldC** [ACL4SSR/ACL4SSR#730]
话说微信知乎小程序，在开启应用净化后，他就只让你看个主页，具体回答就基本不让你看了，关了就正常了...但我看日志，没找到是哪条规则影响了，连接的域名看上去都和没关前一样，再搜规则，也没发现有关的。所以有大佬知道是应用净化里哪条规则影响了嘛？求告知，谢谢

**Comment by wyangx** [comment]
拦截`sugar.zhihu.com`这个域名会导致看不了问答
我刚刚提pr了 #733

**Comment by Ayx03** [comment]
拦截此域名同时也会导致最新 Play 版应用「我的」页面下半部分包括创作中心在内的功能加载失败

**Comment by ldsoy** [comment]
建议直接把净化策略组选直连
![image](https://user-images.githubusercontent.com/67219859/177231146-982fd9ec-b3dc-4eae-ab9c-d1fac91c1a70.png)

**Comment by ldsoy** [comment]
我感觉净化也没个啥用，还老是出问题，我提交的最新的is就是因为净化规则导致的
