### ISSUE TITLE
Android原版SS客户端在自定义规则里以URL方式和剪贴板复制的方式添加banAD.acl后，Telegram无法连接，其他需要用到代理的应用均可正常连接。

### ISSUE THREAD

**Issue by airsontam** [ACL4SSR/ACL4SSR#74]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

**Comment by BROBIRD** [comment]
原版只能使用fullgfwlist.acl
