### ISSUE TITLE
策略无效？为什么全部连接都走“漏网之鱼”？

### ISSUE THREAD

**Issue by Ryan-yl** [ACL4SSR/ACL4SSR#744]
软路由OpenClash，试了ACL4SSR很多规则，已经为每种连接选择了相应的策略，如YouTube走美国，请问为什么查看连接时，所有连接都走“漏网之鱼”呢？这就等于按网站选节点的策略无效？该如何解决呢？

**Comment by sniper3209** [comment]
你试试FULL netfilx这条规则，我目前就是用的这个，目前没有出现你上述的问题。会不会有可能是你自建VPS或者是机场线路中转的问题？

**Comment by sniper3209** [comment]
我目前也遇到了这个情况，发现是模板的规则都没有了，所以才导致无法分流，目前原因未知

**Comment by sniper3209** [comment]
把原来的订阅删除，重新订阅一下，就ok了
