### ISSUE TITLE
请问在代理组中 Proxy Group中进一步过滤服务器节点？

### ISSUE THREAD

**Issue by dayunliang** [ACL4SSR/ACL4SSR#745]
![image](https://user-images.githubusercontent.com/36461319/166171560-7925e8b6-b40d-4614-aba5-37df5ac79f48.png)

如图中我想把红框中服务器节点过滤掉

**Comment by leosam2048** [comment]
可以写正则，具体的请参考
https://github.com/tindy2013/subconverter/blob/master/README-cn.md
