### ISSUE TITLE
Android ssr 使用后过滤广告效果很好，能否移植到Windows PC 下？

### ISSUE THREAD

**Issue by graminc** [ACL4SSR/ACL4SSR#75]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

Android ssr 使用后过滤广告效果很好，能否移植到Windows PC 下？
或者说怎么融合到 SSR C# 客户端目录下的user.rule？

感谢诸位作者的劳动，Android ssr 使用ACL4SSR后有一个清爽的互联网。

**Comment by BROBIRD** [comment]
#67

**Comment by graminc** [comment]
BROBIRD commented 12 days ago
PC上有很多更好的去广告软件，没有必要用ACL。给你推荐一个ADM。然后代理的部分你用PAC一般就可以了。
因为做一个user.rule实在是太费时间，两者语法和格式差异比较大，所以我们不打算为每一个ACL创建一个user.rule版本，请您谅解。

============================
理解。
感谢推荐！

**Comment by graminc** [comment]
不用pac，pac执行效率慢。
Chrome 、SwitchyOmega、socks5
Windows ssr c# 客户端
系统代理模式 保持当前状态不修改
代理规则  用户自定义，使用 绕过局域网和大陆 不管用，估计DNS污染严重，使用国外DNS不起作用。

**Comment by BROBIRD** [comment]
没明白……

**Comment by graminc** [comment]
> https://github.com/ACL4SSR/ACL4SSR/issues/75#issuecomment-346925103
纯属题外话
