### ISSUE TITLE
请在 /Clash/LocalAreaNetwork.list 中加入 224.0.0.0/4

### ISSUE THREAD

**Issue by Mirr0ch1** [ACL4SSR/ACL4SSR#758]
该地址为用于 Multicast 多播协议的保留地址，但目前不被 ACL4SSR/Clash 内的任何一个规则收录。
结果便是多播协议会跑进“漏网之鱼”策略中，造成不必要的流量跨墙。
![图片](https://user-images.githubusercontent.com/3250823/170177121-59f3c3bc-4841-4e5b-b234-c03d5814a371.png)

**Comment by BROBIRD** [comment]
done
https://github.com/ACL4SSR/ACL4SSR/blob/11cbcd236713d406ed90b7185f74a8942c111311/Clash/LocalAreaNetwork.list#L19
