### ISSUE TITLE
使用订阅转换后，如果给surge开启代理选项

### ISSUE THREAD

**Issue by wkumo** [ACL4SSR/ACL4SSR#759]
还是只能fork一份出来 开启代理？

**Comment by PingZi-Wing** [comment]
有Surge还用clash做什么，不理解

**Comment by wkumo** [comment]
> 

我是用surge的订阅 可是订阅转换后 生成的订阅文件里就没有了利用surge做代理的选项
比如httplisten之类的

**Comment by PingZi-Wing** [comment]
我用的quanX，直接在懒人配置基础上添加另外的规则引用，再开iCloud同步，iPhone、iPad共用一套配置。按理说surge添加规则引用应该很方便吧，不用走订阅转换。

**Comment by wkumo** [comment]
我用的是mac 顺便同步到iphone和ipad
