### ISSUE TITLE
在clash for Android中无法更新订阅，不使用订阅转换的是可以更新的

### ISSUE THREAD

**Issue by zcvxvx** [ACL4SSR/ACL4SSR#765]
之前是可以正常下载订阅信息和更新的，现在既不能下载也不能更新
![Screenshot_2022-06-10-18-50-41-0775607055_EDIT_1](https://user-images.githubusercontent.com/106616424/173050308-0d071bce-947c-4426-b3ab-e8c5b1f6a136.png)
错误信息如图

**Comment by Ayx03** [comment]
尝试替换后端地址
sub.id9.cc
sub.xeton.dev
api.dler.io
sub.maoxiongnet.com
或者自己在局域网里搭建一个 :)
