### ISSUE TITLE
请去除直连规则里的dl.google.com

### ISSUE THREAD

**Issue by LennoC** [ACL4SSR/ACL4SSR#77]
测试该链接并不能直连。
此域名用来下载chrome等google产品，默认规则里设为全球直连，但实际不能直连需要代理。

**Comment by BROBIRD** [comment]
https://ping.chinaz.com/dl.google.com
https://tool.chinaz.com/speedtest/dl.google.com
实测正常直连

**Comment by LennoC** [comment]
奇怪，我这里测试要下载更新chrome时会无法连接。看日志就是不能连上dl.google

BROBIRD ***@***.***> 于2023年8月11日周五 08:59写道：

**Comment by feisan** [comment]
浙江电信也是不能直连 dl.google

**Comment by wouiSB** [comment]
宁波电信实测可以

**Comment by cloudwindy** [comment]
请重新open，连不上

**Comment by WalkerManalone** [comment]
笑死，dl.google根本不存在
我用香港卡都打不开

**Comment by paperbluster** [comment]
完全无法直连

**Comment by realpg** [comment]
全国白名单直连

不能直连的, 检查你自己对dns瞎搞了什么...

**Comment by zzy659781** [comment]
dl.google.com在国内有服务器所以可以直连，可能有的地区有DNS污染给解析到了国外的Google服务器上所以无法直连

**Comment by realpg** [comment]
> dl.google.com在国内有服务器所以可以直连，可能有的地区有DNS污染给解析到了国外的Google服务器上所以无法直连

从来都不是因为dns污染 这个域名是白名单 
只有半桶水的自己瞎搞自己的DNS还没那个技术 域名丢给境外dns解析出国外IP然后连不上在这无能号角
