### ISSUE TITLE
ACL4SSR被搞了吗

### ISSUE THREAD

**Issue by git10135405** [ACL4SSR/ACL4SSR#775]
User ACL4SSR is blocked in China. Please refer to https://github.com/ACL4SSR/ACL4SSR instead. See https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net for more information.

**Comment by BROBIRD** [comment]
很久之前的事了

**Comment by git10135405** [comment]
> 很久之前的事了

我这周前都能用啊

**Comment by BROBIRD** [comment]
@git10135405 从很久之前开始中国大陆IP访问就一直是不可用的

**Comment by git10135405** [comment]
> @git10135405 从很久之前开始中国大陆IP访问就一直是不可用的

那就神奇了，我是这周才报错，上周没问题
