### ISSUE TITLE
Vivo手机智慧视觉里面提取文字功能的请求被关键字【analysis】规则识别过滤为广告，导致请求失败

### ISSUE THREAD

**Issue by ldsoy** [ACL4SSR/ACL4SSR#779]
<img src="https://user-images.githubusercontent.com/67219859/177145847-6130d481-d4de-4761-b7c4-17521147875b.png" width="60%">
今天使用vivo的智慧视觉的提取文字功能，请求被拦截，随后我把过滤广告的策略组改为直连就可以请求了
<img src="https://user-images.githubusercontent.com/67219859/177146481-e9b42c50-9461-48e0-8dab-fb4d1c2a4b5f.png" width="60%">

之后我在clash的日志中找到了被拦截的请求
![image](https://user-images.githubusercontent.com/67219859/177146624-4e27dc79-d41e-43b5-96a9-30b524626b16.png)

并且找到了相应的规则（规则文件：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list）
![image](https://user-images.githubusercontent.com/67219859/177146772-3c57349d-4eee-4de8-91b4-ff749c5aa507.png)

bug可以复现，已经提测，望修复

**Comment by leosam2048** [comment]
下次修复
