### ISSUE TITLE
广告拦截功能开启后，Disney+报错误93

### ISSUE THREAD

**Issue by Rennen0929** [ACL4SSR/ACL4SSR#805]
### 如图所示，希望广告拦截这里能放行该规则（ disney.demdex.net:443），否则Windows 10 UWP 版的 Disney+ 客户端会报错误代码93😥，谢谢开发者❤
![image](https://user-images.githubusercontent.com/89285206/185727510-b99b3976-1f59-422e-a02b-86e816817bd6.png)
![image](https://user-images.githubusercontent.com/89285206/185727517-5beb6ed4-80b7-4a2f-aadb-1f270333760e.png)

**Comment by leosam2048** [comment]
fixed
