### ISSUE TITLE
添加了如下开头代码clash就开始炸内存CPU了,这是为何?

### ISSUE THREAD

**Issue by xishijt** [ACL4SSR/ACL4SSR#812]
添加了如下开头代码clash就开始炸内存CPU了,这是为何?
`mixed-port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    listen: 0.0.0.0:53
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']`

![QQ截图20220830192231](https://user-images.githubusercontent.com/36976248/187424396-db6c757a-8589-43e7-8b2e-9001ca325087.png)
![QQ截图20220830192414](https://user-images.githubusercontent.com/36976248/187424545-15f99514-7cf6-41e1-aed2-84077f495f30.png)

**Comment by BROBIRD** [comment]
Clash配置问题请咨询Clash项目
