### ISSUE TITLE
quanx 规则解析错误

### ISSUE THREAD

**Issue by Mocaris** [ACL4SSR/ACL4SSR#814]
https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/BanEasyPrivacy.list

1415行

DOMAIN-SUFFIX,apester.com/event

圈x 解析器解析错误

<img width="540" alt="image" src="https://user-images.githubusercontent.com/14064316/188264212-b400d72f-d0e7-44e5-99ac-f744b7133084.png">

**Comment by BROBIRD** [comment]
Fixed.

**Comment by Mocaris** [comment]
还有几个同样的，我找了下

4136: DOMAIN-SUFFIX,hh.ru/analytics

5844: DOMAIN-SUFFIX,mercadolibre.com/tracks

7231: DOMAIN-SUFFIX,qzone.qq.com/wspeed.qq.com

**Comment by BROBIRD** [comment]
谢谢，如果暂时没有新的我就先关闭了
