### ISSUE TITLE
ViuTV 规则写法有问题，会导致多余匹配。

### ISSUE THREAD

**Issue by Fvr9W** [ACL4SSR/ACL4SSR#819]
本规则写法：
```DOMAIN-SUFFIX,cloudfront.net```
下面是其他写法：
https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/ViuTV.list
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/ViuTV.list

**Comment by leosam2048** [comment]
fixed
