### ISSUE TITLE
telegram IP 规则不全，实际上官方有提供官方版本的。

### ISSUE THREAD

**Issue by Fvr9W** [ACL4SSR/ACL4SSR#820]
官方地址：https://core.telegram.org/resources/cidr.txt
如果可以的话还可以加上程序名：
```
PROCESS-NAME,Telegram.exe
PROCESS-NAME,nekox.messenger
PROCESS-NAME,org.telegram.messenger
```

**Comment by Wrandz** [comment]
建议合并

**Comment by Karmylr** [comment]
acl4ssr貌似不看issues的

**Comment by leosam2048** [comment]
IP-CIDR,91.108.0.0/16,no-resolve
IP-CIDR,109.239.140.0/24,no-resolve
IP-CIDR,149.154.160.0/20,no-resolve
IP-CIDR6,2001:67c:4e8::/48,no-resolve
IP-CIDR6,2001:b28:f23d::/48,no-resolve
IP-CIDR6,2001:b28:f23f::/48,no-resolve

比上面的更多，我做了一些模糊策略。影响不大，但是条数更少
