### ISSUE TITLE
建议去掉BanEasyPrivacy两个域名

### ISSUE THREAD

**Issue by qifeng2233** [ACL4SSR/ACL4SSR#826]
REJECT BanEasyPrivacy里的data.bilibili.com和cm.bilibili.com会导致B站客户端无法刷新视频并提示数据错误

**Comment by Karmylr** [comment]
data.bilibili.com 不会导致
cm.bilibili.com 确实会导致

**Comment by leosam2048** [comment]
- DOMAIN-SUFFIX,cm.bilibili.com
已经删除
