### ISSUE TITLE
quanx 解析错误

### ISSUE THREAD

**Issue by Mocaris** [ACL4SSR/ACL4SSR#834]
更新后

错误同[#814](https://github.com/ACL4SSR/ACL4SSR/issues/814)

<img width="521" alt="image" src="https://user-images.githubusercontent.com/14064316/197438183-d20cc4ed-16b9-4fcb-a2a5-5aba337e0d96.png">

BanEasyList.list 也有报解析错误

<img width="510" alt="image" src="https://user-images.githubusercontent.com/14064316/197438209-b2f7def3-6f76-4ee0-ab87-3fed9cc48d71.png">

**Comment by leosam2048** [comment]
修复
