### ISSUE TITLE
去除腾讯视频app的广告失效

### ISSUE THREAD

**Issue by lxk0301** [ACL4SSR/ACL4SSR#84]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
不知道banAD.acl  是否可以去除腾讯视频app的广告，如果规则本身可以的话，那就是目前去除广告失效了

**Comment by leosam1995** [comment]
http://www.zdfans.com/6935.html 直接用去广告版的app吧
好多视频软件的广告域名和正常网站域名用的是一样的。
不敢太屏蔽的
