### ISSUE TITLE
添加对Hysteria://协议的支持

### ISSUE THREAD

**Issue by DoyoDia** [ACL4SSR/ACL4SSR#868]
Hysteria项目地址：https://github.com/apernet/hysteria
https://github.com/emptysuns/Hi_Hysteria
请求添加对Hysteria节点的支持，clash核心类型：clash.meta

**Comment by DoyoDia** [comment]
上游subconverter还没添加来着https://github.com/tindy2013/subconverter/issues/518
我还是先等等吧

**Comment by JamesLiu0802** [comment]
这是规则，不是代理协议，你找错地方了吧
