### ISSUE TITLE
Gmail中部分图标不显示

### ISSUE THREAD

**Issue by wjw020206** [ACL4SSR/ACL4SSR#876]
经过测试当使全局代理的时候，Gmail中的部分图标是显示的，但是使用 ACL4 SSR Online默认版分组比较全（与Github同步）会有部分图标不显示，排除了浏览器广告拦截插件的问题

问题如下：
![image](https://user-images.githubusercontent.com/59106659/211016860-4d107868-af14-4c04-8c1b-508c066aa6f1.png)

开全局代理时图标正常加载
![image](https://user-images.githubusercontent.com/59106659/211017048-41cf6dd0-96da-44e9-bc00-092d7ee34b61.png)

浏览器版本：Edge 108.0.1462.54 (正式版本) (64 位)
操作系统版本：Windows 10 专业版 22H2 (64 位)
Clash for Windows 版本：0.20.12 (64 位)

**Comment by leosam2048** [comment]
现在更新试试?
应该是ssl.gstatic.com 直连的原因，现在加到代理了

**Comment by wjw020206** [comment]
> 现在更新试试? 应该是ssl.gstatic.com 直连的原因，现在加到代理了

刚刚试了一下，已经可以了
