### ISSUE TITLE
[规则添加] 请求添加EA/Origin的Ruleset

### ISSUE THREAD

**Issue by sxyzy1016** [ACL4SSR/ACL4SSR#885]
EA App和Origin是目前常用的游戏平台之一，可以和Steam一样单独添加Ruleset，毕竟墙内访问很不稳定。

目前似乎全部落在了规则之外。

<img width="395" alt="屏幕截图 2023-01-12 221340" src="https://user-images.githubusercontent.com/16367112/212089500-2096af3c-1aa0-44e0-9f6f-1595f7e9610f.png">
<img width="385" alt="屏幕截图 2023-01-12 221400" src="https://user-images.githubusercontent.com/16367112/212089530-74c30fb3-b4aa-4541-97cc-8b690a2881f9.png">

**Comment by sxyzy1016** [comment]
域名大概有：

*.ea.com
*.origin.com
rtm.tnt-ea.com
eaasserts-a.akamaihd.net
originasserts.akamaized.net
cloudsync-prod.s3.amazonaws.com

**Comment by leosam2048** [comment]
我不太玩游戏，如果有时间可以帮忙整理一下具体规则吧

**Comment by acl4ssr-sub** [comment]
已添加
