### ISSUE TITLE
关于被某个运营商自己屏蔽的域名

### ISSUE THREAD

**Issue by cnperi** [ACL4SSR/ACL4SSR#89]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
m.readbook8.com 被中国移动屏蔽了，自我加压型的。能不能放到代理范围里面去？

**Comment by BROBIRD** [comment]
抱歉哈，这种域名我们不做处理，你可以自己fork一份修改使用
