### ISSUE TITLE
關於Clash規則中的游戲平臺分組的一些問題

### ISSUE THREAD

**Issue by LiHunghsuan** [ACL4SSR/ACL4SSR#902]
Windows 11 Clash for Windows v 0.20.16 TUN Mode

大佬，您好，我需要OBS實況推流到YouTube，所以需要開TUN Mode，同時需要用小黑盒加速器加速英雄聯盟台服，但是英雄聯盟進入游戲大廳會瘋狂掉綫重連又掉綫。

是否因爲游戲加速器跟Clash中的規則會互相衝突導致，以及如何能解決這一問題，希望大佬可以解決一下，非常感謝！

**Comment by leosam2048** [comment]
感觉跟游戏平台的规则没啥关系，应该是tun模式导致英雄联盟玩不了
可以试试关闭tun，然后obs使用PROCESS-NAME试试
