### ISSUE TITLE
该项目还有人管吗？提交的PR一个多月了还没被review及merge

### ISSUE THREAD

**Issue by dijingkai** [ACL4SSR/ACL4SSR#909]
该项目还有人管吗？提交的PR #887  一个多月了还没被review及merge。希望有管理权限的人帮忙review及merge一下吧，谢谢

**Comment by hudingwen** [comment]
基本上没有了吧，都是自己fork然后自己改吧，我都是象征性的PR一下。

**Comment by leosam2048** [comment]
平均一个月搞一次吧
