### ISSUE TITLE
请添加onenote的相关域名走代理

### ISSUE THREAD

**Issue by ChicBrother** [ACL4SSR/ACL4SSR#91]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [x] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

因onenote在国内直接使用经常同步不了，如果 走代理的话则很顺利。已经捉取了Onenote app的相关域名,分别是 （主域名）
live.net
live.com
onenote.com
请添加，谢谢。

**Comment by leosam1995** [comment]
ok 今天抽空加上

**Comment by HonorWater** [comment]
发现最近onenote好像有点抽风，不开SSR基本都能正常更新，但是开了，不论用什么规则，基本就断断续续的连不上。不知是不是onenote的域名跟排除中国大陆地区IP冲突了。
