### ISSUE TITLE
ProxyGFWlist.list的 国家代码，可能会导致有些会议app走代理，比如 zoom.us 

### ISSUE THREAD

**Issue by babylife** [ACL4SSR/ACL4SSR#912]
作者是否考虑优化下？
DOMAIN-SUFFIX,eu
DOMAIN-SUFFIX,hk
DOMAIN-SUFFIX,jp
DOMAIN-SUFFIX,kr
DOMAIN-SUFFIX,sg
DOMAIN-SUFFIX,tw
DOMAIN-SUFFIX,uk
DOMAIN-SUFFIX,us
DOMAIN-SUFFIX,ca

**Comment by leosam2048** [comment]
把DOMAIN-SUFFIX,us去掉了
