### ISSUE TITLE
请求添加chatgpt相关分流

### ISSUE THREAD

**Issue by Wyatt323** [ACL4SSR/ACL4SSR#913]
目前的域名应该是下面的
DOMAIN-SUFFIX,openai.com
DOMAIN-SUFFIX,chat.openai.com
DOMAIN-SUFFIX,challenges.cloudflare.com
DOMAIN-SUFFIX,chat.openai.com
DOMAIN-SUFFIX,auth0.openai.com
DOMAIN-SUFFIX,ai.com
我将这些域名添加进配置文件，同时创了一个chatgpt组可以手动选择节点（选择的是可以上gpt的节点）
最后还是无法访问chatgpt

**Comment by Wyatt323** [comment]
wc解决了，openclash要开tun模式才能把上面的分流，有老大解释一下为啥吗

**Comment by xuexin** [comment]
@Wyatt323 你好，我也想对chatgpt进行分流，但是之前完全没接触过这些的配置，请问要添加到哪里？

**Comment by leosam2048** [comment]
已添加
