### ISSUE TITLE
建议将育碧(Ubisoft)相关域名移除"漏网之鱼"分组,  转至"游戏平台"分组

### ISSUE THREAD

**Issue by desslie047** [ACL4SSR/ACL4SSR#917]
由于育碧旗下的游戏启动平台Ubisoft connect(Uplay)是依据登录时的IP地址来判断玩家是否需要进行二步验证(2FA),  该域名在大陆通常可以直接访问,  而使用代理工具登录平台,  常常会因为节点变动而被要求重新输入账密,  并输入邮箱验证码,  从而引起较多烦扰.

希望将以下两个与下载游戏无关的域名前缀添加至"游戏平台"分组,  以便用户做出灵活的决定

ubi.com
ubisoft.com

![图片](https://user-images.githubusercontent.com/80453485/223997654-105ff6ae-9b68-4eb4-9c4a-dacefe454a71.png)

**Comment by leosam2048** [comment]
这个网址感觉最好自己做个规则，自用吧
