### ISSUE TITLE
关于nobanAD.acl的说明

### ISSUE THREAD

**Issue by zhxhwyzh14** [ACL4SSR/ACL4SSR#92]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [x] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [x] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
关于nobanAD.acl的说明，国内域名不应该是直连嘛？怎么回事代理？还是我理解错了？感觉要是直连的话会更好啊，相比banAD.acl只是少了一个去广告功能。
最后再次感谢开发者一直以来的更新与耐心回复！

**Comment by BROBIRD** [comment]
看首页说明

**Comment by zhxhwyzh14** [comment]
你好，我就是不太明白首页的说明。既然nobanAD.acl是“白名单，无去广告”。那么为什么会是“常用域名-代理”呢？难道不应该是“常用域名-直连”嘛？

**Comment by BROBIRD** [comment]
写错了。。

**Comment by zhxhwyzh14** [comment]
好的 谢谢
