### ISSUE TITLE
希望能加入这些广告域名，括pixiv和雅虎的一些广告

### ISSUE THREAD

**Issue by MundaneDefoliation** [ACL4SSR/ACL4SSR#93]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [ ] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [ ] 报告错误
- [x] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：

(^|\.)\w*tapone\w*\.\w*$
(^|\.)\w*umeng\w*\.\w*$
(^|\.)\w*jpush\w*\.\w*$
(^|\.)\w*umengcloud\w*\.\w*$
(^|\.)\w*nxliyuan\w*\.\w*$
(^|\.)\w*rd\.ane\.yahoo\w*\.\w*$
(^|\.)rd\.ane\.yahoo\w*\.\w*$
(^|\.)rd\.yahoo\w*\.\w*$
(^|\.)geo\.query\.yahoo\w*\.\w*$
(^|\.)ybp\.yahoo\w*\.\w*$
(^|\.)ybx\.yahoo\w*\.\w*$
(^|\.)yeas\.yahoo\w*\.\w*$
(^|\.)yjaxc\.yahoo\w*\.\w*$
(^|\.)\w*yads\w*\..*$
(^|\.)\w*adservice\w*\..*$
(^|\.)\w*ads\w*\..*$
(^|\.)\w*adyun\w*\..*$
(^|\.)pdgt\.gtimg\.cn\/get\/0\..*$
(^|\.)11h5\.com$
(^|\.)googleads\.g\.doubleclick\..*$
(^|\.)googleads\.g\.doubleclick\.net\..*$

**Comment by leosam1995** [comment]
这些已经有了
(^|.)\wumengcloud\w.\w*$
(^|.)\wumeng\w.\w*$
(^|.)\wjpush\w.\w*$
(^|.)googleads.g.doubleclick..$
(^|.)googleads.g.doubleclick.net..$

雅虎的 国内有用的吗？ 一般都是什么软件 

还有这个 wads  是那个网站的 

11h5.com 这个不是广告域名啊
(^|.)pdgt.gtimg.cn/get/0..$ 这个也不合法

请挨个解释一下

**Comment by leosam1995** [comment]
差不多能加的 都加了
