### ISSUE TITLE
Twitter客户端不显示图片

### ISSUE THREAD

**Issue by hfzgvxldnmvs** [ACL4SSR/ACL4SSR#94]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [ ] backcn-banAD.acl
- [x] banAD.acl
- [ ] fullgfwlist.acl
- [ ] gfwlist-banAD.acl
- [ ] gfwlist-user.rule
- [ ] nobanAD.acl
- [ ] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
图片无法加载，不使用acl后恢复正常

**Comment by leosam1995** [comment]
你现在试试？ 我把Twitter的图片域名加进代理了

**Comment by hfzgvxldnmvs** [comment]
对了
