### ISSUE TITLE
用了规则,王者荣耀都打不了.走代理了

### ISSUE THREAD

**Issue by fewpiwork** [ACL4SSR/ACL4SSR#95]
* 有关此issue的规则名称：(请将“[ ]”中的空格替换为小写英文字母“x”以勾选)
- [x] backcn-banAD.acl
- [x] banAD.acl
- [x] fullgfwlist.acl
- [x] gfwlist-banAD.acl
- [x] gfwlist-user.rule
- [x] nobanAD.acl
- [x] onlybanAD.acl

* 您提交此issue的目的是：
- [x] 报告错误
- [ ] 提交广告域名
- [ ] 提交代理/直连域名
- [ ] 其他问题

* 有关GFW的域名请先[提交给GFWList项目](https://github.com/gfwlist/gfwlist/issues/new)
---
* 您要反馈的问题：
`用了规则,王者荣耀都打不了.走代理了`

**Comment by leosam1995** [comment]
分应用代理吧。
